// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: migratorservice.proto

package migratorconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	migrator "github.com/multigres/multigres/go/pb/migrator"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// MigratorName is the fully-qualified name of the Migrator service.
	MigratorName = "migrator.Migrator"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// MigratorCreateMigrationProcedure is the fully-qualified name of the Migrator's CreateMigration
	// RPC.
	MigratorCreateMigrationProcedure = "/migrator.Migrator/CreateMigration"
	// MigratorStartMigrationProcedure is the fully-qualified name of the Migrator's StartMigration RPC.
	MigratorStartMigrationProcedure = "/migrator.Migrator/StartMigration"
	// MigratorUpdateMigrationProcedure is the fully-qualified name of the Migrator's UpdateMigration
	// RPC.
	MigratorUpdateMigrationProcedure = "/migrator.Migrator/UpdateMigration"
	// MigratorGetMigrationsProcedure is the fully-qualified name of the Migrator's GetMigrations RPC.
	MigratorGetMigrationsProcedure = "/migrator.Migrator/GetMigrations"
	// MigratorSetMigrationDirectionProcedure is the fully-qualified name of the Migrator's
	// SetMigrationDirection RPC.
	MigratorSetMigrationDirectionProcedure = "/migrator.Migrator/SetMigrationDirection"
	// MigratorDropMigrationProcedure is the fully-qualified name of the Migrator's DropMigration RPC.
	MigratorDropMigrationProcedure = "/migrator.Migrator/DropMigration"
)

// MigratorClient is a client for the migrator.Migrator service.
type MigratorClient interface {
	// CreateMigration records a migration's configuration (no database changes).
	CreateMigration(context.Context, *connect.Request[migrator.CreateMigrationRequest]) (*connect.Response[migrator.CreateMigrationResponse], error)
	// StartMigration runs the workflow: validate, schema copy, publication,
	// subscription, and initial catch-up.
	StartMigration(context.Context, *connect.Request[migrator.StartMigrationRequest]) (*connect.Response[migrator.StartMigrationResponse], error)
	// UpdateMigration changes mutable fields (field-masked), notably the source
	// connection.
	UpdateMigration(context.Context, *connect.Request[migrator.UpdateMigrationRequest]) (*connect.Response[migrator.UpdateMigrationResponse], error)
	// GetMigrations returns status for one migration (id set) or all migrations.
	GetMigrations(context.Context, *connect.Request[migrator.GetMigrationsRequest]) (*connect.Response[migrator.GetMigrationsResponse], error)
	// SetMigrationDirection sets the active direction (IMPORT or EXPORT).
	SetMigrationDirection(context.Context, *connect.Request[migrator.SetMigrationDirectionRequest]) (*connect.Response[migrator.SetMigrationDirectionResponse], error)
	// DropMigration tears down the subscription/publication/slot and removes
	// the workflow (default drains first; wait/force modify that).
	DropMigration(context.Context, *connect.Request[migrator.DropMigrationRequest]) (*connect.Response[migrator.DropMigrationResponse], error)
}

// NewMigratorClient constructs a client for the migrator.Migrator service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewMigratorClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) MigratorClient {
	baseURL = strings.TrimRight(baseURL, "/")
	migratorMethods := migrator.File_migratorservice_proto.Services().ByName("Migrator").Methods()
	return &migratorClient{
		createMigration: connect.NewClient[migrator.CreateMigrationRequest, migrator.CreateMigrationResponse](
			httpClient,
			baseURL+MigratorCreateMigrationProcedure,
			connect.WithSchema(migratorMethods.ByName("CreateMigration")),
			connect.WithClientOptions(opts...),
		),
		startMigration: connect.NewClient[migrator.StartMigrationRequest, migrator.StartMigrationResponse](
			httpClient,
			baseURL+MigratorStartMigrationProcedure,
			connect.WithSchema(migratorMethods.ByName("StartMigration")),
			connect.WithClientOptions(opts...),
		),
		updateMigration: connect.NewClient[migrator.UpdateMigrationRequest, migrator.UpdateMigrationResponse](
			httpClient,
			baseURL+MigratorUpdateMigrationProcedure,
			connect.WithSchema(migratorMethods.ByName("UpdateMigration")),
			connect.WithClientOptions(opts...),
		),
		getMigrations: connect.NewClient[migrator.GetMigrationsRequest, migrator.GetMigrationsResponse](
			httpClient,
			baseURL+MigratorGetMigrationsProcedure,
			connect.WithSchema(migratorMethods.ByName("GetMigrations")),
			connect.WithClientOptions(opts...),
		),
		setMigrationDirection: connect.NewClient[migrator.SetMigrationDirectionRequest, migrator.SetMigrationDirectionResponse](
			httpClient,
			baseURL+MigratorSetMigrationDirectionProcedure,
			connect.WithSchema(migratorMethods.ByName("SetMigrationDirection")),
			connect.WithClientOptions(opts...),
		),
		dropMigration: connect.NewClient[migrator.DropMigrationRequest, migrator.DropMigrationResponse](
			httpClient,
			baseURL+MigratorDropMigrationProcedure,
			connect.WithSchema(migratorMethods.ByName("DropMigration")),
			connect.WithClientOptions(opts...),
		),
	}
}

// migratorClient implements MigratorClient.
type migratorClient struct {
	createMigration       *connect.Client[migrator.CreateMigrationRequest, migrator.CreateMigrationResponse]
	startMigration        *connect.Client[migrator.StartMigrationRequest, migrator.StartMigrationResponse]
	updateMigration       *connect.Client[migrator.UpdateMigrationRequest, migrator.UpdateMigrationResponse]
	getMigrations         *connect.Client[migrator.GetMigrationsRequest, migrator.GetMigrationsResponse]
	setMigrationDirection *connect.Client[migrator.SetMigrationDirectionRequest, migrator.SetMigrationDirectionResponse]
	dropMigration         *connect.Client[migrator.DropMigrationRequest, migrator.DropMigrationResponse]
}

// CreateMigration calls migrator.Migrator.CreateMigration.
func (c *migratorClient) CreateMigration(ctx context.Context, req *connect.Request[migrator.CreateMigrationRequest]) (*connect.Response[migrator.CreateMigrationResponse], error) {
	return c.createMigration.CallUnary(ctx, req)
}

// StartMigration calls migrator.Migrator.StartMigration.
func (c *migratorClient) StartMigration(ctx context.Context, req *connect.Request[migrator.StartMigrationRequest]) (*connect.Response[migrator.StartMigrationResponse], error) {
	return c.startMigration.CallUnary(ctx, req)
}

// UpdateMigration calls migrator.Migrator.UpdateMigration.
func (c *migratorClient) UpdateMigration(ctx context.Context, req *connect.Request[migrator.UpdateMigrationRequest]) (*connect.Response[migrator.UpdateMigrationResponse], error) {
	return c.updateMigration.CallUnary(ctx, req)
}

// GetMigrations calls migrator.Migrator.GetMigrations.
func (c *migratorClient) GetMigrations(ctx context.Context, req *connect.Request[migrator.GetMigrationsRequest]) (*connect.Response[migrator.GetMigrationsResponse], error) {
	return c.getMigrations.CallUnary(ctx, req)
}

// SetMigrationDirection calls migrator.Migrator.SetMigrationDirection.
func (c *migratorClient) SetMigrationDirection(ctx context.Context, req *connect.Request[migrator.SetMigrationDirectionRequest]) (*connect.Response[migrator.SetMigrationDirectionResponse], error) {
	return c.setMigrationDirection.CallUnary(ctx, req)
}

// DropMigration calls migrator.Migrator.DropMigration.
func (c *migratorClient) DropMigration(ctx context.Context, req *connect.Request[migrator.DropMigrationRequest]) (*connect.Response[migrator.DropMigrationResponse], error) {
	return c.dropMigration.CallUnary(ctx, req)
}

// MigratorHandler is an implementation of the migrator.Migrator service.
type MigratorHandler interface {
	// CreateMigration records a migration's configuration (no database changes).
	CreateMigration(context.Context, *connect.Request[migrator.CreateMigrationRequest]) (*connect.Response[migrator.CreateMigrationResponse], error)
	// StartMigration runs the workflow: validate, schema copy, publication,
	// subscription, and initial catch-up.
	StartMigration(context.Context, *connect.Request[migrator.StartMigrationRequest]) (*connect.Response[migrator.StartMigrationResponse], error)
	// UpdateMigration changes mutable fields (field-masked), notably the source
	// connection.
	UpdateMigration(context.Context, *connect.Request[migrator.UpdateMigrationRequest]) (*connect.Response[migrator.UpdateMigrationResponse], error)
	// GetMigrations returns status for one migration (id set) or all migrations.
	GetMigrations(context.Context, *connect.Request[migrator.GetMigrationsRequest]) (*connect.Response[migrator.GetMigrationsResponse], error)
	// SetMigrationDirection sets the active direction (IMPORT or EXPORT).
	SetMigrationDirection(context.Context, *connect.Request[migrator.SetMigrationDirectionRequest]) (*connect.Response[migrator.SetMigrationDirectionResponse], error)
	// DropMigration tears down the subscription/publication/slot and removes
	// the workflow (default drains first; wait/force modify that).
	DropMigration(context.Context, *connect.Request[migrator.DropMigrationRequest]) (*connect.Response[migrator.DropMigrationResponse], error)
}

// NewMigratorHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewMigratorHandler(svc MigratorHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	migratorMethods := migrator.File_migratorservice_proto.Services().ByName("Migrator").Methods()
	migratorCreateMigrationHandler := connect.NewUnaryHandler(
		MigratorCreateMigrationProcedure,
		svc.CreateMigration,
		connect.WithSchema(migratorMethods.ByName("CreateMigration")),
		connect.WithHandlerOptions(opts...),
	)
	migratorStartMigrationHandler := connect.NewUnaryHandler(
		MigratorStartMigrationProcedure,
		svc.StartMigration,
		connect.WithSchema(migratorMethods.ByName("StartMigration")),
		connect.WithHandlerOptions(opts...),
	)
	migratorUpdateMigrationHandler := connect.NewUnaryHandler(
		MigratorUpdateMigrationProcedure,
		svc.UpdateMigration,
		connect.WithSchema(migratorMethods.ByName("UpdateMigration")),
		connect.WithHandlerOptions(opts...),
	)
	migratorGetMigrationsHandler := connect.NewUnaryHandler(
		MigratorGetMigrationsProcedure,
		svc.GetMigrations,
		connect.WithSchema(migratorMethods.ByName("GetMigrations")),
		connect.WithHandlerOptions(opts...),
	)
	migratorSetMigrationDirectionHandler := connect.NewUnaryHandler(
		MigratorSetMigrationDirectionProcedure,
		svc.SetMigrationDirection,
		connect.WithSchema(migratorMethods.ByName("SetMigrationDirection")),
		connect.WithHandlerOptions(opts...),
	)
	migratorDropMigrationHandler := connect.NewUnaryHandler(
		MigratorDropMigrationProcedure,
		svc.DropMigration,
		connect.WithSchema(migratorMethods.ByName("DropMigration")),
		connect.WithHandlerOptions(opts...),
	)
	return "/migrator.Migrator/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case MigratorCreateMigrationProcedure:
			migratorCreateMigrationHandler.ServeHTTP(w, r)
		case MigratorStartMigrationProcedure:
			migratorStartMigrationHandler.ServeHTTP(w, r)
		case MigratorUpdateMigrationProcedure:
			migratorUpdateMigrationHandler.ServeHTTP(w, r)
		case MigratorGetMigrationsProcedure:
			migratorGetMigrationsHandler.ServeHTTP(w, r)
		case MigratorSetMigrationDirectionProcedure:
			migratorSetMigrationDirectionHandler.ServeHTTP(w, r)
		case MigratorDropMigrationProcedure:
			migratorDropMigrationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedMigratorHandler returns CodeUnimplemented from all methods.
type UnimplementedMigratorHandler struct{}

func (UnimplementedMigratorHandler) CreateMigration(context.Context, *connect.Request[migrator.CreateMigrationRequest]) (*connect.Response[migrator.CreateMigrationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("migrator.Migrator.CreateMigration is not implemented"))
}

func (UnimplementedMigratorHandler) StartMigration(context.Context, *connect.Request[migrator.StartMigrationRequest]) (*connect.Response[migrator.StartMigrationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("migrator.Migrator.StartMigration is not implemented"))
}

func (UnimplementedMigratorHandler) UpdateMigration(context.Context, *connect.Request[migrator.UpdateMigrationRequest]) (*connect.Response[migrator.UpdateMigrationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("migrator.Migrator.UpdateMigration is not implemented"))
}

func (UnimplementedMigratorHandler) GetMigrations(context.Context, *connect.Request[migrator.GetMigrationsRequest]) (*connect.Response[migrator.GetMigrationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("migrator.Migrator.GetMigrations is not implemented"))
}

func (UnimplementedMigratorHandler) SetMigrationDirection(context.Context, *connect.Request[migrator.SetMigrationDirectionRequest]) (*connect.Response[migrator.SetMigrationDirectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("migrator.Migrator.SetMigrationDirection is not implemented"))
}

func (UnimplementedMigratorHandler) DropMigration(context.Context, *connect.Request[migrator.DropMigrationRequest]) (*connect.Response[migrator.DropMigrationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("migrator.Migrator.DropMigration is not implemented"))
}
