// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: migratorservice.proto

package migrator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Migrator_CreateMigration_FullMethodName     = "/migrator.Migrator/CreateMigration"
	Migrator_StartMigration_FullMethodName      = "/migrator.Migrator/StartMigration"
	Migrator_UpdateMigration_FullMethodName     = "/migrator.Migrator/UpdateMigration"
	Migrator_GetMigration_FullMethodName        = "/migrator.Migrator/GetMigration"
	Migrator_ListMigrations_FullMethodName      = "/migrator.Migrator/ListMigrations"
	Migrator_GetMigrationJournal_FullMethodName = "/migrator.Migrator/GetMigrationJournal"
	Migrator_ActivateMigration_FullMethodName   = "/migrator.Migrator/ActivateMigration"
	Migrator_DeactivateMigration_FullMethodName = "/migrator.Migrator/DeactivateMigration"
	Migrator_DropMigration_FullMethodName       = "/migrator.Migrator/DropMigration"
	Migrator_CreateConnection_FullMethodName    = "/migrator.Migrator/CreateConnection"
	Migrator_UpdateConnection_FullMethodName    = "/migrator.Migrator/UpdateConnection"
	Migrator_GetConnection_FullMethodName       = "/migrator.Migrator/GetConnection"
	Migrator_ListConnections_FullMethodName     = "/migrator.Migrator/ListConnections"
	Migrator_DropConnection_FullMethodName      = "/migrator.Migrator/DropConnection"
)

// MigratorClient is the client API for Migrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Migrator coordinates one logical-replication migration per workflow,
// from a standalone source postgres into a multigres target shard.
type MigratorClient interface {
	// CreateMigration records a migration's configuration (no database changes).
	CreateMigration(ctx context.Context, in *CreateMigrationRequest, opts ...grpc.CallOption) (*CreateMigrationResponse, error)
	// StartMigration runs the workflow: validate, schema copy, publication,
	// subscription, and initial catch-up.
	StartMigration(ctx context.Context, in *StartMigrationRequest, opts ...grpc.CallOption) (*StartMigrationResponse, error)
	// UpdateMigration changes mutable fields (field-masked), notably the source
	// connection.
	UpdateMigration(ctx context.Context, in *UpdateMigrationRequest, opts ...grpc.CallOption) (*UpdateMigrationResponse, error)
	// GetMigration returns status for one migration, addressed by ref (id or name).
	GetMigration(ctx context.Context, in *GetMigrationRequest, opts ...grpc.CallOption) (*GetMigrationResponse, error)
	// ListMigrations returns the ids of every migration; fetch full details for
	// each via GetMigration.
	ListMigrations(ctx context.Context, in *ListMigrationsRequest, opts ...grpc.CallOption) (*ListMigrationsResponse, error)
	// GetMigrationJournal returns a migration's append-only audit journal (oldest
	// first). Internal audit surface; entries are retained after a drop, so this
	// returns them even for a migration whose row is gone (addressed by id).
	GetMigrationJournal(ctx context.Context, in *GetMigrationJournalRequest, opts ...grpc.CallOption) (*GetMigrationJournalResponse, error)
	// ActivateMigration cuts over to serving (IMPORT -> EXPORT): drain, flip
	// direction, and start serving. Requires the current direction to be IMPORT.
	ActivateMigration(ctx context.Context, in *ActivateMigrationRequest, opts ...grpc.CallOption) (*ActivateMigrationResponse, error)
	// DeactivateMigration rolls back to non-serving (EXPORT -> IMPORT): stop
	// serving, then flip direction. Requires the current direction to be EXPORT.
	DeactivateMigration(ctx context.Context, in *DeactivateMigrationRequest, opts ...grpc.CallOption) (*DeactivateMigrationResponse, error)
	// DropMigration tears down the subscription/publication/slot and removes
	// the workflow (default drains first; wait/force modify that).
	DropMigration(ctx context.Context, in *DropMigrationRequest, opts ...grpc.CallOption) (*DropMigrationResponse, error)
	// CreateConnection stores a named source conninfo, shard-scoped.
	CreateConnection(ctx context.Context, in *CreateConnectionRequest, opts ...grpc.CallOption) (*CreateConnectionResponse, error)
	// UpdateConnection changes a connection's dsn (field-masked). Takes effect
	// immediately for every migration that references it.
	UpdateConnection(ctx context.Context, in *UpdateConnectionRequest, opts ...grpc.CallOption) (*UpdateConnectionResponse, error)
	// GetConnection returns one connection, addressed by ref (id or name).
	GetConnection(ctx context.Context, in *GetConnectionRequest, opts ...grpc.CallOption) (*GetConnectionResponse, error)
	// ListConnections returns every stored connection in full.
	ListConnections(ctx context.Context, in *ListConnectionsRequest, opts ...grpc.CallOption) (*ListConnectionsResponse, error)
	// DropConnection removes a connection. Fails if a migration still
	// references it.
	DropConnection(ctx context.Context, in *DropConnectionRequest, opts ...grpc.CallOption) (*DropConnectionResponse, error)
}

type migratorClient struct {
	cc grpc.ClientConnInterface
}

func NewMigratorClient(cc grpc.ClientConnInterface) MigratorClient {
	return &migratorClient{cc}
}

func (c *migratorClient) CreateMigration(ctx context.Context, in *CreateMigrationRequest, opts ...grpc.CallOption) (*CreateMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMigrationResponse)
	err := c.cc.Invoke(ctx, Migrator_CreateMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) StartMigration(ctx context.Context, in *StartMigrationRequest, opts ...grpc.CallOption) (*StartMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartMigrationResponse)
	err := c.cc.Invoke(ctx, Migrator_StartMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) UpdateMigration(ctx context.Context, in *UpdateMigrationRequest, opts ...grpc.CallOption) (*UpdateMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMigrationResponse)
	err := c.cc.Invoke(ctx, Migrator_UpdateMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) GetMigration(ctx context.Context, in *GetMigrationRequest, opts ...grpc.CallOption) (*GetMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMigrationResponse)
	err := c.cc.Invoke(ctx, Migrator_GetMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) ListMigrations(ctx context.Context, in *ListMigrationsRequest, opts ...grpc.CallOption) (*ListMigrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMigrationsResponse)
	err := c.cc.Invoke(ctx, Migrator_ListMigrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) GetMigrationJournal(ctx context.Context, in *GetMigrationJournalRequest, opts ...grpc.CallOption) (*GetMigrationJournalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMigrationJournalResponse)
	err := c.cc.Invoke(ctx, Migrator_GetMigrationJournal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) ActivateMigration(ctx context.Context, in *ActivateMigrationRequest, opts ...grpc.CallOption) (*ActivateMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActivateMigrationResponse)
	err := c.cc.Invoke(ctx, Migrator_ActivateMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) DeactivateMigration(ctx context.Context, in *DeactivateMigrationRequest, opts ...grpc.CallOption) (*DeactivateMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeactivateMigrationResponse)
	err := c.cc.Invoke(ctx, Migrator_DeactivateMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) DropMigration(ctx context.Context, in *DropMigrationRequest, opts ...grpc.CallOption) (*DropMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropMigrationResponse)
	err := c.cc.Invoke(ctx, Migrator_DropMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) CreateConnection(ctx context.Context, in *CreateConnectionRequest, opts ...grpc.CallOption) (*CreateConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateConnectionResponse)
	err := c.cc.Invoke(ctx, Migrator_CreateConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) UpdateConnection(ctx context.Context, in *UpdateConnectionRequest, opts ...grpc.CallOption) (*UpdateConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConnectionResponse)
	err := c.cc.Invoke(ctx, Migrator_UpdateConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) GetConnection(ctx context.Context, in *GetConnectionRequest, opts ...grpc.CallOption) (*GetConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConnectionResponse)
	err := c.cc.Invoke(ctx, Migrator_GetConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) ListConnections(ctx context.Context, in *ListConnectionsRequest, opts ...grpc.CallOption) (*ListConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConnectionsResponse)
	err := c.cc.Invoke(ctx, Migrator_ListConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) DropConnection(ctx context.Context, in *DropConnectionRequest, opts ...grpc.CallOption) (*DropConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropConnectionResponse)
	err := c.cc.Invoke(ctx, Migrator_DropConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MigratorServer is the server API for Migrator service.
// All implementations must embed UnimplementedMigratorServer
// for forward compatibility.
//
// Migrator coordinates one logical-replication migration per workflow,
// from a standalone source postgres into a multigres target shard.
type MigratorServer interface {
	// CreateMigration records a migration's configuration (no database changes).
	CreateMigration(context.Context, *CreateMigrationRequest) (*CreateMigrationResponse, error)
	// StartMigration runs the workflow: validate, schema copy, publication,
	// subscription, and initial catch-up.
	StartMigration(context.Context, *StartMigrationRequest) (*StartMigrationResponse, error)
	// UpdateMigration changes mutable fields (field-masked), notably the source
	// connection.
	UpdateMigration(context.Context, *UpdateMigrationRequest) (*UpdateMigrationResponse, error)
	// GetMigration returns status for one migration, addressed by ref (id or name).
	GetMigration(context.Context, *GetMigrationRequest) (*GetMigrationResponse, error)
	// ListMigrations returns the ids of every migration; fetch full details for
	// each via GetMigration.
	ListMigrations(context.Context, *ListMigrationsRequest) (*ListMigrationsResponse, error)
	// GetMigrationJournal returns a migration's append-only audit journal (oldest
	// first). Internal audit surface; entries are retained after a drop, so this
	// returns them even for a migration whose row is gone (addressed by id).
	GetMigrationJournal(context.Context, *GetMigrationJournalRequest) (*GetMigrationJournalResponse, error)
	// ActivateMigration cuts over to serving (IMPORT -> EXPORT): drain, flip
	// direction, and start serving. Requires the current direction to be IMPORT.
	ActivateMigration(context.Context, *ActivateMigrationRequest) (*ActivateMigrationResponse, error)
	// DeactivateMigration rolls back to non-serving (EXPORT -> IMPORT): stop
	// serving, then flip direction. Requires the current direction to be EXPORT.
	DeactivateMigration(context.Context, *DeactivateMigrationRequest) (*DeactivateMigrationResponse, error)
	// DropMigration tears down the subscription/publication/slot and removes
	// the workflow (default drains first; wait/force modify that).
	DropMigration(context.Context, *DropMigrationRequest) (*DropMigrationResponse, error)
	// CreateConnection stores a named source conninfo, shard-scoped.
	CreateConnection(context.Context, *CreateConnectionRequest) (*CreateConnectionResponse, error)
	// UpdateConnection changes a connection's dsn (field-masked). Takes effect
	// immediately for every migration that references it.
	UpdateConnection(context.Context, *UpdateConnectionRequest) (*UpdateConnectionResponse, error)
	// GetConnection returns one connection, addressed by ref (id or name).
	GetConnection(context.Context, *GetConnectionRequest) (*GetConnectionResponse, error)
	// ListConnections returns every stored connection in full.
	ListConnections(context.Context, *ListConnectionsRequest) (*ListConnectionsResponse, error)
	// DropConnection removes a connection. Fails if a migration still
	// references it.
	DropConnection(context.Context, *DropConnectionRequest) (*DropConnectionResponse, error)
	mustEmbedUnimplementedMigratorServer()
}

// UnimplementedMigratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMigratorServer struct{}

func (UnimplementedMigratorServer) CreateMigration(context.Context, *CreateMigrationRequest) (*CreateMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMigration not implemented")
}
func (UnimplementedMigratorServer) StartMigration(context.Context, *StartMigrationRequest) (*StartMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartMigration not implemented")
}
func (UnimplementedMigratorServer) UpdateMigration(context.Context, *UpdateMigrationRequest) (*UpdateMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMigration not implemented")
}
func (UnimplementedMigratorServer) GetMigration(context.Context, *GetMigrationRequest) (*GetMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMigration not implemented")
}
func (UnimplementedMigratorServer) ListMigrations(context.Context, *ListMigrationsRequest) (*ListMigrationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMigrations not implemented")
}
func (UnimplementedMigratorServer) GetMigrationJournal(context.Context, *GetMigrationJournalRequest) (*GetMigrationJournalResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMigrationJournal not implemented")
}
func (UnimplementedMigratorServer) ActivateMigration(context.Context, *ActivateMigrationRequest) (*ActivateMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ActivateMigration not implemented")
}
func (UnimplementedMigratorServer) DeactivateMigration(context.Context, *DeactivateMigrationRequest) (*DeactivateMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeactivateMigration not implemented")
}
func (UnimplementedMigratorServer) DropMigration(context.Context, *DropMigrationRequest) (*DropMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropMigration not implemented")
}
func (UnimplementedMigratorServer) CreateConnection(context.Context, *CreateConnectionRequest) (*CreateConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConnection not implemented")
}
func (UnimplementedMigratorServer) UpdateConnection(context.Context, *UpdateConnectionRequest) (*UpdateConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateConnection not implemented")
}
func (UnimplementedMigratorServer) GetConnection(context.Context, *GetConnectionRequest) (*GetConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConnection not implemented")
}
func (UnimplementedMigratorServer) ListConnections(context.Context, *ListConnectionsRequest) (*ListConnectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConnections not implemented")
}
func (UnimplementedMigratorServer) DropConnection(context.Context, *DropConnectionRequest) (*DropConnectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropConnection not implemented")
}
func (UnimplementedMigratorServer) mustEmbedUnimplementedMigratorServer() {}
func (UnimplementedMigratorServer) testEmbeddedByValue()                  {}

// UnsafeMigratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MigratorServer will
// result in compilation errors.
type UnsafeMigratorServer interface {
	mustEmbedUnimplementedMigratorServer()
}

func RegisterMigratorServer(s grpc.ServiceRegistrar, srv MigratorServer) {
	// If the following call pancis, it indicates UnimplementedMigratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Migrator_ServiceDesc, srv)
}

func _Migrator_CreateMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).CreateMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_CreateMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).CreateMigration(ctx, req.(*CreateMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_StartMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).StartMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_StartMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).StartMigration(ctx, req.(*StartMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_UpdateMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).UpdateMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_UpdateMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).UpdateMigration(ctx, req.(*UpdateMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_GetMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).GetMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_GetMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).GetMigration(ctx, req.(*GetMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_ListMigrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMigrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).ListMigrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_ListMigrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).ListMigrations(ctx, req.(*ListMigrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_GetMigrationJournal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMigrationJournalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).GetMigrationJournal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_GetMigrationJournal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).GetMigrationJournal(ctx, req.(*GetMigrationJournalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_ActivateMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).ActivateMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_ActivateMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).ActivateMigration(ctx, req.(*ActivateMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_DeactivateMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeactivateMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).DeactivateMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_DeactivateMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).DeactivateMigration(ctx, req.(*DeactivateMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_DropMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).DropMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_DropMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).DropMigration(ctx, req.(*DropMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_CreateConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).CreateConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_CreateConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).CreateConnection(ctx, req.(*CreateConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_UpdateConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).UpdateConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_UpdateConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).UpdateConnection(ctx, req.(*UpdateConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_GetConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).GetConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_GetConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).GetConnection(ctx, req.(*GetConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_ListConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).ListConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_ListConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).ListConnections(ctx, req.(*ListConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_DropConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).DropConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_DropConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).DropConnection(ctx, req.(*DropConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Migrator_ServiceDesc is the grpc.ServiceDesc for Migrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Migrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "migrator.Migrator",
	HandlerType: (*MigratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMigration",
			Handler:    _Migrator_CreateMigration_Handler,
		},
		{
			MethodName: "StartMigration",
			Handler:    _Migrator_StartMigration_Handler,
		},
		{
			MethodName: "UpdateMigration",
			Handler:    _Migrator_UpdateMigration_Handler,
		},
		{
			MethodName: "GetMigration",
			Handler:    _Migrator_GetMigration_Handler,
		},
		{
			MethodName: "ListMigrations",
			Handler:    _Migrator_ListMigrations_Handler,
		},
		{
			MethodName: "GetMigrationJournal",
			Handler:    _Migrator_GetMigrationJournal_Handler,
		},
		{
			MethodName: "ActivateMigration",
			Handler:    _Migrator_ActivateMigration_Handler,
		},
		{
			MethodName: "DeactivateMigration",
			Handler:    _Migrator_DeactivateMigration_Handler,
		},
		{
			MethodName: "DropMigration",
			Handler:    _Migrator_DropMigration_Handler,
		},
		{
			MethodName: "CreateConnection",
			Handler:    _Migrator_CreateConnection_Handler,
		},
		{
			MethodName: "UpdateConnection",
			Handler:    _Migrator_UpdateConnection_Handler,
		},
		{
			MethodName: "GetConnection",
			Handler:    _Migrator_GetConnection_Handler,
		},
		{
			MethodName: "ListConnections",
			Handler:    _Migrator_ListConnections_Handler,
		},
		{
			MethodName: "DropConnection",
			Handler:    _Migrator_DropConnection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "migratorservice.proto",
}
