// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: migratorservice.proto

package migrator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Migrator_CreateMigration_FullMethodName       = "/migrator.Migrator/CreateMigration"
	Migrator_StartMigration_FullMethodName        = "/migrator.Migrator/StartMigration"
	Migrator_UpdateMigration_FullMethodName       = "/migrator.Migrator/UpdateMigration"
	Migrator_GetMigrations_FullMethodName         = "/migrator.Migrator/GetMigrations"
	Migrator_SetMigrationDirection_FullMethodName = "/migrator.Migrator/SetMigrationDirection"
	Migrator_DropMigration_FullMethodName         = "/migrator.Migrator/DropMigration"
)

// MigratorClient is the client API for Migrator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Migrator coordinates one logical-replication migration per workflow,
// from a standalone source postgres into a multigres target shard.
type MigratorClient interface {
	// CreateMigration records a migration's configuration (no database changes).
	CreateMigration(ctx context.Context, in *CreateMigrationRequest, opts ...grpc.CallOption) (*CreateMigrationResponse, error)
	// StartMigration runs the workflow: validate, schema copy, publication,
	// subscription, and initial catch-up.
	StartMigration(ctx context.Context, in *StartMigrationRequest, opts ...grpc.CallOption) (*StartMigrationResponse, error)
	// UpdateMigration changes mutable fields (field-masked), notably the source
	// connection.
	UpdateMigration(ctx context.Context, in *UpdateMigrationRequest, opts ...grpc.CallOption) (*UpdateMigrationResponse, error)
	// GetMigrations returns status for one migration (id set) or all migrations.
	GetMigrations(ctx context.Context, in *GetMigrationsRequest, opts ...grpc.CallOption) (*GetMigrationsResponse, error)
	// SetMigrationDirection sets the active direction (IMPORT or EXPORT).
	SetMigrationDirection(ctx context.Context, in *SetMigrationDirectionRequest, opts ...grpc.CallOption) (*SetMigrationDirectionResponse, error)
	// DropMigration tears down the subscription/publication/slot and removes
	// the workflow (default drains first; wait/force modify that).
	DropMigration(ctx context.Context, in *DropMigrationRequest, opts ...grpc.CallOption) (*DropMigrationResponse, error)
}

type migratorClient struct {
	cc grpc.ClientConnInterface
}

func NewMigratorClient(cc grpc.ClientConnInterface) MigratorClient {
	return &migratorClient{cc}
}

func (c *migratorClient) CreateMigration(ctx context.Context, in *CreateMigrationRequest, opts ...grpc.CallOption) (*CreateMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMigrationResponse)
	err := c.cc.Invoke(ctx, Migrator_CreateMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) StartMigration(ctx context.Context, in *StartMigrationRequest, opts ...grpc.CallOption) (*StartMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartMigrationResponse)
	err := c.cc.Invoke(ctx, Migrator_StartMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) UpdateMigration(ctx context.Context, in *UpdateMigrationRequest, opts ...grpc.CallOption) (*UpdateMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMigrationResponse)
	err := c.cc.Invoke(ctx, Migrator_UpdateMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) GetMigrations(ctx context.Context, in *GetMigrationsRequest, opts ...grpc.CallOption) (*GetMigrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMigrationsResponse)
	err := c.cc.Invoke(ctx, Migrator_GetMigrations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) SetMigrationDirection(ctx context.Context, in *SetMigrationDirectionRequest, opts ...grpc.CallOption) (*SetMigrationDirectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMigrationDirectionResponse)
	err := c.cc.Invoke(ctx, Migrator_SetMigrationDirection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *migratorClient) DropMigration(ctx context.Context, in *DropMigrationRequest, opts ...grpc.CallOption) (*DropMigrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropMigrationResponse)
	err := c.cc.Invoke(ctx, Migrator_DropMigration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MigratorServer is the server API for Migrator service.
// All implementations must embed UnimplementedMigratorServer
// for forward compatibility.
//
// Migrator coordinates one logical-replication migration per workflow,
// from a standalone source postgres into a multigres target shard.
type MigratorServer interface {
	// CreateMigration records a migration's configuration (no database changes).
	CreateMigration(context.Context, *CreateMigrationRequest) (*CreateMigrationResponse, error)
	// StartMigration runs the workflow: validate, schema copy, publication,
	// subscription, and initial catch-up.
	StartMigration(context.Context, *StartMigrationRequest) (*StartMigrationResponse, error)
	// UpdateMigration changes mutable fields (field-masked), notably the source
	// connection.
	UpdateMigration(context.Context, *UpdateMigrationRequest) (*UpdateMigrationResponse, error)
	// GetMigrations returns status for one migration (id set) or all migrations.
	GetMigrations(context.Context, *GetMigrationsRequest) (*GetMigrationsResponse, error)
	// SetMigrationDirection sets the active direction (IMPORT or EXPORT).
	SetMigrationDirection(context.Context, *SetMigrationDirectionRequest) (*SetMigrationDirectionResponse, error)
	// DropMigration tears down the subscription/publication/slot and removes
	// the workflow (default drains first; wait/force modify that).
	DropMigration(context.Context, *DropMigrationRequest) (*DropMigrationResponse, error)
	mustEmbedUnimplementedMigratorServer()
}

// UnimplementedMigratorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMigratorServer struct{}

func (UnimplementedMigratorServer) CreateMigration(context.Context, *CreateMigrationRequest) (*CreateMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMigration not implemented")
}
func (UnimplementedMigratorServer) StartMigration(context.Context, *StartMigrationRequest) (*StartMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartMigration not implemented")
}
func (UnimplementedMigratorServer) UpdateMigration(context.Context, *UpdateMigrationRequest) (*UpdateMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMigration not implemented")
}
func (UnimplementedMigratorServer) GetMigrations(context.Context, *GetMigrationsRequest) (*GetMigrationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMigrations not implemented")
}
func (UnimplementedMigratorServer) SetMigrationDirection(context.Context, *SetMigrationDirectionRequest) (*SetMigrationDirectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMigrationDirection not implemented")
}
func (UnimplementedMigratorServer) DropMigration(context.Context, *DropMigrationRequest) (*DropMigrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropMigration not implemented")
}
func (UnimplementedMigratorServer) mustEmbedUnimplementedMigratorServer() {}
func (UnimplementedMigratorServer) testEmbeddedByValue()                  {}

// UnsafeMigratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MigratorServer will
// result in compilation errors.
type UnsafeMigratorServer interface {
	mustEmbedUnimplementedMigratorServer()
}

func RegisterMigratorServer(s grpc.ServiceRegistrar, srv MigratorServer) {
	// If the following call pancis, it indicates UnimplementedMigratorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Migrator_ServiceDesc, srv)
}

func _Migrator_CreateMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).CreateMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_CreateMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).CreateMigration(ctx, req.(*CreateMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_StartMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).StartMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_StartMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).StartMigration(ctx, req.(*StartMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_UpdateMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).UpdateMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_UpdateMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).UpdateMigration(ctx, req.(*UpdateMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_GetMigrations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMigrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).GetMigrations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_GetMigrations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).GetMigrations(ctx, req.(*GetMigrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_SetMigrationDirection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMigrationDirectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).SetMigrationDirection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_SetMigrationDirection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).SetMigrationDirection(ctx, req.(*SetMigrationDirectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Migrator_DropMigration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropMigrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MigratorServer).DropMigration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Migrator_DropMigration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MigratorServer).DropMigration(ctx, req.(*DropMigrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Migrator_ServiceDesc is the grpc.ServiceDesc for Migrator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Migrator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "migrator.Migrator",
	HandlerType: (*MigratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMigration",
			Handler:    _Migrator_CreateMigration_Handler,
		},
		{
			MethodName: "StartMigration",
			Handler:    _Migrator_StartMigration_Handler,
		},
		{
			MethodName: "UpdateMigration",
			Handler:    _Migrator_UpdateMigration_Handler,
		},
		{
			MethodName: "GetMigrations",
			Handler:    _Migrator_GetMigrations_Handler,
		},
		{
			MethodName: "SetMigrationDirection",
			Handler:    _Migrator_SetMigrationDirection_Handler,
		},
		{
			MethodName: "DropMigration",
			Handler:    _Migrator_DropMigration_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "migratorservice.proto",
}
