// Copyright 2025 The Multigres Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: multiadminservice.proto

package multiadmin

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MultiAdminService_GetCell_FullMethodName     = "/multiadmin.MultiAdminService/GetCell"
	MultiAdminService_GetDatabase_FullMethodName = "/multiadmin.MultiAdminService/GetDatabase"
)

// MultiAdminServiceClient is the client API for MultiAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MultiAdminService provides administrative gRPC APIs for querying cluster metadata
type MultiAdminServiceClient interface {
	// GetCell retrieves information about a specific cell
	GetCell(ctx context.Context, in *GetCellRequest, opts ...grpc.CallOption) (*GetCellResponse, error)
	// GetDatabase retrieves information about a specific database
	GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseResponse, error)
}

type multiAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiAdminServiceClient(cc grpc.ClientConnInterface) MultiAdminServiceClient {
	return &multiAdminServiceClient{cc}
}

func (c *multiAdminServiceClient) GetCell(ctx context.Context, in *GetCellRequest, opts ...grpc.CallOption) (*GetCellResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCellResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_GetCell_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiAdminServiceClient) GetDatabase(ctx context.Context, in *GetDatabaseRequest, opts ...grpc.CallOption) (*GetDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDatabaseResponse)
	err := c.cc.Invoke(ctx, MultiAdminService_GetDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MultiAdminServiceServer is the server API for MultiAdminService service.
// All implementations must embed UnimplementedMultiAdminServiceServer
// for forward compatibility.
//
// MultiAdminService provides administrative gRPC APIs for querying cluster metadata
type MultiAdminServiceServer interface {
	// GetCell retrieves information about a specific cell
	GetCell(context.Context, *GetCellRequest) (*GetCellResponse, error)
	// GetDatabase retrieves information about a specific database
	GetDatabase(context.Context, *GetDatabaseRequest) (*GetDatabaseResponse, error)
	mustEmbedUnimplementedMultiAdminServiceServer()
}

// UnimplementedMultiAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultiAdminServiceServer struct{}

func (UnimplementedMultiAdminServiceServer) GetCell(context.Context, *GetCellRequest) (*GetCellResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCell not implemented")
}
func (UnimplementedMultiAdminServiceServer) GetDatabase(context.Context, *GetDatabaseRequest) (*GetDatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatabase not implemented")
}
func (UnimplementedMultiAdminServiceServer) mustEmbedUnimplementedMultiAdminServiceServer() {}
func (UnimplementedMultiAdminServiceServer) testEmbeddedByValue()                           {}

// UnsafeMultiAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiAdminServiceServer will
// result in compilation errors.
type UnsafeMultiAdminServiceServer interface {
	mustEmbedUnimplementedMultiAdminServiceServer()
}

func RegisterMultiAdminServiceServer(s grpc.ServiceRegistrar, srv MultiAdminServiceServer) {
	// If the following call pancis, it indicates UnimplementedMultiAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MultiAdminService_ServiceDesc, srv)
}

func _MultiAdminService_GetCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).GetCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_GetCell_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).GetCell(ctx, req.(*GetCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiAdminService_GetDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiAdminServiceServer).GetDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiAdminService_GetDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiAdminServiceServer).GetDatabase(ctx, req.(*GetDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MultiAdminService_ServiceDesc is the grpc.ServiceDesc for MultiAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultiAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "multiadmin.MultiAdminService",
	HandlerType: (*MultiAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCell",
			Handler:    _MultiAdminService_GetCell_Handler,
		},
		{
			MethodName: "GetDatabase",
			Handler:    _MultiAdminService_GetDatabase_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "multiadminservice.proto",
}
