//
//Copyright 2025 Supabase, Inc.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// This file contains data structures for query results in Multigres.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: query.proto

package query

import (
	clustermetadata "github.com/multigres/multigres/go/pb/clustermetadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryResult represents the result of executing a query
type QueryResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// fields describes the columns in the result set (nil if no rows returned)
	Fields []*Field `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	// rows_affected is the number of rows affected (INSERT, UPDATE, DELETE, etc.)
	RowsAffected uint64 `protobuf:"varint,2,opt,name=rows_affected,json=rowsAffected,proto3" json:"rows_affected,omitempty"`
	// rows contains the actual data rows
	Rows []*Row `protobuf:"bytes,3,rep,name=rows,proto3" json:"rows,omitempty"`
	// command_tag is the PostgreSQL command tag for this result set.
	// When streaming results, this should only be set on the final packet of a result set.
	// When set, the protocol layer will send CommandComplete and reset state for the next result set.
	// Examples: "SELECT 42", "INSERT 0 5", "UPDATE 10", "DELETE 3", "CREATE TABLE"
	CommandTag string `protobuf:"bytes,4,opt,name=command_tag,json=commandTag,proto3" json:"command_tag,omitempty"`
	// notices contains any PostgreSQL diagnostic messages received during query execution.
	// These are typically non-fatal messages like warnings or informational notices,
	// but may also include error diagnostics for logging/auditing purposes.
	// The message_type field ('E' or 'N') indicates whether each is an error or notice.
	Notices       []*PgDiagnostic `protobuf:"bytes,5,rep,name=notices,proto3" json:"notices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryResult) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *QueryResult) GetRowsAffected() uint64 {
	if x != nil {
		return x.RowsAffected
	}
	return 0
}

func (x *QueryResult) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *QueryResult) GetCommandTag() string {
	if x != nil {
		return x.CommandTag
	}
	return ""
}

func (x *QueryResult) GetNotices() []*PgDiagnostic {
	if x != nil {
		return x.Notices
	}
	return nil
}

// Field represents metadata about a column in the result set.
// This includes all PostgreSQL wire protocol metadata needed for RowDescription messages.
type Field struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the column name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// type is a human-readable type name (for logging/debugging)
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// table_oid is the object ID of the table (0 if not a table column)
	TableOid uint32 `protobuf:"varint,3,opt,name=table_oid,json=tableOid,proto3" json:"table_oid,omitempty"`
	// table_attribute_number is the column number in the table (0 if not a table column)
	TableAttributeNumber int32 `protobuf:"varint,4,opt,name=table_attribute_number,json=tableAttributeNumber,proto3" json:"table_attribute_number,omitempty"`
	// data_type_oid is the object ID of the data type
	DataTypeOid uint32 `protobuf:"varint,5,opt,name=data_type_oid,json=dataTypeOid,proto3" json:"data_type_oid,omitempty"`
	// data_type_size is the size of the data type (-1 for variable length)
	DataTypeSize int32 `protobuf:"varint,6,opt,name=data_type_size,json=dataTypeSize,proto3" json:"data_type_size,omitempty"`
	// type_modifier is the type modifier (-1 for no modifier)
	TypeModifier int32 `protobuf:"varint,7,opt,name=type_modifier,json=typeModifier,proto3" json:"type_modifier,omitempty"`
	// format is the format code (0=text, 1=binary)
	Format        int32 `protobuf:"varint,8,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Field) Reset() {
	*x = Field{}
	mi := &file_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{1}
}

func (x *Field) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Field) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Field) GetTableOid() uint32 {
	if x != nil {
		return x.TableOid
	}
	return 0
}

func (x *Field) GetTableAttributeNumber() int32 {
	if x != nil {
		return x.TableAttributeNumber
	}
	return 0
}

func (x *Field) GetDataTypeOid() uint32 {
	if x != nil {
		return x.DataTypeOid
	}
	return 0
}

func (x *Field) GetDataTypeSize() int32 {
	if x != nil {
		return x.DataTypeSize
	}
	return 0
}

func (x *Field) GetTypeModifier() int32 {
	if x != nil {
		return x.TypeModifier
	}
	return 0
}

func (x *Field) GetFormat() int32 {
	if x != nil {
		return x.Format
	}
	return 0
}

// Row represents a single row of data in the result set.
type Row struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// lengths contains the length of each column value.
	// -1 means NULL, 0 means empty string, >0 means actual length.
	Lengths []int64 `protobuf:"zigzag64,1,rep,packed,name=lengths,proto3" json:"lengths,omitempty"`
	// values contains all non-null values concatenated together.
	// Use lengths to split this into individual column values.
	Values        []byte `protobuf:"bytes,2,opt,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{2}
}

func (x *Row) GetLengths() []int64 {
	if x != nil {
		return x.Lengths
	}
	return nil
}

func (x *Row) GetValues() []byte {
	if x != nil {
		return x.Values
	}
	return nil
}

// PgDiagnostic represents a PostgreSQL diagnostic message (error or notice).
// PostgreSQL uses the same wire format for both ErrorResponse ('E') and NoticeResponse ('N'),
// differentiated by the message_type field. This unified structure captures all 14 fields
// defined in the PostgreSQL protocol for diagnostic messages.
//
// Error severities: ERROR, FATAL, PANIC
// Notice severities: WARNING, NOTICE, DEBUG, INFO, LOG
//
// Reference: https://www.postgresql.org/docs/current/protocol-error-fields.html
type PgDiagnostic struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_type is the PostgreSQL protocol message type byte.
	// 'E' (0x45 = 69) for ErrorResponse, 'N' (0x4E = 78) for NoticeResponse.
	// This determines whether the diagnostic is an error or notice.
	MessageType int32 `protobuf:"varint,15,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	// severity is the severity level (e.g., "ERROR", "FATAL", "WARNING", "NOTICE", "INFO")
	Severity string `protobuf:"bytes,1,opt,name=severity,proto3" json:"severity,omitempty"`
	// code is the SQLSTATE error code (e.g., "42P01", "22P02")
	Code string `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	// message is the primary human-readable diagnostic message
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	// detail provides additional detail about the diagnostic (optional)
	Detail string `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	// hint provides a hint about how to address the issue (optional)
	Hint string `protobuf:"bytes,5,opt,name=hint,proto3" json:"hint,omitempty"`
	// position is the cursor position in the original query string (1-indexed, 0 if not available)
	Position int32 `protobuf:"varint,6,opt,name=position,proto3" json:"position,omitempty"`
	// internal_position is the cursor position in the internal query (1-indexed, 0 if not available)
	InternalPosition int32 `protobuf:"varint,7,opt,name=internal_position,json=internalPosition,proto3" json:"internal_position,omitempty"`
	// internal_query is the text of the internally-generated query (optional)
	InternalQuery string `protobuf:"bytes,8,opt,name=internal_query,json=internalQuery,proto3" json:"internal_query,omitempty"`
	// where is the context in which the diagnostic occurred, e.g., PL/pgSQL call stack (optional)
	Where string `protobuf:"bytes,9,opt,name=where,proto3" json:"where,omitempty"`
	// schema_name is the name of the schema associated with the diagnostic (optional)
	SchemaName string `protobuf:"bytes,10,opt,name=schema_name,json=schemaName,proto3" json:"schema_name,omitempty"`
	// table_name is the name of the table associated with the diagnostic (optional)
	TableName string `protobuf:"bytes,11,opt,name=table_name,json=tableName,proto3" json:"table_name,omitempty"`
	// column_name is the name of the column associated with the diagnostic (optional)
	ColumnName string `protobuf:"bytes,12,opt,name=column_name,json=columnName,proto3" json:"column_name,omitempty"`
	// data_type_name is the name of the data type associated with the diagnostic (optional)
	DataTypeName string `protobuf:"bytes,13,opt,name=data_type_name,json=dataTypeName,proto3" json:"data_type_name,omitempty"`
	// constraint_name is the name of the constraint associated with the diagnostic (optional)
	ConstraintName string `protobuf:"bytes,14,opt,name=constraint_name,json=constraintName,proto3" json:"constraint_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PgDiagnostic) Reset() {
	*x = PgDiagnostic{}
	mi := &file_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PgDiagnostic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PgDiagnostic) ProtoMessage() {}

func (x *PgDiagnostic) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PgDiagnostic.ProtoReflect.Descriptor instead.
func (*PgDiagnostic) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{3}
}

func (x *PgDiagnostic) GetMessageType() int32 {
	if x != nil {
		return x.MessageType
	}
	return 0
}

func (x *PgDiagnostic) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *PgDiagnostic) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *PgDiagnostic) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PgDiagnostic) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *PgDiagnostic) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

func (x *PgDiagnostic) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *PgDiagnostic) GetInternalPosition() int32 {
	if x != nil {
		return x.InternalPosition
	}
	return 0
}

func (x *PgDiagnostic) GetInternalQuery() string {
	if x != nil {
		return x.InternalQuery
	}
	return ""
}

func (x *PgDiagnostic) GetWhere() string {
	if x != nil {
		return x.Where
	}
	return ""
}

func (x *PgDiagnostic) GetSchemaName() string {
	if x != nil {
		return x.SchemaName
	}
	return ""
}

func (x *PgDiagnostic) GetTableName() string {
	if x != nil {
		return x.TableName
	}
	return ""
}

func (x *PgDiagnostic) GetColumnName() string {
	if x != nil {
		return x.ColumnName
	}
	return ""
}

func (x *PgDiagnostic) GetDataTypeName() string {
	if x != nil {
		return x.DataTypeName
	}
	return ""
}

func (x *PgDiagnostic) GetConstraintName() string {
	if x != nil {
		return x.ConstraintName
	}
	return ""
}

// StatementDescription describes a prepared statement or portal.
// Used for the Describe message ('D') response in the extended query protocol.
type StatementDescription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// parameters describes the parameters of the statement (for statement describe)
	// Nil for portal describe.
	Parameters []*ParameterDescription `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
	// fields describes the result columns
	// Nil if the statement doesn't return rows.
	Fields        []*Field `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatementDescription) Reset() {
	*x = StatementDescription{}
	mi := &file_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatementDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatementDescription) ProtoMessage() {}

func (x *StatementDescription) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatementDescription.ProtoReflect.Descriptor instead.
func (*StatementDescription) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{4}
}

func (x *StatementDescription) GetParameters() []*ParameterDescription {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *StatementDescription) GetFields() []*Field {
	if x != nil {
		return x.Fields
	}
	return nil
}

// ParameterDescription describes a parameter in a prepared statement.
type ParameterDescription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data_type_oid is the OID of the parameter's data type
	DataTypeOid   uint32 `protobuf:"varint,1,opt,name=data_type_oid,json=dataTypeOid,proto3" json:"data_type_oid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterDescription) Reset() {
	*x = ParameterDescription{}
	mi := &file_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterDescription) ProtoMessage() {}

func (x *ParameterDescription) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterDescription.ProtoReflect.Descriptor instead.
func (*ParameterDescription) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{5}
}

func (x *ParameterDescription) GetDataTypeOid() uint32 {
	if x != nil {
		return x.DataTypeOid
	}
	return 0
}

// Target identifies the target for query execution.
// It specifies which tablegroup, shard, and pooler type to route the query to.
// - Route to PRIMARY for writes
// - Route to REPLICA for reads
// - Route to specific shards (future)
type Target struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// table_group is the target tablegroup name
	TableGroup string `protobuf:"bytes,1,opt,name=table_group,json=tableGroup,proto3" json:"table_group,omitempty"`
	// shard is the target shard name (empty for unsharded or to route to any shard)
	Shard string `protobuf:"bytes,2,opt,name=shard,proto3" json:"shard,omitempty"`
	// pooler_type is the type of pooler to route to (PRIMARY, REPLICA)
	// If not specified (UNKNOWN), defaults to PRIMARY
	PoolerType    clustermetadata.PoolerType `protobuf:"varint,3,opt,name=pooler_type,json=poolerType,proto3,enum=clustermetadata.PoolerType" json:"pooler_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{6}
}

func (x *Target) GetTableGroup() string {
	if x != nil {
		return x.TableGroup
	}
	return ""
}

func (x *Target) GetShard() string {
	if x != nil {
		return x.Shard
	}
	return ""
}

func (x *Target) GetPoolerType() clustermetadata.PoolerType {
	if x != nil {
		return x.PoolerType
	}
	return clustermetadata.PoolerType(0)
}

// PreparedStatement represents a prepared statement in the extended query protocol.
// Prepared statements are created by the Parse message and can be executed
// multiple times with different parameter values.
type PreparedStatement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the client-provided name for the prepared statement.
	// An empty name indicates the unnamed statement.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// query is the SQL query string.
	Query string `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	// param_types contains the OIDs of the parameter types.
	// This is sent by the client in the Parse message.
	ParamTypes    []uint32 `protobuf:"varint,3,rep,packed,name=param_types,json=paramTypes,proto3" json:"param_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreparedStatement) Reset() {
	*x = PreparedStatement{}
	mi := &file_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreparedStatement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreparedStatement) ProtoMessage() {}

func (x *PreparedStatement) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreparedStatement.ProtoReflect.Descriptor instead.
func (*PreparedStatement) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{7}
}

func (x *PreparedStatement) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PreparedStatement) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *PreparedStatement) GetParamTypes() []uint32 {
	if x != nil {
		return x.ParamTypes
	}
	return nil
}

// Portal represents a bound prepared statement with parameters.
// Portals are created by the Bind message and can be executed via Execute.
type Portal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the client-provided name for the portal.
	// An empty name indicates the unnamed portal.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// prepared_statement_name is the name of the prepared statement this portal is bound to.
	PreparedStatementName string `protobuf:"bytes,2,opt,name=prepared_statement_name,json=preparedStatementName,proto3" json:"prepared_statement_name,omitempty"`
	// param_lengths contains the length of each parameter value.
	// -1 means NULL, 0 means empty string, >0 means actual length.
	ParamLengths []int64 `protobuf:"zigzag64,3,rep,packed,name=param_lengths,json=paramLengths,proto3" json:"param_lengths,omitempty"`
	// param_values contains all non-null parameter values concatenated together.
	// Use param_lengths to split this into individual parameter values.
	ParamValues []byte `protobuf:"bytes,4,opt,name=param_values,json=paramValues,proto3" json:"param_values,omitempty"`
	// param_formats specifies the format code for each parameter.
	// 0 = text, 1 = binary.
	// If empty, all parameters are text format.
	// If a single element, that format applies to all parameters.
	ParamFormats []int32 `protobuf:"varint,5,rep,packed,name=param_formats,json=paramFormats,proto3" json:"param_formats,omitempty"`
	// result_formats specifies the format code for each result column.
	// 0 = text, 1 = binary.
	// If empty, all results are text format.
	// If a single element, that format applies to all result columns.
	ResultFormats []int32 `protobuf:"varint,6,rep,packed,name=result_formats,json=resultFormats,proto3" json:"result_formats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Portal) Reset() {
	*x = Portal{}
	mi := &file_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Portal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Portal) ProtoMessage() {}

func (x *Portal) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Portal.ProtoReflect.Descriptor instead.
func (*Portal) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{8}
}

func (x *Portal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Portal) GetPreparedStatementName() string {
	if x != nil {
		return x.PreparedStatementName
	}
	return ""
}

func (x *Portal) GetParamLengths() []int64 {
	if x != nil {
		return x.ParamLengths
	}
	return nil
}

func (x *Portal) GetParamValues() []byte {
	if x != nil {
		return x.ParamValues
	}
	return nil
}

func (x *Portal) GetParamFormats() []int32 {
	if x != nil {
		return x.ParamFormats
	}
	return nil
}

func (x *Portal) GetResultFormats() []int32 {
	if x != nil {
		return x.ResultFormats
	}
	return nil
}

// ExecuteOptions contains execution options for query execution.
// This includes session state like prepared statements and portals that
// need to be available on the connection where the query is executed.
type ExecuteOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session_settings contains session variables (SET commands) that should
	// be applied to the connection before executing the query.
	// Key is the variable name, value is the variable value.
	SessionSettings map[string]string `protobuf:"bytes,1,rep,name=session_settings,json=sessionSettings,proto3" json:"session_settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// user is the PostgreSQL user/role identity for query execution.
	// This determines which per-user connection pool to use.
	// Required for per-user pool routing in the multipooler.
	User string `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	// max_rows is the maximum number of rows to return from Execute.
	// 0 means return all rows. Used by the Execute message in the extended query protocol.
	MaxRows uint64 `protobuf:"varint,4,opt,name=max_rows,json=maxRows,proto3" json:"max_rows,omitempty"`
	// reserved_connection_id is the ID of a reserved connection on the multipooler.
	// Used for connection pinning - this tells the multipooler which specific
	// connection to use for executing this query.
	ReservedConnectionId uint64 `protobuf:"varint,5,opt,name=reserved_connection_id,json=reservedConnectionId,proto3" json:"reserved_connection_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ExecuteOptions) Reset() {
	*x = ExecuteOptions{}
	mi := &file_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteOptions) ProtoMessage() {}

func (x *ExecuteOptions) ProtoReflect() protoreflect.Message {
	mi := &file_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteOptions.ProtoReflect.Descriptor instead.
func (*ExecuteOptions) Descriptor() ([]byte, []int) {
	return file_query_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteOptions) GetSessionSettings() map[string]string {
	if x != nil {
		return x.SessionSettings
	}
	return nil
}

func (x *ExecuteOptions) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *ExecuteOptions) GetMaxRows() uint64 {
	if x != nil {
		return x.MaxRows
	}
	return 0
}

func (x *ExecuteOptions) GetReservedConnectionId() uint64 {
	if x != nil {
		return x.ReservedConnectionId
	}
	return 0
}

var File_query_proto protoreflect.FileDescriptor

const file_query_proto_rawDesc = "" +
	"\n" +
	"\vquery.proto\x12\x05query\x1a\x15clustermetadata.proto\"\xc8\x01\n" +
	"\vQueryResult\x12$\n" +
	"\x06fields\x18\x01 \x03(\v2\f.query.FieldR\x06fields\x12#\n" +
	"\rrows_affected\x18\x02 \x01(\x04R\frowsAffected\x12\x1e\n" +
	"\x04rows\x18\x03 \x03(\v2\n" +
	".query.RowR\x04rows\x12\x1f\n" +
	"\vcommand_tag\x18\x04 \x01(\tR\n" +
	"commandTag\x12-\n" +
	"\anotices\x18\x05 \x03(\v2\x13.query.PgDiagnosticR\anotices\"\x89\x02\n" +
	"\x05Field\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1b\n" +
	"\ttable_oid\x18\x03 \x01(\rR\btableOid\x124\n" +
	"\x16table_attribute_number\x18\x04 \x01(\x05R\x14tableAttributeNumber\x12\"\n" +
	"\rdata_type_oid\x18\x05 \x01(\rR\vdataTypeOid\x12$\n" +
	"\x0edata_type_size\x18\x06 \x01(\x05R\fdataTypeSize\x12#\n" +
	"\rtype_modifier\x18\a \x01(\x05R\ftypeModifier\x12\x16\n" +
	"\x06format\x18\b \x01(\x05R\x06format\"7\n" +
	"\x03Row\x12\x18\n" +
	"\alengths\x18\x01 \x03(\x12R\alengths\x12\x16\n" +
	"\x06values\x18\x02 \x01(\fR\x06values\"\xdd\x03\n" +
	"\fPgDiagnostic\x12!\n" +
	"\fmessage_type\x18\x0f \x01(\x05R\vmessageType\x12\x1a\n" +
	"\bseverity\x18\x01 \x01(\tR\bseverity\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x12\n" +
	"\x04hint\x18\x05 \x01(\tR\x04hint\x12\x1a\n" +
	"\bposition\x18\x06 \x01(\x05R\bposition\x12+\n" +
	"\x11internal_position\x18\a \x01(\x05R\x10internalPosition\x12%\n" +
	"\x0einternal_query\x18\b \x01(\tR\rinternalQuery\x12\x14\n" +
	"\x05where\x18\t \x01(\tR\x05where\x12\x1f\n" +
	"\vschema_name\x18\n" +
	" \x01(\tR\n" +
	"schemaName\x12\x1d\n" +
	"\n" +
	"table_name\x18\v \x01(\tR\ttableName\x12\x1f\n" +
	"\vcolumn_name\x18\f \x01(\tR\n" +
	"columnName\x12$\n" +
	"\x0edata_type_name\x18\r \x01(\tR\fdataTypeName\x12'\n" +
	"\x0fconstraint_name\x18\x0e \x01(\tR\x0econstraintName\"y\n" +
	"\x14StatementDescription\x12;\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2\x1b.query.ParameterDescriptionR\n" +
	"parameters\x12$\n" +
	"\x06fields\x18\x02 \x03(\v2\f.query.FieldR\x06fields\":\n" +
	"\x14ParameterDescription\x12\"\n" +
	"\rdata_type_oid\x18\x01 \x01(\rR\vdataTypeOid\"}\n" +
	"\x06Target\x12\x1f\n" +
	"\vtable_group\x18\x01 \x01(\tR\n" +
	"tableGroup\x12\x14\n" +
	"\x05shard\x18\x02 \x01(\tR\x05shard\x12<\n" +
	"\vpooler_type\x18\x03 \x01(\x0e2\x1b.clustermetadata.PoolerTypeR\n" +
	"poolerType\"^\n" +
	"\x11PreparedStatement\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x1f\n" +
	"\vparam_types\x18\x03 \x03(\rR\n" +
	"paramTypes\"\xe8\x01\n" +
	"\x06Portal\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x126\n" +
	"\x17prepared_statement_name\x18\x02 \x01(\tR\x15preparedStatementName\x12#\n" +
	"\rparam_lengths\x18\x03 \x03(\x12R\fparamLengths\x12!\n" +
	"\fparam_values\x18\x04 \x01(\fR\vparamValues\x12#\n" +
	"\rparam_formats\x18\x05 \x03(\x05R\fparamFormats\x12%\n" +
	"\x0eresult_formats\x18\x06 \x03(\x05R\rresultFormats\"\x90\x02\n" +
	"\x0eExecuteOptions\x12U\n" +
	"\x10session_settings\x18\x01 \x03(\v2*.query.ExecuteOptions.SessionSettingsEntryR\x0fsessionSettings\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x12\x19\n" +
	"\bmax_rows\x18\x04 \x01(\x04R\amaxRows\x124\n" +
	"\x16reserved_connection_id\x18\x05 \x01(\x04R\x14reservedConnectionId\x1aB\n" +
	"\x14SessionSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B,Z*github.com/multigres/multigres/go/pb/queryb\x06proto3"

var (
	file_query_proto_rawDescOnce sync.Once
	file_query_proto_rawDescData []byte
)

func file_query_proto_rawDescGZIP() []byte {
	file_query_proto_rawDescOnce.Do(func() {
		file_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)))
	})
	return file_query_proto_rawDescData
}

var file_query_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_query_proto_goTypes = []any{
	(*QueryResult)(nil),             // 0: query.QueryResult
	(*Field)(nil),                   // 1: query.Field
	(*Row)(nil),                     // 2: query.Row
	(*PgDiagnostic)(nil),            // 3: query.PgDiagnostic
	(*StatementDescription)(nil),    // 4: query.StatementDescription
	(*ParameterDescription)(nil),    // 5: query.ParameterDescription
	(*Target)(nil),                  // 6: query.Target
	(*PreparedStatement)(nil),       // 7: query.PreparedStatement
	(*Portal)(nil),                  // 8: query.Portal
	(*ExecuteOptions)(nil),          // 9: query.ExecuteOptions
	nil,                             // 10: query.ExecuteOptions.SessionSettingsEntry
	(clustermetadata.PoolerType)(0), // 11: clustermetadata.PoolerType
}
var file_query_proto_depIdxs = []int32{
	1,  // 0: query.QueryResult.fields:type_name -> query.Field
	2,  // 1: query.QueryResult.rows:type_name -> query.Row
	3,  // 2: query.QueryResult.notices:type_name -> query.PgDiagnostic
	5,  // 3: query.StatementDescription.parameters:type_name -> query.ParameterDescription
	1,  // 4: query.StatementDescription.fields:type_name -> query.Field
	11, // 5: query.Target.pooler_type:type_name -> clustermetadata.PoolerType
	10, // 6: query.ExecuteOptions.session_settings:type_name -> query.ExecuteOptions.SessionSettingsEntry
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_query_proto_init() }
func file_query_proto_init() {
	if File_query_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_query_proto_rawDesc), len(file_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_query_proto_goTypes,
		DependencyIndexes: file_query_proto_depIdxs,
		MessageInfos:      file_query_proto_msgTypes,
	}.Build()
	File_query_proto = out.File
	file_query_proto_goTypes = nil
	file_query_proto_depIdxs = nil
}
