// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: consensusservice.proto

package consensus

import (
	reflect "reflect"
	unsafe "unsafe"

	consensusdata "github.com/multigres/multigres/go/pb/consensusdata"
	multipoolermanagerdata "github.com/multigres/multigres/go/pb/multipoolermanagerdata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_consensusservice_proto protoreflect.FileDescriptor

const file_consensusservice_proto_rawDesc = "" +
	"\n" +
	"\x16consensusservice.proto\x12\tconsensus\x1a\x13consensusdata.proto\x1a\x1cmultipoolermanagerdata.proto2\xd6\b\n" +
	"\x14MultiPoolerConsensus\x12N\n" +
	"\tBeginTerm\x12\x1f.consensusdata.BeginTermRequest\x1a .consensusdata.BeginTermResponse\x12E\n" +
	"\x06Status\x12\x1c.consensusdata.StatusRequest\x1a\x1d.consensusdata.StatusResponse\x12r\n" +
	"\x0fEmergencyDemote\x12..multipoolermanagerdata.EmergencyDemoteRequest\x1a/.multipoolermanagerdata.EmergencyDemoteResponse\x12Z\n" +
	"\aPromote\x12&.multipoolermanagerdata.PromoteRequest\x1a'.multipoolermanagerdata.PromoteResponse\x12\x90\x01\n" +
	"\x13UpdateConsensusRule\x12;.multipoolermanagerdata.UpdateSynchronousStandbyListRequest\x1a<.multipoolermanagerdata.UpdateSynchronousStandbyListResponse\x12{\n" +
	"\x12DemoteStalePrimary\x121.multipoolermanagerdata.DemoteStalePrimaryRequest\x1a2.multipoolermanagerdata.DemoteStalePrimaryResponse\x12{\n" +
	"\x12SetPrimaryConnInfo\x121.multipoolermanagerdata.SetPrimaryConnInfoRequest\x1a2.multipoolermanagerdata.SetPrimaryConnInfoResponse\x12o\n" +
	"\x0eRewindToSource\x12-.multipoolermanagerdata.RewindToSourceRequest\x1a..multipoolermanagerdata.RewindToSourceResponse\x12H\n" +
	"\aRecruit\x12\x1d.consensusdata.RecruitRequest\x1a\x1e.consensusdata.RecruitResponse\x12H\n" +
	"\aPropose\x12\x1d.consensusdata.ProposeRequest\x1a\x1e.consensusdata.ProposeResponse\x12E\n" +
	"\x06Inform\x12\x1c.consensusdata.InformRequest\x1a\x1d.consensusdata.InformResponseB0Z.github.com/multigres/multigres/go/pb/consensusb\x06proto3"

var file_consensusservice_proto_goTypes = []any{
	(*consensusdata.BeginTermRequest)(nil),                              // 0: consensusdata.BeginTermRequest
	(*consensusdata.StatusRequest)(nil),                                 // 1: consensusdata.StatusRequest
	(*multipoolermanagerdata.EmergencyDemoteRequest)(nil),               // 2: multipoolermanagerdata.EmergencyDemoteRequest
	(*multipoolermanagerdata.PromoteRequest)(nil),                       // 3: multipoolermanagerdata.PromoteRequest
	(*multipoolermanagerdata.UpdateSynchronousStandbyListRequest)(nil),  // 4: multipoolermanagerdata.UpdateSynchronousStandbyListRequest
	(*multipoolermanagerdata.DemoteStalePrimaryRequest)(nil),            // 5: multipoolermanagerdata.DemoteStalePrimaryRequest
	(*multipoolermanagerdata.SetPrimaryConnInfoRequest)(nil),            // 6: multipoolermanagerdata.SetPrimaryConnInfoRequest
	(*multipoolermanagerdata.RewindToSourceRequest)(nil),                // 7: multipoolermanagerdata.RewindToSourceRequest
	(*consensusdata.RecruitRequest)(nil),                                // 8: consensusdata.RecruitRequest
	(*consensusdata.ProposeRequest)(nil),                                // 9: consensusdata.ProposeRequest
	(*consensusdata.InformRequest)(nil),                                 // 10: consensusdata.InformRequest
	(*consensusdata.BeginTermResponse)(nil),                             // 11: consensusdata.BeginTermResponse
	(*consensusdata.StatusResponse)(nil),                                // 12: consensusdata.StatusResponse
	(*multipoolermanagerdata.EmergencyDemoteResponse)(nil),              // 13: multipoolermanagerdata.EmergencyDemoteResponse
	(*multipoolermanagerdata.PromoteResponse)(nil),                      // 14: multipoolermanagerdata.PromoteResponse
	(*multipoolermanagerdata.UpdateSynchronousStandbyListResponse)(nil), // 15: multipoolermanagerdata.UpdateSynchronousStandbyListResponse
	(*multipoolermanagerdata.DemoteStalePrimaryResponse)(nil),           // 16: multipoolermanagerdata.DemoteStalePrimaryResponse
	(*multipoolermanagerdata.SetPrimaryConnInfoResponse)(nil),           // 17: multipoolermanagerdata.SetPrimaryConnInfoResponse
	(*multipoolermanagerdata.RewindToSourceResponse)(nil),               // 18: multipoolermanagerdata.RewindToSourceResponse
	(*consensusdata.RecruitResponse)(nil),                               // 19: consensusdata.RecruitResponse
	(*consensusdata.ProposeResponse)(nil),                               // 20: consensusdata.ProposeResponse
	(*consensusdata.InformResponse)(nil),                                // 21: consensusdata.InformResponse
}
var file_consensusservice_proto_depIdxs = []int32{
	0,  // 0: consensus.MultiPoolerConsensus.BeginTerm:input_type -> consensusdata.BeginTermRequest
	1,  // 1: consensus.MultiPoolerConsensus.Status:input_type -> consensusdata.StatusRequest
	2,  // 2: consensus.MultiPoolerConsensus.EmergencyDemote:input_type -> multipoolermanagerdata.EmergencyDemoteRequest
	3,  // 3: consensus.MultiPoolerConsensus.Promote:input_type -> multipoolermanagerdata.PromoteRequest
	4,  // 4: consensus.MultiPoolerConsensus.UpdateConsensusRule:input_type -> multipoolermanagerdata.UpdateSynchronousStandbyListRequest
	5,  // 5: consensus.MultiPoolerConsensus.DemoteStalePrimary:input_type -> multipoolermanagerdata.DemoteStalePrimaryRequest
	6,  // 6: consensus.MultiPoolerConsensus.SetPrimaryConnInfo:input_type -> multipoolermanagerdata.SetPrimaryConnInfoRequest
	7,  // 7: consensus.MultiPoolerConsensus.RewindToSource:input_type -> multipoolermanagerdata.RewindToSourceRequest
	8,  // 8: consensus.MultiPoolerConsensus.Recruit:input_type -> consensusdata.RecruitRequest
	9,  // 9: consensus.MultiPoolerConsensus.Propose:input_type -> consensusdata.ProposeRequest
	10, // 10: consensus.MultiPoolerConsensus.Inform:input_type -> consensusdata.InformRequest
	11, // 11: consensus.MultiPoolerConsensus.BeginTerm:output_type -> consensusdata.BeginTermResponse
	12, // 12: consensus.MultiPoolerConsensus.Status:output_type -> consensusdata.StatusResponse
	13, // 13: consensus.MultiPoolerConsensus.EmergencyDemote:output_type -> multipoolermanagerdata.EmergencyDemoteResponse
	14, // 14: consensus.MultiPoolerConsensus.Promote:output_type -> multipoolermanagerdata.PromoteResponse
	15, // 15: consensus.MultiPoolerConsensus.UpdateConsensusRule:output_type -> multipoolermanagerdata.UpdateSynchronousStandbyListResponse
	16, // 16: consensus.MultiPoolerConsensus.DemoteStalePrimary:output_type -> multipoolermanagerdata.DemoteStalePrimaryResponse
	17, // 17: consensus.MultiPoolerConsensus.SetPrimaryConnInfo:output_type -> multipoolermanagerdata.SetPrimaryConnInfoResponse
	18, // 18: consensus.MultiPoolerConsensus.RewindToSource:output_type -> multipoolermanagerdata.RewindToSourceResponse
	19, // 19: consensus.MultiPoolerConsensus.Recruit:output_type -> consensusdata.RecruitResponse
	20, // 20: consensus.MultiPoolerConsensus.Propose:output_type -> consensusdata.ProposeResponse
	21, // 21: consensus.MultiPoolerConsensus.Inform:output_type -> consensusdata.InformResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_consensusservice_proto_init() }
func file_consensusservice_proto_init() {
	if File_consensusservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensusservice_proto_rawDesc), len(file_consensusservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_consensusservice_proto_goTypes,
		DependencyIndexes: file_consensusservice_proto_depIdxs,
	}.Build()
	File_consensusservice_proto = out.File
	file_consensusservice_proto_goTypes = nil
	file_consensusservice_proto_depIdxs = nil
}
