//
//Copyright 2025 Supabase, Inc.
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// This file contains the RPC service definition for multipooler.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v4.25.1
// source: multipoolerservice.proto

package multipoolerservice

import (
	context "context"
	query "github.com/multigres/multigres/go/pb/query"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MultiPoolerService_ExecuteQuery_FullMethodName        = "/multipoolerservice.MultiPoolerService/ExecuteQuery"
	MultiPoolerService_StreamExecute_FullMethodName       = "/multipoolerservice.MultiPoolerService/StreamExecute"
	MultiPoolerService_PortalStreamExecute_FullMethodName = "/multipoolerservice.MultiPoolerService/PortalStreamExecute"
	MultiPoolerService_Describe_FullMethodName            = "/multipoolerservice.MultiPoolerService/Describe"
	MultiPoolerService_GetAuthCredentials_FullMethodName  = "/multipoolerservice.MultiPoolerService/GetAuthCredentials"
	MultiPoolerService_CopyBidiExecute_FullMethodName     = "/multipoolerservice.MultiPoolerService/CopyBidiExecute"
)

// MultiPoolerServiceClient is the client API for MultiPoolerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MultiPoolerService provides connection pooling and query execution
type MultiPoolerServiceClient interface {
	// ExecuteQuery executes a SQL query and returns the result
	// This should be used sparingly only when we know the result set is small,
	// otherwise StreamExecute should be used.
	ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (*ExecuteQueryResponse, error)
	// StreamExecute executes a SQL query and streams the results back
	StreamExecute(ctx context.Context, in *StreamExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[query.QueryResultPayload], error)
	// PortalStreamExecute executes a portal (bound prepared statement) and streams results
	// Returns reserved connection information for session affinity
	PortalStreamExecute(ctx context.Context, in *PortalStreamExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PortalStreamExecuteResponse], error)
	// Describe returns metadata about a prepared statement or portal
	Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error)
	// GetAuthCredentials retrieves authentication credentials for a user.
	// Used by multigateway to get SCRAM password hashes for client authentication.
	//
	// NOTE: This API may change. Currently fetches credentials one user at a time.
	// Future iterations could switch to a streaming model where multigateway maintains
	// an up-to-date cache of all password hashes and by real-time updates from multipooler
	// when any credentials change.
	GetAuthCredentials(ctx context.Context, in *GetAuthCredentialsRequest, opts ...grpc.CallOption) (*GetAuthCredentialsResponse, error)
	// CopyBidiExecute handles bidirectional streaming operations (e.g., COPY commands).
	// The gateway sends the initial command and then streams data/messages.
	// The pooler responds with protocol-specific messages and final result.
	CopyBidiExecute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CopyBidiExecuteRequest, CopyBidiExecuteResponse], error)
}

type multiPoolerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMultiPoolerServiceClient(cc grpc.ClientConnInterface) MultiPoolerServiceClient {
	return &multiPoolerServiceClient{cc}
}

func (c *multiPoolerServiceClient) ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (*ExecuteQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteQueryResponse)
	err := c.cc.Invoke(ctx, MultiPoolerService_ExecuteQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiPoolerServiceClient) StreamExecute(ctx context.Context, in *StreamExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[query.QueryResultPayload], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MultiPoolerService_ServiceDesc.Streams[0], MultiPoolerService_StreamExecute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamExecuteRequest, query.QueryResultPayload]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultiPoolerService_StreamExecuteClient = grpc.ServerStreamingClient[query.QueryResultPayload]

func (c *multiPoolerServiceClient) PortalStreamExecute(ctx context.Context, in *PortalStreamExecuteRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PortalStreamExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MultiPoolerService_ServiceDesc.Streams[1], MultiPoolerService_PortalStreamExecute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PortalStreamExecuteRequest, PortalStreamExecuteResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultiPoolerService_PortalStreamExecuteClient = grpc.ServerStreamingClient[PortalStreamExecuteResponse]

func (c *multiPoolerServiceClient) Describe(ctx context.Context, in *DescribeRequest, opts ...grpc.CallOption) (*DescribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeResponse)
	err := c.cc.Invoke(ctx, MultiPoolerService_Describe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiPoolerServiceClient) GetAuthCredentials(ctx context.Context, in *GetAuthCredentialsRequest, opts ...grpc.CallOption) (*GetAuthCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuthCredentialsResponse)
	err := c.cc.Invoke(ctx, MultiPoolerService_GetAuthCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *multiPoolerServiceClient) CopyBidiExecute(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[CopyBidiExecuteRequest, CopyBidiExecuteResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MultiPoolerService_ServiceDesc.Streams[2], MultiPoolerService_CopyBidiExecute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[CopyBidiExecuteRequest, CopyBidiExecuteResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultiPoolerService_CopyBidiExecuteClient = grpc.BidiStreamingClient[CopyBidiExecuteRequest, CopyBidiExecuteResponse]

// MultiPoolerServiceServer is the server API for MultiPoolerService service.
// All implementations must embed UnimplementedMultiPoolerServiceServer
// for forward compatibility.
//
// MultiPoolerService provides connection pooling and query execution
type MultiPoolerServiceServer interface {
	// ExecuteQuery executes a SQL query and returns the result
	// This should be used sparingly only when we know the result set is small,
	// otherwise StreamExecute should be used.
	ExecuteQuery(context.Context, *ExecuteQueryRequest) (*ExecuteQueryResponse, error)
	// StreamExecute executes a SQL query and streams the results back
	StreamExecute(*StreamExecuteRequest, grpc.ServerStreamingServer[query.QueryResultPayload]) error
	// PortalStreamExecute executes a portal (bound prepared statement) and streams results
	// Returns reserved connection information for session affinity
	PortalStreamExecute(*PortalStreamExecuteRequest, grpc.ServerStreamingServer[PortalStreamExecuteResponse]) error
	// Describe returns metadata about a prepared statement or portal
	Describe(context.Context, *DescribeRequest) (*DescribeResponse, error)
	// GetAuthCredentials retrieves authentication credentials for a user.
	// Used by multigateway to get SCRAM password hashes for client authentication.
	//
	// NOTE: This API may change. Currently fetches credentials one user at a time.
	// Future iterations could switch to a streaming model where multigateway maintains
	// an up-to-date cache of all password hashes and by real-time updates from multipooler
	// when any credentials change.
	GetAuthCredentials(context.Context, *GetAuthCredentialsRequest) (*GetAuthCredentialsResponse, error)
	// CopyBidiExecute handles bidirectional streaming operations (e.g., COPY commands).
	// The gateway sends the initial command and then streams data/messages.
	// The pooler responds with protocol-specific messages and final result.
	CopyBidiExecute(grpc.BidiStreamingServer[CopyBidiExecuteRequest, CopyBidiExecuteResponse]) error
	mustEmbedUnimplementedMultiPoolerServiceServer()
}

// UnimplementedMultiPoolerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMultiPoolerServiceServer struct{}

func (UnimplementedMultiPoolerServiceServer) ExecuteQuery(context.Context, *ExecuteQueryRequest) (*ExecuteQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedMultiPoolerServiceServer) StreamExecute(*StreamExecuteRequest, grpc.ServerStreamingServer[query.QueryResultPayload]) error {
	return status.Errorf(codes.Unimplemented, "method StreamExecute not implemented")
}
func (UnimplementedMultiPoolerServiceServer) PortalStreamExecute(*PortalStreamExecuteRequest, grpc.ServerStreamingServer[PortalStreamExecuteResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PortalStreamExecute not implemented")
}
func (UnimplementedMultiPoolerServiceServer) Describe(context.Context, *DescribeRequest) (*DescribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Describe not implemented")
}
func (UnimplementedMultiPoolerServiceServer) GetAuthCredentials(context.Context, *GetAuthCredentialsRequest) (*GetAuthCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthCredentials not implemented")
}
func (UnimplementedMultiPoolerServiceServer) CopyBidiExecute(grpc.BidiStreamingServer[CopyBidiExecuteRequest, CopyBidiExecuteResponse]) error {
	return status.Errorf(codes.Unimplemented, "method CopyBidiExecute not implemented")
}
func (UnimplementedMultiPoolerServiceServer) mustEmbedUnimplementedMultiPoolerServiceServer() {}
func (UnimplementedMultiPoolerServiceServer) testEmbeddedByValue()                            {}

// UnsafeMultiPoolerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MultiPoolerServiceServer will
// result in compilation errors.
type UnsafeMultiPoolerServiceServer interface {
	mustEmbedUnimplementedMultiPoolerServiceServer()
}

func RegisterMultiPoolerServiceServer(s grpc.ServiceRegistrar, srv MultiPoolerServiceServer) {
	// If the following call pancis, it indicates UnimplementedMultiPoolerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MultiPoolerService_ServiceDesc, srv)
}

func _MultiPoolerService_ExecuteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiPoolerServiceServer).ExecuteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiPoolerService_ExecuteQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiPoolerServiceServer).ExecuteQuery(ctx, req.(*ExecuteQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiPoolerService_StreamExecute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MultiPoolerServiceServer).StreamExecute(m, &grpc.GenericServerStream[StreamExecuteRequest, query.QueryResultPayload]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultiPoolerService_StreamExecuteServer = grpc.ServerStreamingServer[query.QueryResultPayload]

func _MultiPoolerService_PortalStreamExecute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PortalStreamExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MultiPoolerServiceServer).PortalStreamExecute(m, &grpc.GenericServerStream[PortalStreamExecuteRequest, PortalStreamExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultiPoolerService_PortalStreamExecuteServer = grpc.ServerStreamingServer[PortalStreamExecuteResponse]

func _MultiPoolerService_Describe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiPoolerServiceServer).Describe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiPoolerService_Describe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiPoolerServiceServer).Describe(ctx, req.(*DescribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiPoolerService_GetAuthCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MultiPoolerServiceServer).GetAuthCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MultiPoolerService_GetAuthCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MultiPoolerServiceServer).GetAuthCredentials(ctx, req.(*GetAuthCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MultiPoolerService_CopyBidiExecute_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MultiPoolerServiceServer).CopyBidiExecute(&grpc.GenericServerStream[CopyBidiExecuteRequest, CopyBidiExecuteResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MultiPoolerService_CopyBidiExecuteServer = grpc.BidiStreamingServer[CopyBidiExecuteRequest, CopyBidiExecuteResponse]

// MultiPoolerService_ServiceDesc is the grpc.ServiceDesc for MultiPoolerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MultiPoolerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "multipoolerservice.MultiPoolerService",
	HandlerType: (*MultiPoolerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecuteQuery",
			Handler:    _MultiPoolerService_ExecuteQuery_Handler,
		},
		{
			MethodName: "Describe",
			Handler:    _MultiPoolerService_Describe_Handler,
		},
		{
			MethodName: "GetAuthCredentials",
			Handler:    _MultiPoolerService_GetAuthCredentials_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamExecute",
			Handler:       _MultiPoolerService_StreamExecute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PortalStreamExecute",
			Handler:       _MultiPoolerService_PortalStreamExecute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "CopyBidiExecute",
			Handler:       _MultiPoolerService_CopyBidiExecute_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "multipoolerservice.proto",
}
