// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package plpgsql

import (
	"fmt"

	"github.com/multigres/multigres/go/common/parser/ast/plpgsqlast"
)

// lexer implements the plpgsqlLexer interface generated by goyacc.
//
// Scaffolding only: Lex returns EOF immediately so the grammar's empty start
// rule fires once and we publish an empty PLpgSQL_function. Real tokenization
// (wrapping the main parser.Lexer and emitting PL/pgSQL keywords) is added as
// the grammar is ported.
type lexer struct {
	input  string
	done   bool
	result *plpgsqlast.PLpgSQL_function
	err    error
}

func newLexer(input string) *lexer {
	return &lexer{input: input}
}

// Lex implements plpgsqlLexer. It returns 0 (EOF) on every call — the empty
// grammar accepts that as a successful parse of the root production.
func (l *lexer) Lex(lval *plpgsqlSymType) int {
	l.done = true
	return 0
}

// Error implements plpgsqlLexer. Records only the first error we see.
func (l *lexer) Error(s string) {
	if l.err == nil {
		l.err = fmt.Errorf("plpgsql parse error: %s", s)
	}
}

// SetResult satisfies the plpgsqlResultSetter interface used by the grammar's
// start-rule action to publish the parsed function.
func (l *lexer) SetResult(fn *plpgsqlast.PLpgSQL_function) {
	l.result = fn
}
