// Code generated by goyacc -f -p plpgsql -o plpgsql.go plpgsql.y. DO NOT EDIT.

//line plpgsql.y:2
// PostgreSQL Database Management System
// (also known as Postgres, formerly known as Postgres95)
//
//  Portions Copyright (c) 2025, Supabase, Inc
//
//  Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group
//
//  Portions Copyright (c) 1994, The Regents of the University of California
//
// Permission to use, copy, modify, and distribute this software and its
// documentation for any purpose, without fee, and without a written agreement
// is hereby granted, provided that the above copyright notice and this
// paragraph and the following two paragraphs appear in all copies.
//
// IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
// DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
// LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS
// DOCUMENTATION, EVEN IF THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
//
// THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
// AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
// ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATIONS TO
// PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.

// Ported from postgres/src/pl/plpgsql/src/pl_gram.y. Currently only the
// scaffolding: the grammar accepts an empty body and produces an empty
// PLpgSQL_function root node. Statement productions (block, DECLARE, IF,
// LOOP, FOR, EXECSQL, DYNEXECUTE, …) are added incrementally as the grammar
// is ported.

package plpgsql

import (
	"fmt"
	__yyfmt__ "fmt"
	__yyunsafe__ "unsafe"

	"github.com/multigres/multigres/go/common/parser/ast/plpgsqlast" //line plpgsql.y:34
)

// plpgsqlResultSetter is accessed via type assertion on the lexer so actions
// can publish the parsed function without depending on a concrete lexer type.
type plpgsqlResultSetter interface {
	SetResult(*plpgsqlast.PLpgSQL_function)
}

const (
	IDENT                  = 57346
	UIDENT                 = 57347
	FCONST                 = 57348
	SCONST                 = 57349
	USCONST                = 57350
	BCONST                 = 57351
	XCONST                 = 57352
	Op                     = 57353
	ICONST                 = 57354
	PARAM                  = 57355
	TYPECAST               = 57356
	DOT_DOT                = 57357
	COLON_EQUALS           = 57358
	EQUALS_GREATER         = 57359
	LESS_EQUALS            = 57360
	GREATER_EQUALS         = 57361
	NOT_EQUALS             = 57362
	T_WORD                 = 57363
	T_CWORD                = 57364
	T_DATUM                = 57365
	LESS_LESS              = 57366
	GREATER_GREATER        = 57367
	K_ABSOLUTE             = 57368
	K_ALIAS                = 57369
	K_ALL                  = 57370
	K_AND                  = 57371
	K_ARRAY                = 57372
	K_ASSERT               = 57373
	K_BACKWARD             = 57374
	K_BEGIN                = 57375
	K_BY                   = 57376
	K_CALL                 = 57377
	K_CASE                 = 57378
	K_CHAIN                = 57379
	K_CLOSE                = 57380
	K_COLLATE              = 57381
	K_COLUMN               = 57382
	K_COLUMN_NAME          = 57383
	K_COMMIT               = 57384
	K_CONSTANT             = 57385
	K_CONSTRAINT           = 57386
	K_CONSTRAINT_NAME      = 57387
	K_CONTINUE             = 57388
	K_CURRENT              = 57389
	K_CURSOR               = 57390
	K_DATATYPE             = 57391
	K_DEBUG                = 57392
	K_DECLARE              = 57393
	K_DEFAULT              = 57394
	K_DETAIL               = 57395
	K_DIAGNOSTICS          = 57396
	K_DO                   = 57397
	K_DUMP                 = 57398
	K_ELSE                 = 57399
	K_ELSIF                = 57400
	K_END                  = 57401
	K_ERRCODE              = 57402
	K_ERROR                = 57403
	K_EXCEPTION            = 57404
	K_EXECUTE              = 57405
	K_EXIT                 = 57406
	K_FETCH                = 57407
	K_FIRST                = 57408
	K_FOR                  = 57409
	K_FOREACH              = 57410
	K_FORWARD              = 57411
	K_FROM                 = 57412
	K_GET                  = 57413
	K_HINT                 = 57414
	K_IF                   = 57415
	K_IMPORT               = 57416
	K_IN                   = 57417
	K_INFO                 = 57418
	K_INSERT               = 57419
	K_INTO                 = 57420
	K_IS                   = 57421
	K_LAST                 = 57422
	K_LOG                  = 57423
	K_LOOP                 = 57424
	K_MERGE                = 57425
	K_MESSAGE              = 57426
	K_MESSAGE_TEXT         = 57427
	K_MOVE                 = 57428
	K_NEXT                 = 57429
	K_NO                   = 57430
	K_NOT                  = 57431
	K_NOTICE               = 57432
	K_NULL                 = 57433
	K_OPEN                 = 57434
	K_OPTION               = 57435
	K_OR                   = 57436
	K_PERFORM              = 57437
	K_PG_CONTEXT           = 57438
	K_PG_DATATYPE_NAME     = 57439
	K_PG_EXCEPTION_CONTEXT = 57440
	K_PG_EXCEPTION_DETAIL  = 57441
	K_PG_EXCEPTION_HINT    = 57442
	K_PG_ROUTINE_OID       = 57443
	K_PRINT_STRICT_PARAMS  = 57444
	K_PRIOR                = 57445
	K_QUERY                = 57446
	K_RAISE                = 57447
	K_RELATIVE             = 57448
	K_RETURN               = 57449
	K_RETURNED_SQLSTATE    = 57450
	K_REVERSE              = 57451
	K_ROLLBACK             = 57452
	K_ROW_COUNT            = 57453
	K_ROWTYPE              = 57454
	K_SCHEMA               = 57455
	K_SCHEMA_NAME          = 57456
	K_SCROLL               = 57457
	K_SLICE                = 57458
	K_SQLSTATE             = 57459
	K_STACKED              = 57460
	K_STRICT               = 57461
	K_TABLE                = 57462
	K_TABLE_NAME           = 57463
	K_THEN                 = 57464
	K_TO                   = 57465
	K_TYPE                 = 57466
	K_USE_COLUMN           = 57467
	K_USE_VARIABLE         = 57468
	K_USING                = 57469
	K_VARIABLE_CONFLICT    = 57470
	K_WARNING              = 57471
	K_WHEN                 = 57472
	K_WHILE                = 57473
)

var plpgsqlToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"UIDENT",
	"FCONST",
	"SCONST",
	"USCONST",
	"BCONST",
	"XCONST",
	"Op",
	"ICONST",
	"PARAM",
	"TYPECAST",
	"DOT_DOT",
	"COLON_EQUALS",
	"EQUALS_GREATER",
	"LESS_EQUALS",
	"GREATER_EQUALS",
	"NOT_EQUALS",
	"T_WORD",
	"T_CWORD",
	"T_DATUM",
	"LESS_LESS",
	"GREATER_GREATER",
	"K_ABSOLUTE",
	"K_ALIAS",
	"K_ALL",
	"K_AND",
	"K_ARRAY",
	"K_ASSERT",
	"K_BACKWARD",
	"K_BEGIN",
	"K_BY",
	"K_CALL",
	"K_CASE",
	"K_CHAIN",
	"K_CLOSE",
	"K_COLLATE",
	"K_COLUMN",
	"K_COLUMN_NAME",
	"K_COMMIT",
	"K_CONSTANT",
	"K_CONSTRAINT",
	"K_CONSTRAINT_NAME",
	"K_CONTINUE",
	"K_CURRENT",
	"K_CURSOR",
	"K_DATATYPE",
	"K_DEBUG",
	"K_DECLARE",
	"K_DEFAULT",
	"K_DETAIL",
	"K_DIAGNOSTICS",
	"K_DO",
	"K_DUMP",
	"K_ELSE",
	"K_ELSIF",
	"K_END",
	"K_ERRCODE",
	"K_ERROR",
	"K_EXCEPTION",
	"K_EXECUTE",
	"K_EXIT",
	"K_FETCH",
	"K_FIRST",
	"K_FOR",
	"K_FOREACH",
	"K_FORWARD",
	"K_FROM",
	"K_GET",
	"K_HINT",
	"K_IF",
	"K_IMPORT",
	"K_IN",
	"K_INFO",
	"K_INSERT",
	"K_INTO",
	"K_IS",
	"K_LAST",
	"K_LOG",
	"K_LOOP",
	"K_MERGE",
	"K_MESSAGE",
	"K_MESSAGE_TEXT",
	"K_MOVE",
	"K_NEXT",
	"K_NO",
	"K_NOT",
	"K_NOTICE",
	"K_NULL",
	"K_OPEN",
	"K_OPTION",
	"K_OR",
	"K_PERFORM",
	"K_PG_CONTEXT",
	"K_PG_DATATYPE_NAME",
	"K_PG_EXCEPTION_CONTEXT",
	"K_PG_EXCEPTION_DETAIL",
	"K_PG_EXCEPTION_HINT",
	"K_PG_ROUTINE_OID",
	"K_PRINT_STRICT_PARAMS",
	"K_PRIOR",
	"K_QUERY",
	"K_RAISE",
	"K_RELATIVE",
	"K_RETURN",
	"K_RETURNED_SQLSTATE",
	"K_REVERSE",
	"K_ROLLBACK",
	"K_ROW_COUNT",
	"K_ROWTYPE",
	"K_SCHEMA",
	"K_SCHEMA_NAME",
	"K_SCROLL",
	"K_SLICE",
	"K_SQLSTATE",
	"K_STACKED",
	"K_STRICT",
	"K_TABLE",
	"K_TABLE_NAME",
	"K_THEN",
	"K_TO",
	"K_TYPE",
	"K_USE_COLUMN",
	"K_USE_VARIABLE",
	"K_USING",
	"K_VARIABLE_CONFLICT",
	"K_WARNING",
	"K_WHEN",
	"K_WHILE",
	"';'",
	"'='",
}

var plpgsqlStatenames = [...]string{}

const (
	plpgsqlEofCode          = 1
	plpgsqlErrCode          = 2
	plpgsqlInitialStackSize = 16
)

//line plpgsql.y:479

//line yacctab:1
var plpgsqlExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const plpgsqlPrivate = 57344

const plpgsqlLast = 286

var plpgsqlAct = [...]int{
	11, 120, 119, 116, 119, 13, 14, 7, 15, 16,
	17, 18, 97, 117, 19, 129, 20, 21, 22, 23,
	24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
	99, 34, 35, 36, 37, 38, 123, 39, 128, 40,
	41, 42, 9, 43, 44, 45, 113, 8, 46, 101,
	47, 48, 5, 49, 126, 50, 51, 2, 52, 53,
	54, 6, 55, 56, 57, 58, 59, 60, 107, 61,
	12, 62, 63, 114, 64, 65, 66, 67, 68, 69,
	70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
	80, 81, 82, 83, 84, 85, 86, 87, 4, 88,
	89, 105, 106, 90, 91, 92, 11, 93, 94, 111,
	103, 13, 14, 95, 15, 16, 17, 18, 125, 118,
	19, 118, 20, 21, 22, 23, 24, 25, 26, 27,
	28, 29, 30, 31, 32, 33, 127, 34, 35, 36,
	37, 38, 100, 39, 122, 40, 41, 42, 10, 43,
	44, 45, 112, 104, 46, 124, 47, 48, 121, 49,
	98, 50, 51, 96, 52, 53, 54, 3, 55, 56,
	57, 58, 59, 60, 1, 61, 0, 62, 63, 0,
	64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
	74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
	84, 85, 86, 87, 0, 88, 89, 0, 0, 90,
	91, 92, 0, 93, 94, 109, 110, 0, 5, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 115, 0, 0, 0, 0,
	0, 0, 0, 102, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 108,
}

var plpgsqlPact = [...]int{
	28, -1000, -125, 14, -9, 85, -1000, -1000, -1000, -21,
	24, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, 194, -21, -1000, -1000, -1000,
	3, -1000, 85, -1000, -129, -1000, -1000, -12, -131, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -53, -14, -76, -1000, -1000, -1000, -1000, -1000, -1000,
}

var plpgsqlPgo = [...]int{
	0, 174, 57, 167, 163, 12, 160, 158, 155, 152,
	144, 113, 110, 102, 101, 98, 73, 142, 70, 68,
	61, 54, 13,
}

//line plpgsql.y:479
type plpgsqlSymType struct {
	union    any
	str      string
	ival     int
	location int
	yys      int
}

func (st *plpgsqlSymType) blockUnion() *plpgsqlast.PLpgSQL_stmt_block {
	v, _ := st.union.(*plpgsqlast.PLpgSQL_stmt_block)
	return v
}

func (st *plpgsqlSymType) bvalUnion() bool {
	v, _ := st.union.(bool)
	return v
}

func (st *plpgsqlSymType) datumUnion() plpgsqlast.Datum {
	v, _ := st.union.(plpgsqlast.Datum)
	return v
}

func (st *plpgsqlSymType) datumsUnion() []plpgsqlast.Datum {
	v, _ := st.union.([]plpgsqlast.Datum)
	return v
}

func (st *plpgsqlSymType) declsectUnion() declSect {
	v, _ := st.union.(declSect)
	return v
}

func (st *plpgsqlSymType) exprUnion() *plpgsqlast.PLpgSQL_expr {
	v, _ := st.union.(*plpgsqlast.PLpgSQL_expr)
	return v
}

func (st *plpgsqlSymType) functionUnion() *plpgsqlast.PLpgSQL_function {
	v, _ := st.union.(*plpgsqlast.PLpgSQL_function)
	return v
}

func (st *plpgsqlSymType) stmtUnion() plpgsqlast.Stmt {
	v, _ := st.union.(plpgsqlast.Stmt)
	return v
}

func (st *plpgsqlSymType) stmtsUnion() []plpgsqlast.Stmt {
	v, _ := st.union.([]plpgsqlast.Stmt)
	return v
}

func (st *plpgsqlSymType) typUnion() *plpgsqlast.PLpgSQL_type {
	v, _ := st.union.(*plpgsqlast.PLpgSQL_type)
	return v
}

var plpgsqlR1 = [...]int{
	0, 1, 20, 20, 2, 3, 3, 4, 4, 5,
	5, 6, 9, 9, 7, 10, 10, 8, 8, 21,
	21, 22, 22, 11, 11, 12, 12, 12, 13, 14,
	19, 19, 15, 15, 16, 16, 17, 17, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
	18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
}

var plpgsqlR2 = [...]int{
	0, 2, 0, 1, 5, 1, 3, 2, 1, 1,
	1, 5, 0, 1, 0, 0, 2, 1, 1, 1,
	1, 1, 1, 0, 2, 2, 1, 1, 2, 2,
	1, 1, 0, 3, 0, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
}

var plpgsqlChk = [...]int{
	-1000, -1, -2, -3, -15, 24, -20, 132, 33, 51,
	-17, 21, -18, 26, 27, 29, 30, 31, 32, 35,
	37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
	47, 48, 49, 50, 52, 53, 54, 55, 56, 58,
	60, 61, 62, 64, 65, 66, 69, 71, 72, 74,
	76, 77, 79, 80, 81, 83, 84, 85, 86, 87,
	88, 90, 92, 93, 95, 96, 97, 98, 99, 100,
	101, 102, 103, 104, 105, 106, 107, 108, 109, 110,
	111, 112, 113, 114, 115, 116, 117, 118, 120, 121,
	124, 125, 126, 128, 129, -11, -4, -5, -6, 51,
	-17, 25, 59, -12, -2, -14, -13, -19, 91, 21,
	22, -5, -9, 43, -16, -17, 132, -22, 133, 16,
	132, -7, -10, 89, -8, 132, -21, -22, 52, 91,
}

var plpgsqlDef = [...]int{
	32, -2, 2, 0, 5, 0, 1, 3, 23, 0,
	0, 36, 37, 38, 39, 40, 41, 42, 43, 44,
	45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
	55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
	65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
	75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
	85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
	95, 96, 97, 98, 99, 100, 101, 102, 103, 104,
	105, 106, 107, 108, 109, 110, 111, 112, 113, 114,
	115, 116, 117, 118, 119, 32, 6, 8, 9, 10,
	12, 33, 34, 24, 0, 26, 27, 0, 0, 30,
	31, 7, 14, 13, 4, 35, 25, 29, 21, 22,
	28, 15, 0, 0, 11, 17, 18, 19, 20, 16,
}

var plpgsqlTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 132,
	3, 133,
}

var plpgsqlTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
	112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
	122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
}

var plpgsqlTok3 = [...]int{
	0,
}

var plpgsqlErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

func plpgsqlIaddr(v any) __yyunsafe__.Pointer {
	type h struct {
		t __yyunsafe__.Pointer
		p __yyunsafe__.Pointer
	}
	return (*h)(__yyunsafe__.Pointer(&v)).p
}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	plpgsqlDebug        = 0
	plpgsqlErrorVerbose = false
)

type plpgsqlLexer interface {
	Lex(lval *plpgsqlSymType) int
	Error(s string)
}

type plpgsqlParser interface {
	Parse(plpgsqlLexer) int
	Lookahead() int
}

type plpgsqlParserImpl struct {
	lval  plpgsqlSymType
	stack [plpgsqlInitialStackSize]plpgsqlSymType
	char  int
}

func (p *plpgsqlParserImpl) Lookahead() int {
	return p.char
}

func plpgsqlNewParser() plpgsqlParser {
	return &plpgsqlParserImpl{}
}

const plpgsqlFlag = -1000

func plpgsqlTokname(c int) string {
	if c >= 1 && c-1 < len(plpgsqlToknames) {
		if plpgsqlToknames[c-1] != "" {
			return plpgsqlToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func plpgsqlStatname(s int) string {
	if s >= 0 && s < len(plpgsqlStatenames) {
		if plpgsqlStatenames[s] != "" {
			return plpgsqlStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func plpgsqlErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !plpgsqlErrorVerbose {
		return "syntax error"
	}

	for _, e := range plpgsqlErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + plpgsqlTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := plpgsqlPact[state]
	for tok := TOKSTART; tok-1 < len(plpgsqlToknames); tok++ {
		if n := base + tok; n >= 0 && n < plpgsqlLast && plpgsqlChk[plpgsqlAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if plpgsqlDef[state] == -2 {
		i := 0
		for plpgsqlExca[i] != -1 || plpgsqlExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; plpgsqlExca[i] >= 0; i += 2 {
			tok := plpgsqlExca[i]
			if tok < TOKSTART || plpgsqlExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if plpgsqlExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += plpgsqlTokname(tok)
	}
	return res
}

func plpgsqllex1(lex plpgsqlLexer, lval *plpgsqlSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = plpgsqlTok1[0]
		goto out
	}
	if char < len(plpgsqlTok1) {
		token = plpgsqlTok1[char]
		goto out
	}
	if char >= plpgsqlPrivate {
		if char < plpgsqlPrivate+len(plpgsqlTok2) {
			token = plpgsqlTok2[char-plpgsqlPrivate]
			goto out
		}
	}
	for i := 0; i < len(plpgsqlTok3); i += 2 {
		token = plpgsqlTok3[i+0]
		if token == char {
			token = plpgsqlTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = plpgsqlTok2[1] /* unknown char */
	}
	if plpgsqlDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", plpgsqlTokname(token), uint(char))
	}
	return char, token
}

func plpgsqlParse(plpgsqllex plpgsqlLexer) int {
	return plpgsqlNewParser().Parse(plpgsqllex)
}

func (plpgsqlrcvr *plpgsqlParserImpl) Parse(plpgsqllex plpgsqlLexer) int {
	var plpgsqln int
	var plpgsqlVAL plpgsqlSymType
	var plpgsqlDollar []plpgsqlSymType
	_ = plpgsqlDollar // silence set and not used
	plpgsqlS := plpgsqlrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	plpgsqlstate := 0
	plpgsqlrcvr.char = -1
	plpgsqltoken := -1 // plpgsqlrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		plpgsqlstate = -1
		plpgsqlrcvr.char = -1
		plpgsqltoken = -1
	}()
	plpgsqlp := -1
	goto plpgsqlstack

ret0:
	return 0

ret1:
	return 1

plpgsqlstack:
	/* put a state and value onto the stack */
	if plpgsqlDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", plpgsqlTokname(plpgsqltoken), plpgsqlStatname(plpgsqlstate))
	}

	plpgsqlp++
	if plpgsqlp >= len(plpgsqlS) {
		nyys := make([]plpgsqlSymType, len(plpgsqlS)*2)
		copy(nyys, plpgsqlS)
		plpgsqlS = nyys
	}
	plpgsqlS[plpgsqlp] = plpgsqlVAL
	plpgsqlS[plpgsqlp].yys = plpgsqlstate

plpgsqlnewstate:
	plpgsqln = plpgsqlPact[plpgsqlstate]
	if plpgsqln <= plpgsqlFlag {
		goto plpgsqldefault /* simple state */
	}
	if plpgsqlrcvr.char < 0 {
		plpgsqlrcvr.char, plpgsqltoken = plpgsqllex1(plpgsqllex, &plpgsqlrcvr.lval)
	}
	plpgsqln += plpgsqltoken
	if plpgsqln < 0 || plpgsqln >= plpgsqlLast {
		goto plpgsqldefault
	}
	plpgsqln = plpgsqlAct[plpgsqln]
	if plpgsqlChk[plpgsqln] == plpgsqltoken { /* valid shift */
		plpgsqlrcvr.char = -1
		plpgsqltoken = -1
		plpgsqlVAL = plpgsqlrcvr.lval
		plpgsqlstate = plpgsqln
		if Errflag > 0 {
			Errflag--
		}
		goto plpgsqlstack
	}

plpgsqldefault:
	/* default state action */
	plpgsqln = plpgsqlDef[plpgsqlstate]
	if plpgsqln == -2 {
		if plpgsqlrcvr.char < 0 {
			plpgsqlrcvr.char, plpgsqltoken = plpgsqllex1(plpgsqllex, &plpgsqlrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if plpgsqlExca[xi+0] == -1 && plpgsqlExca[xi+1] == plpgsqlstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			plpgsqln = plpgsqlExca[xi+0]
			if plpgsqln < 0 || plpgsqln == plpgsqltoken {
				break
			}
		}
		plpgsqln = plpgsqlExca[xi+1]
		if plpgsqln < 0 {
			goto ret0
		}
	}
	if plpgsqln == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			plpgsqllex.Error(plpgsqlErrorMessage(plpgsqlstate, plpgsqltoken))
			Nerrs++
			if plpgsqlDebug >= 1 {
				__yyfmt__.Printf("%s", plpgsqlStatname(plpgsqlstate))
				__yyfmt__.Printf(" saw %s\n", plpgsqlTokname(plpgsqltoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for plpgsqlp >= 0 {
				plpgsqln = plpgsqlPact[plpgsqlS[plpgsqlp].yys] + plpgsqlErrCode
				if plpgsqln >= 0 && plpgsqln < plpgsqlLast {
					plpgsqlstate = plpgsqlAct[plpgsqln] /* simulate a shift of "error" */
					if plpgsqlChk[plpgsqlstate] == plpgsqlErrCode {
						goto plpgsqlstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if plpgsqlDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", plpgsqlS[plpgsqlp].yys)
				}
				plpgsqlp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if plpgsqlDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", plpgsqlTokname(plpgsqltoken))
			}
			if plpgsqltoken == plpgsqlEofCode {
				goto ret1
			}
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			goto plpgsqlnewstate /* try again in the same state */
		}
	}

	/* reduction by production plpgsqln */
	if plpgsqlDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", plpgsqln, plpgsqlStatname(plpgsqlstate))
	}

	plpgsqlnt := plpgsqln
	plpgsqlpt := plpgsqlp
	_ = plpgsqlpt // guard against "declared and not used"

	plpgsqlp -= plpgsqlR2[plpgsqln]
	// plpgsqlp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if plpgsqlp+1 >= len(plpgsqlS) {
		nyys := make([]plpgsqlSymType, len(plpgsqlS)*2)
		copy(nyys, plpgsqlS)
		plpgsqlS = nyys
	}
	plpgsqlVAL = plpgsqlS[plpgsqlp+1]

	/* consult goto table to find next state */
	plpgsqln = plpgsqlR1[plpgsqln]
	plpgsqlg := plpgsqlPgo[plpgsqln]
	plpgsqlj := plpgsqlg + plpgsqlS[plpgsqlp].yys + 1

	if plpgsqlj >= plpgsqlLast {
		plpgsqlstate = plpgsqlAct[plpgsqlg]
	} else {
		plpgsqlstate = plpgsqlAct[plpgsqlj]
		if plpgsqlChk[plpgsqlstate] != -plpgsqln {
			plpgsqlstate = plpgsqlAct[plpgsqlg]
		}
	}
	// dummy call; replaced with literal code
	switch plpgsqlnt {

	case 1:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql.y:135
		{
			fn := plpgsqlast.NewPLpgSQL_function()
			fn.Action = plpgsqlDollar[1].blockUnion()
			if l, ok := plpgsqllex.(plpgsqlResultSetter); ok {
				l.SetResult(fn)
			}
		}
	case 4:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-5 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_stmt_block
//line plpgsql.y:156
		{
			block := plpgsqlast.NewPLpgSQL_stmt_block()
			block.Label = plpgsqlDollar[1].declsectUnion().label
			block.Decls = plpgsqlDollar[1].declsectUnion().decls
			block.Body = plpgsqlDollar[3].stmtsUnion()
			if err := checkLabels(plpgsqlDollar[1].declsectUnion().label, plpgsqlDollar[5].str); err != nil {
				plpgsqllex.Error(err.Error())
			}
			plpgsqlLOCAL = block
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 5:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL declSect
//line plpgsql.y:174
		{
			plpgsqlLOCAL = declSect{label: plpgsqlDollar[1].str}
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 6:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
		var plpgsqlLOCAL declSect
//line plpgsql.y:178
		{
			plpgsqlLOCAL = declSect{label: plpgsqlDollar[1].str, decls: plpgsqlDollar[3].datumsUnion()}
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 7:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL []plpgsqlast.Datum
//line plpgsql.y:185
		{
			plpgsqlLOCAL = appendDatum(plpgsqlDollar[1].datumsUnion(), plpgsqlDollar[2].datumUnion())
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 8:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL []plpgsqlast.Datum
//line plpgsql.y:189
		{
			plpgsqlLOCAL = appendDatum(nil, plpgsqlDollar[1].datumUnion())
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 9:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Datum
//line plpgsql.y:196
		{
			plpgsqlLOCAL = plpgsqlDollar[1].datumUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 10:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Datum
//line plpgsql.y:200
		{
			// extra DECLAREs are allowed and ignored, matching PG
			plpgsqlLOCAL = nil
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 11:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-5 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Datum
//line plpgsql.y:214
		{
			v := plpgsqlast.NewPLpgSQL_var(plpgsqlDollar[1].str)
			v.IsConst = plpgsqlDollar[2].bvalUnion()
			v.DataType = plpgsqlDollar[3].typUnion()
			v.NotNull = plpgsqlDollar[4].bvalUnion()
			v.DefaultVal = plpgsqlDollar[5].exprUnion()
			if v.NotNull && v.DefaultVal == nil {
				plpgsqllex.Error(fmt.Sprintf(
					"variable %q must have a default value, since it's declared NOT NULL",
					v.Refname))
			}
			plpgsqlLOCAL = v
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 12:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL bool
//line plpgsql.y:231
		{
			plpgsqlLOCAL = false
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 13:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL bool
//line plpgsql.y:235
		{
			plpgsqlLOCAL = true
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 14:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_type
//line plpgsql.y:242
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.readDatatype()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 15:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL bool
//line plpgsql.y:253
		{
			plpgsqlLOCAL = false
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 16:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL bool
//line plpgsql.y:257
		{
			plpgsqlLOCAL = true
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 17:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_expr
//line plpgsql.y:264
		{
			plpgsqlLOCAL = nil
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 18:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_expr
//line plpgsql.y:268
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.readSQLExpr()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 23:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL []plpgsqlast.Stmt
//line plpgsql.y:289
		{
			plpgsqlLOCAL = nil
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 24:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL []plpgsqlast.Stmt
//line plpgsql.y:293
		{
			// Mirror PG: don't link NULL statements into the body list.
			if plpgsqlDollar[2].stmtUnion() == nil {
				plpgsqlLOCAL = plpgsqlDollar[1].stmtsUnion()
			} else {
				plpgsqlLOCAL = append(plpgsqlDollar[1].stmtsUnion(), plpgsqlDollar[2].stmtUnion())
			}
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 25:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:305
		{
			plpgsqlLOCAL = plpgsqlDollar[1].blockUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 26:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:309
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 27:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:313
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 28:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:320
		{
			// Like PG, we build no node for NULL; it carries no meaning.
			plpgsqlLOCAL = nil
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 29:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:334
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			stmt := plpgsqlast.NewPLpgSQL_stmt_assign(plpgsqlDollar[1].str)
			stmt.Expr = lx.readSQLExpr()
			plpgsqlLOCAL = stmt
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 30:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql.y:347
		{
			plpgsqlVAL.str = plpgsqlDollar[1].str
		}
	case 31:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql.y:351
		{
			plpgsqlVAL.str = plpgsqlDollar[1].str
		}
	case 32:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql.y:358
		{
			plpgsqlVAL.str = ""
		}
	case 33:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql.y:362
		{
			plpgsqlVAL.str = plpgsqlDollar[2].str
		}
	case 34:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql.y:369
		{
			plpgsqlVAL.str = ""
		}
	case 35:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql.y:373
		{
			plpgsqlVAL.str = plpgsqlDollar[1].str
		}
	case 36:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql.y:380
		{
			plpgsqlVAL.str = plpgsqlDollar[1].str
		}
	case 37:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql.y:384
		{
			plpgsqlVAL.str = plpgsqlDollar[1].str
		}
	}
	goto plpgsqlstack /* stack new state and value */
}
