// Code generated by goyacc -f -p plpgsql -o plpgsql.go plpgsql.y. DO NOT EDIT.

//line plpgsql.y:2
// PostgreSQL Database Management System
// (also known as Postgres, formerly known as Postgres95)
//
//  Portions Copyright (c) 2025, Supabase, Inc
//
//  Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group
//
//  Portions Copyright (c) 1994, The Regents of the University of California
//
// Permission to use, copy, modify, and distribute this software and its
// documentation for any purpose, without fee, and without a written agreement
// is hereby granted, provided that the above copyright notice and this
// paragraph and the following two paragraphs appear in all copies.
//
// IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
// DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
// LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS
// DOCUMENTATION, EVEN IF THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE
// POSSIBILITY OF SUCH DAMAGE.
//
// THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
// AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
// ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATIONS TO
// PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.

// Ported from postgres/src/pl/plpgsql/src/pl_gram.y. Currently only the
// scaffolding: the grammar accepts an empty body and produces an empty
// PLpgSQL_function root node. Statement productions (block, DECLARE, IF,
// LOOP, FOR, EXECSQL, DYNEXECUTE, …) are added incrementally as the grammar
// is ported.

package plpgsql

import (
	"fmt"
	__yyfmt__ "fmt"
	__yyunsafe__ "unsafe"

	"github.com/multigres/multigres/go/common/parser/ast/plpgsqlast" //line plpgsql.y:34
)

// plpgsqlResultSetter is accessed via type assertion on the lexer so actions
// can publish the parsed function without depending on a concrete lexer type.
type plpgsqlResultSetter interface {
	SetResult(*plpgsqlast.PLpgSQL_function)
}

const (
	IDENT                  = 57346
	UIDENT                 = 57347
	FCONST                 = 57348
	SCONST                 = 57349
	USCONST                = 57350
	BCONST                 = 57351
	XCONST                 = 57352
	Op                     = 57353
	ICONST                 = 57354
	PARAM                  = 57355
	TYPECAST               = 57356
	DOT_DOT                = 57357
	COLON_EQUALS           = 57358
	EQUALS_GREATER         = 57359
	LESS_EQUALS            = 57360
	GREATER_EQUALS         = 57361
	NOT_EQUALS             = 57362
	T_WORD                 = 57363
	T_CWORD                = 57364
	T_DATUM                = 57365
	LESS_LESS              = 57366
	GREATER_GREATER        = 57367
	K_ABSOLUTE             = 57368
	K_ALIAS                = 57369
	K_ALL                  = 57370
	K_AND                  = 57371
	K_ARRAY                = 57372
	K_ASSERT               = 57373
	K_BACKWARD             = 57374
	K_BEGIN                = 57375
	K_BY                   = 57376
	K_CALL                 = 57377
	K_CASE                 = 57378
	K_CHAIN                = 57379
	K_CLOSE                = 57380
	K_COLLATE              = 57381
	K_COLUMN               = 57382
	K_COLUMN_NAME          = 57383
	K_COMMIT               = 57384
	K_CONSTANT             = 57385
	K_CONSTRAINT           = 57386
	K_CONSTRAINT_NAME      = 57387
	K_CONTINUE             = 57388
	K_CURRENT              = 57389
	K_CURSOR               = 57390
	K_DATATYPE             = 57391
	K_DEBUG                = 57392
	K_DECLARE              = 57393
	K_DEFAULT              = 57394
	K_DETAIL               = 57395
	K_DIAGNOSTICS          = 57396
	K_DO                   = 57397
	K_DUMP                 = 57398
	K_ELSE                 = 57399
	K_ELSIF                = 57400
	K_END                  = 57401
	K_ERRCODE              = 57402
	K_ERROR                = 57403
	K_EXCEPTION            = 57404
	K_EXECUTE              = 57405
	K_EXIT                 = 57406
	K_FETCH                = 57407
	K_FIRST                = 57408
	K_FOR                  = 57409
	K_FOREACH              = 57410
	K_FORWARD              = 57411
	K_FROM                 = 57412
	K_GET                  = 57413
	K_HINT                 = 57414
	K_IF                   = 57415
	K_IMPORT               = 57416
	K_IN                   = 57417
	K_INFO                 = 57418
	K_INSERT               = 57419
	K_INTO                 = 57420
	K_IS                   = 57421
	K_LAST                 = 57422
	K_LOG                  = 57423
	K_LOOP                 = 57424
	K_MERGE                = 57425
	K_MESSAGE              = 57426
	K_MESSAGE_TEXT         = 57427
	K_MOVE                 = 57428
	K_NEXT                 = 57429
	K_NO                   = 57430
	K_NOT                  = 57431
	K_NOTICE               = 57432
	K_NULL                 = 57433
	K_OPEN                 = 57434
	K_OPTION               = 57435
	K_OR                   = 57436
	K_PERFORM              = 57437
	K_PG_CONTEXT           = 57438
	K_PG_DATATYPE_NAME     = 57439
	K_PG_EXCEPTION_CONTEXT = 57440
	K_PG_EXCEPTION_DETAIL  = 57441
	K_PG_EXCEPTION_HINT    = 57442
	K_PG_ROUTINE_OID       = 57443
	K_PRINT_STRICT_PARAMS  = 57444
	K_PRIOR                = 57445
	K_QUERY                = 57446
	K_RAISE                = 57447
	K_RELATIVE             = 57448
	K_RETURN               = 57449
	K_RETURNED_SQLSTATE    = 57450
	K_REVERSE              = 57451
	K_ROLLBACK             = 57452
	K_ROW_COUNT            = 57453
	K_ROWTYPE              = 57454
	K_SCHEMA               = 57455
	K_SCHEMA_NAME          = 57456
	K_SCROLL               = 57457
	K_SLICE                = 57458
	K_SQLSTATE             = 57459
	K_STACKED              = 57460
	K_STRICT               = 57461
	K_TABLE                = 57462
	K_TABLE_NAME           = 57463
	K_THEN                 = 57464
	K_TO                   = 57465
	K_TYPE                 = 57466
	K_USE_COLUMN           = 57467
	K_USE_VARIABLE         = 57468
	K_USING                = 57469
	K_VARIABLE_CONFLICT    = 57470
	K_WARNING              = 57471
	K_WHEN                 = 57472
	K_WHILE                = 57473
)

var plpgsqlToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"IDENT",
	"UIDENT",
	"FCONST",
	"SCONST",
	"USCONST",
	"BCONST",
	"XCONST",
	"Op",
	"ICONST",
	"PARAM",
	"TYPECAST",
	"DOT_DOT",
	"COLON_EQUALS",
	"EQUALS_GREATER",
	"LESS_EQUALS",
	"GREATER_EQUALS",
	"NOT_EQUALS",
	"T_WORD",
	"T_CWORD",
	"T_DATUM",
	"LESS_LESS",
	"GREATER_GREATER",
	"K_ABSOLUTE",
	"K_ALIAS",
	"K_ALL",
	"K_AND",
	"K_ARRAY",
	"K_ASSERT",
	"K_BACKWARD",
	"K_BEGIN",
	"K_BY",
	"K_CALL",
	"K_CASE",
	"K_CHAIN",
	"K_CLOSE",
	"K_COLLATE",
	"K_COLUMN",
	"K_COLUMN_NAME",
	"K_COMMIT",
	"K_CONSTANT",
	"K_CONSTRAINT",
	"K_CONSTRAINT_NAME",
	"K_CONTINUE",
	"K_CURRENT",
	"K_CURSOR",
	"K_DATATYPE",
	"K_DEBUG",
	"K_DECLARE",
	"K_DEFAULT",
	"K_DETAIL",
	"K_DIAGNOSTICS",
	"K_DO",
	"K_DUMP",
	"K_ELSE",
	"K_ELSIF",
	"K_END",
	"K_ERRCODE",
	"K_ERROR",
	"K_EXCEPTION",
	"K_EXECUTE",
	"K_EXIT",
	"K_FETCH",
	"K_FIRST",
	"K_FOR",
	"K_FOREACH",
	"K_FORWARD",
	"K_FROM",
	"K_GET",
	"K_HINT",
	"K_IF",
	"K_IMPORT",
	"K_IN",
	"K_INFO",
	"K_INSERT",
	"K_INTO",
	"K_IS",
	"K_LAST",
	"K_LOG",
	"K_LOOP",
	"K_MERGE",
	"K_MESSAGE",
	"K_MESSAGE_TEXT",
	"K_MOVE",
	"K_NEXT",
	"K_NO",
	"K_NOT",
	"K_NOTICE",
	"K_NULL",
	"K_OPEN",
	"K_OPTION",
	"K_OR",
	"K_PERFORM",
	"K_PG_CONTEXT",
	"K_PG_DATATYPE_NAME",
	"K_PG_EXCEPTION_CONTEXT",
	"K_PG_EXCEPTION_DETAIL",
	"K_PG_EXCEPTION_HINT",
	"K_PG_ROUTINE_OID",
	"K_PRINT_STRICT_PARAMS",
	"K_PRIOR",
	"K_QUERY",
	"K_RAISE",
	"K_RELATIVE",
	"K_RETURN",
	"K_RETURNED_SQLSTATE",
	"K_REVERSE",
	"K_ROLLBACK",
	"K_ROW_COUNT",
	"K_ROWTYPE",
	"K_SCHEMA",
	"K_SCHEMA_NAME",
	"K_SCROLL",
	"K_SLICE",
	"K_SQLSTATE",
	"K_STACKED",
	"K_STRICT",
	"K_TABLE",
	"K_TABLE_NAME",
	"K_THEN",
	"K_TO",
	"K_TYPE",
	"K_USE_COLUMN",
	"K_USE_VARIABLE",
	"K_USING",
	"K_VARIABLE_CONFLICT",
	"K_WARNING",
	"K_WHEN",
	"K_WHILE",
	"';'",
	"'('",
	"')'",
	"','",
	"'='",
}

var plpgsqlStatenames = [...]string{}

const (
	plpgsqlEofCode          = 1
	plpgsqlErrCode          = 2
	plpgsqlInitialStackSize = 16
)

//line plpgsql.y:1483

//line yacctab:1
var plpgsqlExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
	-1, 96,
	33, 144,
	51, 144,
	59, 102,
	-2, 142,
	-1, 101,
	48, 19,
	-2, 30,
	-1, 206,
	33, 144,
	51, 144,
	57, 113,
	58, 113,
	59, 113,
	-2, 142,
	-1, 208,
	33, 144,
	51, 144,
	-2, 142,
	-1, 221,
	33, 145,
	51, 145,
	-2, 143,
	-1, 264,
	33, 144,
	51, 144,
	59, 106,
	130, 106,
	-2, 142,
	-1, 278,
	33, 144,
	51, 144,
	59, 133,
	-2, 142,
	-1, 279,
	33, 144,
	51, 144,
	57, 131,
	59, 131,
	130, 131,
	-2, 142,
	-1, 294,
	33, 144,
	51, 144,
	59, 116,
	-2, 142,
	-1, 300,
	33, 144,
	51, 144,
	57, 114,
	58, 114,
	59, 114,
	-2, 142,
}

const plpgsqlPrivate = 57344

const plpgsqlLast = 823

var plpgsqlAct = [...]int{
	207, 208, 209, 186, 262, 185, 179, 189, 235, 11,
	96, 268, 196, 101, 13, 216, 211, 168, 165, 176,
	170, 270, 270, 287, 288, 182, 183, 266, 254, 256,
	267, 229, 304, 14, 15, 303, 16, 17, 18, 19,
	180, 220, 20, 219, 21, 22, 23, 24, 25, 26,
	27, 28, 29, 30, 31, 32, 33, 34, 284, 35,
	36, 37, 38, 39, 301, 40, 257, 41, 42, 43,
	233, 44, 45, 46, 205, 202, 47, 200, 48, 49,
	187, 50, 167, 51, 52, 7, 53, 54, 55, 181,
	56, 57, 58, 59, 60, 61, 217, 62, 249, 63,
	64, 101, 65, 66, 67, 68, 69, 70, 71, 72,
	73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
	83, 84, 85, 86, 87, 88, 166, 89, 90, 158,
	231, 91, 92, 93, 246, 94, 95, 174, 281, 192,
	285, 269, 269, 98, 253, 160, 203, 274, 232, 260,
	275, 244, 299, 190, 292, 277, 163, 188, 230, 201,
	172, 259, 171, 273, 272, 10, 191, 178, 223, 193,
	197, 217, 239, 297, 8, 296, 177, 221, 102, 5,
	169, 206, 276, 194, 237, 238, 212, 213, 198, 199,
	161, 106, 2, 282, 258, 9, 6, 204, 149, 4,
	214, 245, 151, 184, 218, 226, 251, 215, 175, 240,
	242, 243, 291, 236, 234, 173, 120, 162, 119, 118,
	117, 116, 115, 114, 250, 113, 112, 111, 110, 109,
	108, 248, 264, 263, 107, 197, 210, 126, 255, 125,
	124, 156, 127, 123, 265, 122, 121, 128, 104, 247,
	271, 278, 279, 222, 224, 261, 228, 159, 252, 157,
	286, 280, 99, 97, 283, 195, 164, 103, 3, 1,
	0, 289, 0, 0, 0, 294, 290, 0, 0, 293,
	295, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 263, 298, 0, 300, 225, 227, 0, 302,
	0, 14, 15, 305, 16, 17, 18, 19, 0, 0,
	20, 0, 21, 22, 23, 24, 25, 26, 27, 28,
	29, 30, 31, 32, 33, 34, 0, 35, 36, 37,
	38, 39, 0, 40, 0, 41, 42, 43, 0, 44,
	45, 46, 0, 0, 47, 0, 48, 49, 0, 50,
	0, 51, 52, 0, 53, 54, 55, 0, 56, 57,
	58, 59, 60, 61, 0, 62, 0, 63, 64, 0,
	65, 66, 67, 68, 69, 70, 71, 72, 73, 74,
	75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
	85, 86, 87, 88, 0, 89, 90, 0, 0, 91,
	92, 93, 12, 94, 95, 0, 0, 14, 15, 0,
	16, 17, 18, 19, 0, 0, 20, 0, 21, 22,
	23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
	33, 34, 100, 35, 36, 37, 38, 39, 0, 40,
	0, 41, 42, 43, 0, 44, 45, 46, 0, 0,
	47, 0, 48, 49, 0, 50, 0, 51, 52, 0,
	53, 54, 55, 0, 56, 57, 58, 59, 60, 61,
	0, 62, 0, 63, 64, 0, 65, 66, 67, 68,
	69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
	79, 80, 81, 82, 83, 84, 85, 86, 87, 88,
	0, 89, 90, 0, 0, 91, 92, 93, 12, 94,
	95, 0, 0, 14, 15, 0, 16, 17, 18, 19,
	0, 0, 20, 0, 21, 22, 23, 24, 25, 26,
	27, 28, 29, 30, 31, 32, 33, 34, 0, 35,
	36, 37, 38, 39, 0, 40, 0, 41, 42, 43,
	0, 44, 45, 46, 0, 0, 47, 0, 48, 49,
	0, 50, 0, 51, 52, 0, 53, 54, 55, 0,
	56, 57, 58, 59, 60, 61, 0, 62, 0, 63,
	64, 0, 65, 66, 67, 68, 69, 70, 71, 72,
	73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
	83, 84, 85, 86, 87, 88, 0, 89, 90, 0,
	0, 91, 92, 93, 0, 94, 95, 132, 133, 0,
	153, 0, 0, 0, 0, 0, 0, 144, 0, 0,
	0, 135, 150, 0, 142, 0, 0, 0, 146, 0,
	0, 0, 155, 0, 0, 0, 0, 0, 0, 0,
	0, 136, 0, 0, 0, 241, 0, 0, 0, 138,
	154, 140, 0, 0, 0, 0, 0, 145, 0, 148,
	129, 0, 0, 130, 0, 132, 133, 0, 153, 131,
	0, 0, 141, 0, 0, 144, 0, 152, 139, 135,
	150, 134, 142, 0, 0, 0, 146, 0, 0, 0,
	155, 143, 0, 137, 0, 0, 147, 0, 0, 136,
	0, 0, 0, 0, 0, 0, 105, 138, 154, 140,
	0, 0, 0, 0, 0, 145, 0, 148, 129, 0,
	0, 130, 0, 132, 133, 0, 153, 131, 0, 0,
	141, 0, 0, 144, 0, 152, 139, 135, 150, 134,
	142, 0, 0, 0, 146, 0, 0, 0, 155, 143,
	0, 137, 0, 0, 147, 0, 0, 136, 0, 0,
	0, 0, 0, 0, 0, 138, 154, 140, 0, 0,
	0, 0, 0, 145, 0, 148, 129, 0, 0, 130,
	0, 0, 0, 0, 0, 131, 0, 0, 141, 0,
	0, 0, 0, 152, 139, 0, 0, 134, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 143, 0, 137,
	0, 0, 147,
}

var plpgsqlPact = [...]int{
	155, -1000, -47, 141, 114, 487, -1000, -1000, -1000, 381,
	-1000, 153, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, 654, 381, -1000, -1000,
	-1000, 102, -1000, 97, -1000, -4, -50, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 159,
	-1000, -1000, 159, -1000, -1000, 90, 147, 147, -1000, -42,
	-1000, 487, -52, 487, -1000, -1000, -1000, -1000, 86, 118,
	-1000, 24, -1000, 487, -4, -1000, 487, -1000, -1000, -1000,
	159, 159, -55, 105, -1000, -1000, -57, 109, -58, -1000,
	-1000, -1000, 165, 165, -34, -89, -1000, -1000, 152, 129,
	275, -102, -1000, -1000, -1000, 36, -1000, -1000, 70, -62,
	-1000, 163, -1000, -1000, 135, -1000, 712, -1000, 596, -1000,
	-1000, 76, -1000, -1000, 18, 41, -1000, -1000, -1000, -1000,
	-1000, -1000, 55, 7, -66, -1000, -1000, -1000, 82, 487,
	-1000, 487, -1000, -1000, -105, -1000, 5, -1000, -1000, -1000,
	106, 65, -1000, -1000, -1000, 75, 170, 96, -1000, -1000,
	-1000, -1000, 6, 49, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -111, -1000, -1000, 712, -1000, -1000, 163, -1000, -1000,
	-1000, 95, -1000, -1000, 487, 145, -1000, 137, 712, 712,
	-1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, 487, -1000,
	-1000, -1000, 79, -1000, 712, -68, -1000, -97, -1000, -100,
	712, -1000, -1000, -1000, -1000, -1000,
}

var plpgsqlPgo = [...]int{
	0, 269, 191, 268, 267, 266, 18, 265, 12, 263,
	143, 262, 7, 261, 260, 259, 258, 257, 256, 255,
	4, 254, 253, 1, 250, 249, 248, 247, 246, 245,
	243, 242, 240, 239, 237, 236, 234, 230, 229, 228,
	227, 226, 225, 223, 222, 221, 220, 219, 218, 216,
	215, 19, 214, 8, 213, 212, 20, 17, 209, 207,
	15, 0, 206, 6, 2, 204, 203, 202, 201, 199,
	198, 5, 3, 14, 16, 196, 195, 194, 193, 11,
}

//line plpgsql.y:1483
type plpgsqlSymType struct {
	union    any
	str      string
	ival     int
	location int
	yys      int
}

func (st *plpgsqlSymType) blockUnion() *plpgsqlast.PLpgSQL_stmt_block {
	v, _ := st.union.(*plpgsqlast.PLpgSQL_stmt_block)
	return v
}

func (st *plpgsqlSymType) bvalUnion() bool {
	v, _ := st.union.(bool)
	return v
}

func (st *plpgsqlSymType) casewhenUnion() *plpgsqlast.PLpgSQL_case_when {
	v, _ := st.union.(*plpgsqlast.PLpgSQL_case_when)
	return v
}

func (st *plpgsqlSymType) casewhensUnion() []*plpgsqlast.PLpgSQL_case_when {
	v, _ := st.union.([]*plpgsqlast.PLpgSQL_case_when)
	return v
}

func (st *plpgsqlSymType) condUnion() *plpgsqlast.PLpgSQL_condition {
	v, _ := st.union.(*plpgsqlast.PLpgSQL_condition)
	return v
}

func (st *plpgsqlSymType) condsUnion() []*plpgsqlast.PLpgSQL_condition {
	v, _ := st.union.([]*plpgsqlast.PLpgSQL_condition)
	return v
}

func (st *plpgsqlSymType) cursorargsUnion() []*plpgsqlast.PLpgSQL_var {
	v, _ := st.union.([]*plpgsqlast.PLpgSQL_var)
	return v
}

func (st *plpgsqlSymType) cvarUnion() *plpgsqlast.PLpgSQL_var {
	v, _ := st.union.(*plpgsqlast.PLpgSQL_var)
	return v
}

func (st *plpgsqlSymType) datumUnion() plpgsqlast.Datum {
	v, _ := st.union.(plpgsqlast.Datum)
	return v
}

func (st *plpgsqlSymType) datumsUnion() []plpgsqlast.Datum {
	v, _ := st.union.([]plpgsqlast.Datum)
	return v
}

func (st *plpgsqlSymType) declsectUnion() declSect {
	v, _ := st.union.(declSect)
	return v
}

func (st *plpgsqlSymType) diagitemUnion() *plpgsqlast.PLpgSQL_diag_item {
	v, _ := st.union.(*plpgsqlast.PLpgSQL_diag_item)
	return v
}

func (st *plpgsqlSymType) diagitemsUnion() []*plpgsqlast.PLpgSQL_diag_item {
	v, _ := st.union.([]*plpgsqlast.PLpgSQL_diag_item)
	return v
}

func (st *plpgsqlSymType) elsifsUnion() []*plpgsqlast.PLpgSQL_if_elsif {
	v, _ := st.union.([]*plpgsqlast.PLpgSQL_if_elsif)
	return v
}

func (st *plpgsqlSymType) excUnion() *plpgsqlast.PLpgSQL_exception {
	v, _ := st.union.(*plpgsqlast.PLpgSQL_exception)
	return v
}

func (st *plpgsqlSymType) excblockUnion() *plpgsqlast.PLpgSQL_exception_block {
	v, _ := st.union.(*plpgsqlast.PLpgSQL_exception_block)
	return v
}

func (st *plpgsqlSymType) excsUnion() []*plpgsqlast.PLpgSQL_exception {
	v, _ := st.union.([]*plpgsqlast.PLpgSQL_exception)
	return v
}

func (st *plpgsqlSymType) exprUnion() *plpgsqlast.PLpgSQL_expr {
	v, _ := st.union.(*plpgsqlast.PLpgSQL_expr)
	return v
}

func (st *plpgsqlSymType) fetchUnion() *plpgsqlast.PLpgSQL_stmt_fetch {
	v, _ := st.union.(*plpgsqlast.PLpgSQL_stmt_fetch)
	return v
}

func (st *plpgsqlSymType) forvarUnion() forVariable {
	v, _ := st.union.(forVariable)
	return v
}

func (st *plpgsqlSymType) functionUnion() *plpgsqlast.PLpgSQL_function {
	v, _ := st.union.(*plpgsqlast.PLpgSQL_function)
	return v
}

func (st *plpgsqlSymType) loopbodyUnion() loopBody {
	v, _ := st.union.(loopBody)
	return v
}

func (st *plpgsqlSymType) stmtUnion() plpgsqlast.Stmt {
	v, _ := st.union.(plpgsqlast.Stmt)
	return v
}

func (st *plpgsqlSymType) stmtsUnion() []plpgsqlast.Stmt {
	v, _ := st.union.([]plpgsqlast.Stmt)
	return v
}

func (st *plpgsqlSymType) typUnion() *plpgsqlast.PLpgSQL_type {
	v, _ := st.union.(*plpgsqlast.PLpgSQL_type)
	return v
}

var plpgsqlR1 = [...]int{
	0, 1, 75, 75, 2, 3, 3, 3, 76, 9,
	9, 10, 10, 11, 11, 11, 21, 21, 21, 17,
	17, 17, 18, 18, 19, 19, 20, 77, 77, 14,
	15, 15, 12, 22, 22, 22, 22, 16, 16, 13,
	13, 78, 78, 79, 79, 23, 23, 26, 26, 26,
	26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
	26, 26, 26, 26, 26, 26, 26, 26, 26, 26,
	27, 36, 36, 36, 36, 36, 37, 38, 38, 39,
	40, 41, 42, 43, 44, 45, 46, 47, 50, 50,
	50, 52, 52, 53, 54, 54, 55, 48, 49, 51,
	51, 51, 4, 4, 5, 5, 6, 7, 7, 8,
	56, 57, 28, 58, 58, 24, 24, 29, 30, 61,
	32, 35, 74, 74, 33, 68, 68, 34, 66, 59,
	59, 60, 25, 25, 31, 67, 67, 65, 65, 62,
	63, 64, 70, 70, 69, 69, 71, 71, 72, 72,
	73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
	73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
	73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
	73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
	73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
	73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
	73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
	73, 73, 73, 73, 73, 73, 73, 73, 73, 73,
	73, 73,
}

var plpgsqlR2 = [...]int{
	0, 2, 0, 1, 6, 1, 2, 3, 1, 2,
	1, 1, 1, 6, 5, 6, 1, 1, 1, 0,
	2, 1, 0, 3, 1, 3, 2, 1, 1, 0,
	0, 1, 0, 0, 2, 2, 2, 0, 2, 1,
	1, 1, 1, 1, 1, 0, 2, 2, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 2, 4, 4, 3, 1, 1, 5, 0, 1,
	1, 3, 1, 3, 1, 1, 0, 3, 3, 2,
	3, 0, 0, 2, 2, 1, 4, 3, 1, 1,
	0, 1, 8, 0, 4, 0, 2, 3, 4, 5,
	4, 2, 1, 1, 8, 0, 2, 7, 0, 2,
	1, 3, 0, 2, 3, 1, 1, 1, 2, 0,
	0, 0, 0, 3, 0, 3, 0, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1,
}

var plpgsqlChk = [...]int{
	-1000, -1, -2, -3, -69, 24, -75, 132, 33, -76,
	51, -72, 21, -73, 26, 27, 29, 30, 31, 32,
	35, 37, 38, 39, 40, 41, 42, 43, 44, 45,
	46, 47, 48, 49, 50, 52, 53, 54, 55, 56,
	58, 60, 61, 62, 64, 65, 66, 69, 71, 72,
	74, 76, 77, 79, 80, 81, 83, 84, 85, 86,
	87, 88, 90, 92, 93, 95, 96, 97, 98, 99,
	100, 101, 102, 103, 104, 105, 106, 107, 108, 109,
	110, 111, 112, 113, 114, 115, 116, 117, 118, 120,
	121, 124, 125, 126, 128, 129, -23, -9, -10, -11,
	51, -72, 25, -4, -26, 62, -2, -36, -37, -38,
	-39, -40, -41, -42, -43, -44, -45, -46, -47, -48,
	-49, -28, -29, -30, -32, -33, -34, -31, -27, 74,
	77, 83, 21, 22, 95, 35, 55, 107, 63, 92,
	65, 86, 38, 105, 31, 71, 42, 110, 73, -70,
	36, -67, 91, 24, 64, 46, -10, -15, 27, -17,
	43, 88, 115, 59, -5, -6, 130, 132, -57, 21,
	-56, -56, -57, -50, 47, 118, -51, 29, -51, -63,
	82, 131, 67, 68, -66, -71, -72, 132, -72, -12,
	67, 48, 115, -71, -6, -7, -8, -72, -57, -57,
	132, 54, 132, 37, 88, 132, -23, -61, -23, -64,
	-35, -74, 21, 22, -74, -59, -60, 130, -65, 132,
	130, 25, -22, 39, -21, 21, -73, 22, -18, 133,
	122, 94, 78, 132, -52, -53, -54, 21, 22, 37,
	-58, 59, -61, -61, 75, -68, 116, -25, -60, 57,
	-63, -62, -16, 89, 21, -73, 22, 132, -77, 79,
	67, -19, -20, -72, -23, -8, 132, 135, -79, 136,
	16, -24, 58, 57, 82, 75, 12, 59, -23, -23,
	-13, 132, -78, -79, 52, 91, -14, 134, 135, -12,
	-53, -55, 59, -63, -23, -71, 30, 36, -20, 73,
	-23, 132, -64, 132, 132, -61,
}

var plpgsqlDef = [...]int{
	144, -2, 2, 0, 5, 0, 1, 3, 45, 6,
	8, 0, 148, 149, 150, 151, 152, 153, 154, 155,
	156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
	166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
	176, 177, 178, 179, 180, 181, 182, 183, 184, 185,
	186, 187, 188, 189, 190, 191, 192, 193, 194, 195,
	196, 197, 198, 199, 200, 201, 202, 203, 204, 205,
	206, 207, 208, 209, 210, 211, 212, 213, 214, 215,
	216, 217, 218, 219, 220, 221, 222, 223, 224, 225,
	226, 227, 228, 229, 230, 231, -2, 7, 10, 11,
	12, -2, 145, 0, 46, 0, 0, 48, 49, 50,
	51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
	61, 62, 63, 64, 65, 66, 67, 68, 69, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 0,
	110, 110, 0, 85, 86, 88, 101, 101, 140, 0,
	128, 146, 0, 0, 135, 136, 9, 32, 0, 0,
	31, 0, 21, 146, 103, 105, 0, 47, 81, 111,
	0, 0, 0, 0, 89, 90, 0, 0, 0, 45,
	45, 141, 0, 0, 0, 0, 147, 70, 0, 33,
	0, 22, 20, 4, 104, 0, 108, 109, 0, 0,
	84, 0, 97, 99, 0, 98, -2, 117, -2, 45,
	45, 0, 122, 123, 125, 132, 130, 140, 134, 137,
	139, -2, 37, 0, 0, 16, 17, 18, 0, 0,
	45, 0, 82, 83, 0, 92, 0, 94, 95, 100,
	115, 0, 118, 120, 121, 0, 0, 0, 129, 45,
	45, 138, 0, 0, 34, 35, 36, 14, 29, 27,
	28, 0, 24, 32, -2, 107, 87, 0, 96, 43,
	44, 0, 140, 45, 146, 0, 126, 0, -2, -2,
	13, 39, 40, 41, 42, 38, 15, 23, 0, 26,
	91, 93, 0, 45, -2, 0, 141, 0, 25, 0,
	-2, 119, 45, 127, 112, 124,
}

var plpgsqlTok1 = [...]int{
	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	133, 134, 3, 3, 135, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 132,
	3, 136,
}

var plpgsqlTok2 = [...]int{
	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
	62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
	72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
	82, 83, 84, 85, 86, 87, 88, 89, 90, 91,
	92, 93, 94, 95, 96, 97, 98, 99, 100, 101,
	102, 103, 104, 105, 106, 107, 108, 109, 110, 111,
	112, 113, 114, 115, 116, 117, 118, 119, 120, 121,
	122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
}

var plpgsqlTok3 = [...]int{
	0,
}

var plpgsqlErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

func plpgsqlIaddr(v any) __yyunsafe__.Pointer {
	type h struct {
		t __yyunsafe__.Pointer
		p __yyunsafe__.Pointer
	}
	return (*h)(__yyunsafe__.Pointer(&v)).p
}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	plpgsqlDebug        = 0
	plpgsqlErrorVerbose = false
)

type plpgsqlLexer interface {
	Lex(lval *plpgsqlSymType) int
	Error(s string)
}

type plpgsqlParser interface {
	Parse(plpgsqlLexer) int
	Lookahead() int
}

type plpgsqlParserImpl struct {
	lval  plpgsqlSymType
	stack [plpgsqlInitialStackSize]plpgsqlSymType
	char  int
}

func (p *plpgsqlParserImpl) Lookahead() int {
	return p.char
}

func plpgsqlNewParser() plpgsqlParser {
	return &plpgsqlParserImpl{}
}

const plpgsqlFlag = -1000

func plpgsqlTokname(c int) string {
	if c >= 1 && c-1 < len(plpgsqlToknames) {
		if plpgsqlToknames[c-1] != "" {
			return plpgsqlToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func plpgsqlStatname(s int) string {
	if s >= 0 && s < len(plpgsqlStatenames) {
		if plpgsqlStatenames[s] != "" {
			return plpgsqlStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func plpgsqlErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !plpgsqlErrorVerbose {
		return "syntax error"
	}

	for _, e := range plpgsqlErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + plpgsqlTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := plpgsqlPact[state]
	for tok := TOKSTART; tok-1 < len(plpgsqlToknames); tok++ {
		if n := base + tok; n >= 0 && n < plpgsqlLast && plpgsqlChk[plpgsqlAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if plpgsqlDef[state] == -2 {
		i := 0
		for plpgsqlExca[i] != -1 || plpgsqlExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; plpgsqlExca[i] >= 0; i += 2 {
			tok := plpgsqlExca[i]
			if tok < TOKSTART || plpgsqlExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if plpgsqlExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += plpgsqlTokname(tok)
	}
	return res
}

func plpgsqllex1(lex plpgsqlLexer, lval *plpgsqlSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = plpgsqlTok1[0]
		goto out
	}
	if char < len(plpgsqlTok1) {
		token = plpgsqlTok1[char]
		goto out
	}
	if char >= plpgsqlPrivate {
		if char < plpgsqlPrivate+len(plpgsqlTok2) {
			token = plpgsqlTok2[char-plpgsqlPrivate]
			goto out
		}
	}
	for i := 0; i < len(plpgsqlTok3); i += 2 {
		token = plpgsqlTok3[i+0]
		if token == char {
			token = plpgsqlTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = plpgsqlTok2[1] /* unknown char */
	}
	if plpgsqlDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", plpgsqlTokname(token), uint(char))
	}
	return char, token
}

func plpgsqlParse(plpgsqllex plpgsqlLexer) int {
	return plpgsqlNewParser().Parse(plpgsqllex)
}

func (plpgsqlrcvr *plpgsqlParserImpl) Parse(plpgsqllex plpgsqlLexer) int {
	var plpgsqln int
	var plpgsqlVAL plpgsqlSymType
	var plpgsqlDollar []plpgsqlSymType
	_ = plpgsqlDollar // silence set and not used
	plpgsqlS := plpgsqlrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	plpgsqlstate := 0
	plpgsqlrcvr.char = -1
	plpgsqltoken := -1 // plpgsqlrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		plpgsqlstate = -1
		plpgsqlrcvr.char = -1
		plpgsqltoken = -1
	}()
	plpgsqlp := -1
	goto plpgsqlstack

ret0:
	return 0

ret1:
	return 1

plpgsqlstack:
	/* put a state and value onto the stack */
	if plpgsqlDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", plpgsqlTokname(plpgsqltoken), plpgsqlStatname(plpgsqlstate))
	}

	plpgsqlp++
	if plpgsqlp >= len(plpgsqlS) {
		nyys := make([]plpgsqlSymType, len(plpgsqlS)*2)
		copy(nyys, plpgsqlS)
		plpgsqlS = nyys
	}
	plpgsqlS[plpgsqlp] = plpgsqlVAL
	plpgsqlS[plpgsqlp].yys = plpgsqlstate

plpgsqlnewstate:
	plpgsqln = plpgsqlPact[plpgsqlstate]
	if plpgsqln <= plpgsqlFlag {
		goto plpgsqldefault /* simple state */
	}
	if plpgsqlrcvr.char < 0 {
		plpgsqlrcvr.char, plpgsqltoken = plpgsqllex1(plpgsqllex, &plpgsqlrcvr.lval)
	}
	plpgsqln += plpgsqltoken
	if plpgsqln < 0 || plpgsqln >= plpgsqlLast {
		goto plpgsqldefault
	}
	plpgsqln = plpgsqlAct[plpgsqln]
	if plpgsqlChk[plpgsqln] == plpgsqltoken { /* valid shift */
		plpgsqlrcvr.char = -1
		plpgsqltoken = -1
		plpgsqlVAL = plpgsqlrcvr.lval
		plpgsqlstate = plpgsqln
		if Errflag > 0 {
			Errflag--
		}
		goto plpgsqlstack
	}

plpgsqldefault:
	/* default state action */
	plpgsqln = plpgsqlDef[plpgsqlstate]
	if plpgsqln == -2 {
		if plpgsqlrcvr.char < 0 {
			plpgsqlrcvr.char, plpgsqltoken = plpgsqllex1(plpgsqllex, &plpgsqlrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if plpgsqlExca[xi+0] == -1 && plpgsqlExca[xi+1] == plpgsqlstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			plpgsqln = plpgsqlExca[xi+0]
			if plpgsqln < 0 || plpgsqln == plpgsqltoken {
				break
			}
		}
		plpgsqln = plpgsqlExca[xi+1]
		if plpgsqln < 0 {
			goto ret0
		}
	}
	if plpgsqln == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			plpgsqllex.Error(plpgsqlErrorMessage(plpgsqlstate, plpgsqltoken))
			Nerrs++
			if plpgsqlDebug >= 1 {
				__yyfmt__.Printf("%s", plpgsqlStatname(plpgsqlstate))
				__yyfmt__.Printf(" saw %s\n", plpgsqlTokname(plpgsqltoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for plpgsqlp >= 0 {
				plpgsqln = plpgsqlPact[plpgsqlS[plpgsqlp].yys] + plpgsqlErrCode
				if plpgsqln >= 0 && plpgsqln < plpgsqlLast {
					plpgsqlstate = plpgsqlAct[plpgsqln] /* simulate a shift of "error" */
					if plpgsqlChk[plpgsqlstate] == plpgsqlErrCode {
						goto plpgsqlstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if plpgsqlDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", plpgsqlS[plpgsqlp].yys)
				}
				plpgsqlp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if plpgsqlDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", plpgsqlTokname(plpgsqltoken))
			}
			if plpgsqltoken == plpgsqlEofCode {
				goto ret1
			}
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			goto plpgsqlnewstate /* try again in the same state */
		}
	}

	/* reduction by production plpgsqln */
	if plpgsqlDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", plpgsqln, plpgsqlStatname(plpgsqlstate))
	}

	plpgsqlnt := plpgsqln
	plpgsqlpt := plpgsqlp
	_ = plpgsqlpt // guard against "declared and not used"

	plpgsqlp -= plpgsqlR2[plpgsqln]
	// plpgsqlp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if plpgsqlp+1 >= len(plpgsqlS) {
		nyys := make([]plpgsqlSymType, len(plpgsqlS)*2)
		copy(nyys, plpgsqlS)
		plpgsqlS = nyys
	}
	plpgsqlVAL = plpgsqlS[plpgsqlp+1]

	/* consult goto table to find next state */
	plpgsqln = plpgsqlR1[plpgsqln]
	plpgsqlg := plpgsqlPgo[plpgsqln]
	plpgsqlj := plpgsqlg + plpgsqlS[plpgsqlp].yys + 1

	if plpgsqlj >= plpgsqlLast {
		plpgsqlstate = plpgsqlAct[plpgsqlg]
	} else {
		plpgsqlstate = plpgsqlAct[plpgsqlj]
		if plpgsqlChk[plpgsqlstate] != -plpgsqln {
			plpgsqlstate = plpgsqlAct[plpgsqlg]
		}
	}
	// dummy call; replaced with literal code
	switch plpgsqlnt {

	case 1:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql.y:177
		{
			fn := plpgsqlast.NewPLpgSQL_function()
			fn.Action = plpgsqlDollar[1].blockUnion()
			if l, ok := plpgsqllex.(plpgsqlResultSetter); ok {
				l.SetResult(fn)
			}
		}
	case 4:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-6 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_stmt_block
//line plpgsql.y:198
		{
			block := plpgsqlast.NewPLpgSQL_stmt_block()
			block.Label = plpgsqlDollar[1].declsectUnion().label
			block.Decls = plpgsqlDollar[1].declsectUnion().decls
			block.Body = plpgsqlDollar[3].stmtsUnion()
			block.Exceptions = plpgsqlDollar[4].excblockUnion()
			if err := checkLabels(plpgsqlDollar[1].declsectUnion().label, plpgsqlDollar[6].str); err != nil {
				plpgsqllex.Error(err.Error())
			}
			plpgsqlLOCAL = block
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 5:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL declSect
//line plpgsql.y:220
		{
			plpgsqlLOCAL = declSect{label: plpgsqlDollar[1].str}
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 6:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL declSect
//line plpgsql.y:224
		{
			plpgsqlLOCAL = declSect{label: plpgsqlDollar[1].str}
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 7:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
		var plpgsqlLOCAL declSect
//line plpgsql.y:228
		{
			plpgsqlLOCAL = declSect{label: plpgsqlDollar[1].str, decls: plpgsqlDollar[3].datumsUnion()}
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 9:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL []plpgsqlast.Datum
//line plpgsql.y:239
		{
			plpgsqlLOCAL = appendDatum(plpgsqlDollar[1].datumsUnion(), plpgsqlDollar[2].datumUnion())
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 10:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL []plpgsqlast.Datum
//line plpgsql.y:243
		{
			plpgsqlLOCAL = appendDatum(nil, plpgsqlDollar[1].datumUnion())
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 11:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Datum
//line plpgsql.y:250
		{
			plpgsqlLOCAL = plpgsqlDollar[1].datumUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 12:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Datum
//line plpgsql.y:254
		{
			// extra DECLAREs are allowed and ignored, matching PG
			plpgsqlLOCAL = nil
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 13:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-6 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Datum
//line plpgsql.y:270
		{
			v := plpgsqlast.NewPLpgSQL_var(plpgsqlDollar[1].str)
			v.IsConst = plpgsqlDollar[2].bvalUnion()
			v.DataType = plpgsqlDollar[3].typUnion()
			v.Collate = plpgsqlDollar[4].str
			v.NotNull = plpgsqlDollar[5].bvalUnion()
			v.DefaultVal = plpgsqlDollar[6].exprUnion()
			if v.NotNull && v.DefaultVal == nil {
				plpgsqllex.Error(fmt.Sprintf(
					"variable %q must have a default value, since it's declared NOT NULL",
					v.Refname))
			}
			plpgsqlLOCAL = v
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 14:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-5 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Datum
//line plpgsql.y:285
		{
			a := plpgsqlast.NewPLpgSQL_alias(plpgsqlDollar[1].str)
			a.Target = plpgsqlDollar[4].str
			plpgsqlLOCAL = a
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 15:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-6 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Datum
//line plpgsql.y:291
		{
			v := plpgsqlast.NewPLpgSQL_var(plpgsqlDollar[1].str)
			v.CursorOptions = plpgsqlast.CURSOR_OPT_FAST_PLAN | plpgsqlDollar[2].ival
			v.CursorArgs = plpgsqlDollar[4].cursorargsUnion()
			v.CursorExplicitExpr = plpgsqlDollar[6].exprUnion()
			plpgsqlLOCAL = v
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 16:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql.y:307
		{
			plpgsqlVAL.str = plpgsqlDollar[1].str
		}
	case 17:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql.y:311
		{
			plpgsqlVAL.str = plpgsqlDollar[1].str
		}
	case 18:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql.y:315
		{
			plpgsqlVAL.str = plpgsqlDollar[1].str
		}
	case 19:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql.y:327
		{
			plpgsqlVAL.ival = 0
		}
	case 20:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql.y:331
		{
			plpgsqlVAL.ival = plpgsqlast.CURSOR_OPT_NO_SCROLL
		}
	case 21:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql.y:335
		{
			plpgsqlVAL.ival = plpgsqlast.CURSOR_OPT_SCROLL
		}
	case 22:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL []*plpgsqlast.PLpgSQL_var
//line plpgsql.y:342
		{
			plpgsqlLOCAL = nil
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 23:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
		var plpgsqlLOCAL []*plpgsqlast.PLpgSQL_var
//line plpgsql.y:346
		{
			plpgsqlLOCAL = plpgsqlDollar[2].cursorargsUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 24:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL []*plpgsqlast.PLpgSQL_var
//line plpgsql.y:353
		{
			plpgsqlLOCAL = appendCursorArg(nil, plpgsqlDollar[1].cvarUnion())
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 25:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
		var plpgsqlLOCAL []*plpgsqlast.PLpgSQL_var
//line plpgsql.y:357
		{
			plpgsqlLOCAL = appendCursorArg(plpgsqlDollar[1].cursorargsUnion(), plpgsqlDollar[3].cvarUnion())
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 26:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_var
//line plpgsql.y:364
		{
			v := plpgsqlast.NewPLpgSQL_var(plpgsqlDollar[1].str)
			v.DataType = plpgsqlDollar[2].typUnion()
			plpgsqlLOCAL = v
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 29:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_expr
//line plpgsql.y:378
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			q, _ := lx.readSQLConstruct(plpgsqlast.RAW_PARSE_DEFAULT, ';')
			plpgsqlLOCAL = q
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 30:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL bool
//line plpgsql.y:390
		{
			plpgsqlLOCAL = false
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 31:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL bool
//line plpgsql.y:394
		{
			plpgsqlLOCAL = true
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 32:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_type
//line plpgsql.y:401
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.readDatatype()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 33:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql.y:419
		{
			plpgsqlVAL.str = ""
		}
	case 34:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql.y:423
		{
			plpgsqlVAL.str = plpgsqlDollar[2].str
		}
	case 35:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql.y:427
		{
			plpgsqlVAL.str = plpgsqlDollar[2].str
		}
	case 36:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql.y:431
		{
			plpgsqlVAL.str = plpgsqlDollar[2].str
		}
	case 37:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL bool
//line plpgsql.y:438
		{
			plpgsqlLOCAL = false
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 38:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL bool
//line plpgsql.y:442
		{
			plpgsqlLOCAL = true
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 39:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_expr
//line plpgsql.y:449
		{
			plpgsqlLOCAL = nil
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 40:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_expr
//line plpgsql.y:453
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.readSQLExpr()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 45:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL []plpgsqlast.Stmt
//line plpgsql.y:474
		{
			plpgsqlLOCAL = nil
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 46:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL []plpgsqlast.Stmt
//line plpgsql.y:478
		{
			// Mirror PG: don't link NULL statements into the body list.
			if plpgsqlDollar[2].stmtUnion() == nil {
				plpgsqlLOCAL = plpgsqlDollar[1].stmtsUnion()
			} else {
				plpgsqlLOCAL = append(plpgsqlDollar[1].stmtsUnion(), plpgsqlDollar[2].stmtUnion())
			}
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 47:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:490
		{
			plpgsqlLOCAL = plpgsqlDollar[1].blockUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 48:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:494
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 49:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:498
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 50:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:502
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 51:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:506
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 52:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:510
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 53:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:514
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 54:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:518
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 55:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:522
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 56:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:526
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 57:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:530
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 58:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:534
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 59:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:538
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 60:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:542
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 61:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:546
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 62:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:550
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 63:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:554
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 64:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:558
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 65:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:562
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 66:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:566
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 67:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:570
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 68:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:574
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 69:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:578
		{
			plpgsqlLOCAL = plpgsqlDollar[1].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 70:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:585
		{
			// Like PG, we build no node for NULL; it carries no meaning.
			plpgsqlLOCAL = nil
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 71:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:603
		{
			lx := plpgsqllex.(*lexer)
			startPos := plpgsqlDollar[1].location
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			stmt := plpgsqlast.NewPLpgSQL_stmt_execsql()
			stmt.Sqlstmt = makeExpr(lx.scanStmtText(false, startPos), plpgsqlast.RAW_PARSE_DEFAULT)
			plpgsqlLOCAL = stmt
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 72:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:614
		{
			lx := plpgsqllex.(*lexer)
			startPos := plpgsqlDollar[1].location
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			stmt := plpgsqlast.NewPLpgSQL_stmt_execsql()
			stmt.Sqlstmt = makeExpr(lx.scanStmtText(false, startPos), plpgsqlast.RAW_PARSE_DEFAULT)
			plpgsqlLOCAL = stmt
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 73:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:625
		{
			lx := plpgsqllex.(*lexer)
			startPos := plpgsqlDollar[1].location
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			stmt := plpgsqlast.NewPLpgSQL_stmt_execsql()
			stmt.Sqlstmt = makeExpr(lx.scanStmtText(false, startPos), plpgsqlast.RAW_PARSE_DEFAULT)
			plpgsqlLOCAL = stmt
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 74:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:636
		{
			lx := plpgsqllex.(*lexer)
			startPos := plpgsqlDollar[1].location
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.makeWordStmt(plpgsqlDollar[1].str, startPos)
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 75:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:645
		{
			lx := plpgsqllex.(*lexer)
			startPos := plpgsqlDollar[1].location
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.makeWordStmt(plpgsqlDollar[1].str, startPos)
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 76:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:663
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			stmt := plpgsqlast.NewPLpgSQL_stmt_perform()
			stmt.Expr, _ = lx.readSQLConstruct(plpgsqlast.RAW_PARSE_DEFAULT, ';')
			plpgsqlLOCAL = stmt
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 77:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:680
		{
			lx := plpgsqllex.(*lexer)
			startPos := plpgsqlDollar[1].location
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			stmt := plpgsqlast.NewPLpgSQL_stmt_call(true)
			stmt.Expr = makeExpr(lx.scanStmtText(false, startPos), plpgsqlast.RAW_PARSE_DEFAULT)
			plpgsqlLOCAL = stmt
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 78:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:691
		{
			lx := plpgsqllex.(*lexer)
			startPos := plpgsqlDollar[1].location
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			stmt := plpgsqlast.NewPLpgSQL_stmt_call(false)
			stmt.Expr = makeExpr(lx.scanStmtText(false, startPos), plpgsqlast.RAW_PARSE_DEFAULT)
			plpgsqlLOCAL = stmt
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 79:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:709
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.makeReturnStmt()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 80:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:725
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.makeDynExecute()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 81:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:742
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.makeOpen(plpgsqlDollar[2].str)
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 82:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-4 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:753
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			fetch := plpgsqlDollar[2].fetchUnion()
			fetch.Curvar = plpgsqlDollar[3].str
			fetch.Target = lx.readFetchTarget()
			// A FETCH pulls one row into one target; multi-row directions
			// (ALL, a count) are MOVE-only. Mirrors PG's stmt_fetch check.
			if fetch.ReturnsMultipleRows {
				plpgsqllex.Error("FETCH statement cannot return multiple rows")
			}
			plpgsqlLOCAL = fetch
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 83:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-4 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:772
		{
			fetch := plpgsqlDollar[2].fetchUnion()
			fetch.Curvar = plpgsqlDollar[3].str
			fetch.IsMove = true
			plpgsqlLOCAL = fetch
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 84:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:782
		{
			stmt := plpgsqlast.NewPLpgSQL_stmt_close()
			stmt.Curvar = plpgsqlDollar[2].str
			plpgsqlLOCAL = stmt
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 85:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:796
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.makeRaiseStmt()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 86:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:811
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.makeAssertStmt()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 87:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-5 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:828
		{
			stmt := plpgsqlast.NewPLpgSQL_stmt_getdiag()
			stmt.IsStacked = plpgsqlDollar[2].bvalUnion()
			stmt.DiagItems = plpgsqlDollar[4].diagitemsUnion()
			plpgsqllex.(*lexer).checkGetDiagItems(stmt)
			plpgsqlLOCAL = stmt
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 88:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL bool
//line plpgsql.y:839
		{
			plpgsqlLOCAL = false
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 89:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL bool
//line plpgsql.y:843
		{
			plpgsqlLOCAL = false
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 90:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL bool
//line plpgsql.y:847
		{
			plpgsqlLOCAL = true
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 91:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
		var plpgsqlLOCAL []*plpgsqlast.PLpgSQL_diag_item
//line plpgsql.y:854
		{
			plpgsqlLOCAL = appendDiagItem(plpgsqlDollar[1].diagitemsUnion(), plpgsqlDollar[3].diagitemUnion())
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 92:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL []*plpgsqlast.PLpgSQL_diag_item
//line plpgsql.y:858
		{
			plpgsqlLOCAL = appendDiagItem(nil, plpgsqlDollar[1].diagitemUnion())
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 93:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_diag_item
//line plpgsql.y:865
		{
			plpgsqlLOCAL = plpgsqlast.NewPLpgSQL_diag_item(plpgsqlast.PLpgSQL_getdiag_kind(plpgsqlDollar[3].ival), plpgsqlDollar[1].str)
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 94:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql.y:877
		{
			plpgsqlVAL.str = plpgsqlDollar[1].str
		}
	case 95:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql.y:881
		{
			plpgsqlVAL.str = plpgsqlDollar[1].str
		}
	case 96:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql.y:888
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlVAL.ival = lx.readGetDiagItem()
		}
	case 97:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:902
		{
			stmt := plpgsqlast.NewPLpgSQL_stmt_commit()
			stmt.Chain = plpgsqlDollar[2].bvalUnion()
			plpgsqlLOCAL = stmt
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 98:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:911
		{
			stmt := plpgsqlast.NewPLpgSQL_stmt_rollback()
			stmt.Chain = plpgsqlDollar[2].bvalUnion()
			plpgsqlLOCAL = stmt
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 99:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL bool
//line plpgsql.y:920
		{
			plpgsqlLOCAL = true
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 100:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
		var plpgsqlLOCAL bool
//line plpgsql.y:924
		{
			plpgsqlLOCAL = false
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 101:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL bool
//line plpgsql.y:928
		{
			plpgsqlLOCAL = false
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 102:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_exception_block
//line plpgsql.y:940
		{
			plpgsqlLOCAL = nil
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 103:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_exception_block
//line plpgsql.y:944
		{
			block := plpgsqlast.NewPLpgSQL_exception_block()
			block.ExcList = plpgsqlDollar[2].excsUnion()
			plpgsqlLOCAL = block
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 104:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL []*plpgsqlast.PLpgSQL_exception
//line plpgsql.y:953
		{
			plpgsqlLOCAL = appendException(plpgsqlDollar[1].excsUnion(), plpgsqlDollar[2].excUnion())
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 105:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL []*plpgsqlast.PLpgSQL_exception
//line plpgsql.y:957
		{
			plpgsqlLOCAL = appendException(nil, plpgsqlDollar[1].excUnion())
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 106:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-4 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_exception
//line plpgsql.y:964
		{
			exc := plpgsqlast.NewPLpgSQL_exception()
			exc.Conditions = plpgsqlDollar[2].condsUnion()
			exc.Action = plpgsqlDollar[4].stmtsUnion()
			plpgsqlLOCAL = exc
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 107:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
		var plpgsqlLOCAL []*plpgsqlast.PLpgSQL_condition
//line plpgsql.y:974
		{
			plpgsqlLOCAL = appendCondition(plpgsqlDollar[1].condsUnion(), plpgsqlDollar[3].condUnion())
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 108:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL []*plpgsqlast.PLpgSQL_condition
//line plpgsql.y:978
		{
			plpgsqlLOCAL = appendCondition(nil, plpgsqlDollar[1].condUnion())
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 109:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_condition
//line plpgsql.y:993
		{
			if plpgsqlDollar[1].str == "sqlstate" {
				lx := plpgsqllex.(*lexer)
				lx.beginScan(plpgsqlrcvr.char)
				plpgsqlrcvr.char = -1
				plpgsqltoken = -1
				plpgsqlLOCAL = lx.readSQLStateCondition()
			} else {
				plpgsqlLOCAL = plpgsqlast.NewPLpgSQL_condition(plpgsqlDollar[1].str)
			}
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 110:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_stmt_fetch
//line plpgsql.y:1008
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.readFetchDirection()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 111:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql.y:1023
		{
			plpgsqlVAL.str = plpgsqlDollar[1].str
		}
	case 112:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-8 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:1034
		{
			stmt := plpgsqlast.NewPLpgSQL_stmt_if()
			stmt.Cond = plpgsqlDollar[2].exprUnion()
			stmt.ThenBody = plpgsqlDollar[3].stmtsUnion()
			stmt.ElsifList = plpgsqlDollar[4].elsifsUnion()
			stmt.ElseBody = plpgsqlDollar[5].stmtsUnion()
			plpgsqlLOCAL = stmt
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 113:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL []*plpgsqlast.PLpgSQL_if_elsif
//line plpgsql.y:1046
		{
			plpgsqlLOCAL = nil
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 114:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-4 : plpgsqlpt+1]
		var plpgsqlLOCAL []*plpgsqlast.PLpgSQL_if_elsif
//line plpgsql.y:1050
		{
			ei := plpgsqlast.NewPLpgSQL_if_elsif()
			ei.Cond = plpgsqlDollar[3].exprUnion()
			ei.Stmts = plpgsqlDollar[4].stmtsUnion()
			plpgsqlLOCAL = appendElsif(plpgsqlDollar[1].elsifsUnion(), ei)
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 115:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL []plpgsqlast.Stmt
//line plpgsql.y:1060
		{
			plpgsqlLOCAL = nil
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 116:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL []plpgsqlast.Stmt
//line plpgsql.y:1064
		{
			plpgsqlLOCAL = plpgsqlDollar[2].stmtsUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 117:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:1077
		{
			stmt := plpgsqlast.NewPLpgSQL_stmt_loop()
			stmt.Label = plpgsqlDollar[1].str
			stmt.Body = plpgsqlDollar[3].loopbodyUnion().stmts
			if err := checkLabels(plpgsqlDollar[1].str, plpgsqlDollar[3].loopbodyUnion().endLabel); err != nil {
				plpgsqllex.Error(err.Error())
			}
			plpgsqlLOCAL = stmt
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 118:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-4 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:1090
		{
			stmt := plpgsqlast.NewPLpgSQL_stmt_while()
			stmt.Label = plpgsqlDollar[1].str
			stmt.Cond = plpgsqlDollar[3].exprUnion()
			stmt.Body = plpgsqlDollar[4].loopbodyUnion().stmts
			if err := checkLabels(plpgsqlDollar[1].str, plpgsqlDollar[4].loopbodyUnion().endLabel); err != nil {
				plpgsqllex.Error(err.Error())
			}
			plpgsqlLOCAL = stmt
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 119:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-5 : plpgsqlpt+1]
		var plpgsqlLOCAL loopBody
//line plpgsql.y:1104
		{
			plpgsqlLOCAL = loopBody{stmts: plpgsqlDollar[1].stmtsUnion(), endLabel: plpgsqlDollar[4].str}
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 120:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-4 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:1118
		{
			switch s := plpgsqlDollar[3].stmtUnion().(type) {
			case *plpgsqlast.PLpgSQL_stmt_fori:
				s.Label = plpgsqlDollar[1].str
				s.Body = plpgsqlDollar[4].loopbodyUnion().stmts
			case *plpgsqlast.PLpgSQL_stmt_fors:
				s.Label = plpgsqlDollar[1].str
				s.Body = plpgsqlDollar[4].loopbodyUnion().stmts
			case *plpgsqlast.PLpgSQL_stmt_dynfors:
				s.Label = plpgsqlDollar[1].str
				s.Body = plpgsqlDollar[4].loopbodyUnion().stmts
			}
			if err := checkLabels(plpgsqlDollar[1].str, plpgsqlDollar[4].loopbodyUnion().endLabel); err != nil {
				plpgsqllex.Error(err.Error())
			}
			plpgsqlLOCAL = plpgsqlDollar[3].stmtUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 121:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:1139
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.readForControl(plpgsqlDollar[1].forvarUnion())
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 122:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL forVariable
//line plpgsql.y:1160
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.readForVariable(plpgsqlDollar[1].str)
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 123:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL forVariable
//line plpgsql.y:1168
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.readForVariable(plpgsqlDollar[1].str)
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 124:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-8 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:1179
		{
			stmt := plpgsqlast.NewPLpgSQL_stmt_foreach_a()
			stmt.Label = plpgsqlDollar[1].str
			stmt.Var = plpgsqlDollar[3].forvarUnion().name
			stmt.Slice = plpgsqlDollar[4].ival
			stmt.Expr = plpgsqlDollar[7].exprUnion()
			stmt.Body = plpgsqlDollar[8].loopbodyUnion().stmts
			if err := checkLabels(plpgsqlDollar[1].str, plpgsqlDollar[8].loopbodyUnion().endLabel); err != nil {
				plpgsqllex.Error(err.Error())
			}
			plpgsqlLOCAL = stmt
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 125:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql.y:1195
		{
			plpgsqlVAL.ival = 0
		}
	case 126:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
//line plpgsql.y:1199
		{
			plpgsqlVAL.ival = plpgsqlDollar[2].ival
		}
	case 127:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-7 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:1211
		{
			stmt := plpgsqlast.NewPLpgSQL_stmt_case()
			stmt.TestExpr = plpgsqlDollar[2].exprUnion()
			stmt.WhenList = plpgsqlDollar[3].casewhensUnion()
			// A present-but-empty ELSE is a non-nil slice (PG's list-with-NULL
			// hack); no ELSE is nil. HaveElse preserves the distinction, which
			// PG uses to suppress CASE_NOT_FOUND.
			stmt.HaveElse = plpgsqlDollar[4].stmtsUnion() != nil
			stmt.ElseStmts = plpgsqlDollar[4].stmtsUnion()
			plpgsqlLOCAL = stmt
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 128:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_expr
//line plpgsql.y:1226
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.readCaseTestExpr()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 129:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL []*plpgsqlast.PLpgSQL_case_when
//line plpgsql.y:1237
		{
			plpgsqlLOCAL = appendCaseWhen(plpgsqlDollar[1].casewhensUnion(), plpgsqlDollar[2].casewhenUnion())
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 130:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL []*plpgsqlast.PLpgSQL_case_when
//line plpgsql.y:1241
		{
			plpgsqlLOCAL = appendCaseWhen(nil, plpgsqlDollar[1].casewhenUnion())
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 131:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_case_when
//line plpgsql.y:1248
		{
			cw := plpgsqlast.NewPLpgSQL_case_when()
			cw.Expr = plpgsqlDollar[2].exprUnion()
			cw.Stmts = plpgsqlDollar[3].stmtsUnion()
			plpgsqlLOCAL = cw
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 132:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL []plpgsqlast.Stmt
//line plpgsql.y:1258
		{
			plpgsqlLOCAL = nil
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 133:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL []plpgsqlast.Stmt
//line plpgsql.y:1262
		{
			// Return a non-nil slice even for an empty ELSE body, so stmt_case
			// can tell "ELSE present" from "no ELSE" (PG's list-with-NULL hack).
			if plpgsqlDollar[2].stmtsUnion() == nil {
				plpgsqlLOCAL = []plpgsqlast.Stmt{}
			} else {
				plpgsqlLOCAL = plpgsqlDollar[2].stmtsUnion()
			}
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 134:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
		var plpgsqlLOCAL plpgsqlast.Stmt
//line plpgsql.y:1280
		{
			stmt := plpgsqlast.NewPLpgSQL_stmt_exit(plpgsqlDollar[1].bvalUnion())
			stmt.Label = plpgsqlDollar[2].str
			stmt.Cond = plpgsqlDollar[3].exprUnion()
			plpgsqlLOCAL = stmt
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 135:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL bool
//line plpgsql.y:1290
		{
			plpgsqlLOCAL = true
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 136:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL bool
//line plpgsql.y:1294
		{
			plpgsqlLOCAL = false
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 137:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_expr
//line plpgsql.y:1301
		{
			plpgsqlLOCAL = nil
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 138:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-2 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_expr
//line plpgsql.y:1305
		{
			plpgsqlLOCAL = plpgsqlDollar[2].exprUnion()
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 139:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_expr
//line plpgsql.y:1318
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.readSQLExprUntil(';')
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 140:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_expr
//line plpgsql.y:1329
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.readSQLExprUntil(K_THEN)
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 141:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
		var plpgsqlLOCAL *plpgsqlast.PLpgSQL_expr
//line plpgsql.y:1340
		{
			lx := plpgsqllex.(*lexer)
			lx.beginScan(plpgsqlrcvr.char)
			plpgsqlrcvr.char = -1
			plpgsqltoken = -1
			plpgsqlLOCAL = lx.readSQLExprUntil(K_LOOP)
		}
		plpgsqlVAL.union = plpgsqlLOCAL
	case 142:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql.y:1351
		{
			plpgsqlVAL.str = ""
		}
	case 143:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql.y:1355
		{
			plpgsqlVAL.str = plpgsqlDollar[2].str
		}
	case 144:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql.y:1362
		{
			plpgsqlVAL.str = ""
		}
	case 145:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-3 : plpgsqlpt+1]
//line plpgsql.y:1366
		{
			plpgsqlVAL.str = plpgsqlDollar[2].str
		}
	case 146:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-0 : plpgsqlpt+1]
//line plpgsql.y:1373
		{
			plpgsqlVAL.str = ""
		}
	case 147:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql.y:1377
		{
			plpgsqlVAL.str = plpgsqlDollar[1].str
		}
	case 148:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql.y:1384
		{
			plpgsqlVAL.str = plpgsqlDollar[1].str
		}
	case 149:
		plpgsqlDollar = plpgsqlS[plpgsqlpt-1 : plpgsqlpt+1]
//line plpgsql.y:1388
		{
			plpgsqlVAL.str = plpgsqlDollar[1].str
		}
	}
	goto plpgsqlstack /* stack new state and value */
}
