// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package migrator

import (
	"context"
	"fmt"
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	migratorpb "github.com/multigres/multigres/go/pb/migrator"
	"github.com/multigres/multigres/go/test/endtoend/shardsetup"
	"github.com/multigres/multigres/go/test/utils"
)

type tableSpec struct {
	name string
	rows int64
}

// seedManyTables creates several PK'd tables on the source and fills them so the
// initial copy takes long enough to interrupt. A wide pad column makes the copy
// byte-heavy (slow) without needing an enormous row count.
func seedManyTables(t *testing.T, ctx context.Context, port int, specs []tableSpec) {
	t.Helper()
	conn := dialSource(t, ctx, port)
	defer conn.Close()
	for _, s := range specs {
		_, err := conn.Query(ctx, fmt.Sprintf(
			"CREATE TABLE %s (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, pad text)", s.name,
		))
		require.NoError(t, err, "create %s", s.name)
		_, err = conn.Query(ctx, fmt.Sprintf(
			"INSERT INTO %s (pad) SELECT repeat('x',500) FROM generate_series(1,%d)", s.name, s.rows,
		))
		require.NoError(t, err, "seed %s", s.name)
	}
}

// TestTargetFailoverDuringCopy is the COPYING-phase companion to
// TestTargetFailoverDuringMigration: it kills the target primary while the
// initial copy is only partway done — some tables copied (srsubstate 'r'),
// others still pending — instead of after catch-up. With several tables (one
// tiny that finishes almost immediately, the rest large) the kill is gated on a
// partial ready_relations count, so we reliably interrupt mid-copy. After
// multiorch promotes a standby, the migration must finish on the new primary:
// already-copied tables are preserved and incomplete ones re-copy from scratch
// (the non-resumable-copy behavior of Strategy S), ending with every table at
// its full row count and no data loss.
func TestTargetFailoverDuringCopy(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping Multigres Migrator copy-failover e2e in short mode")
	}
	if utils.ShouldSkipRealPostgres() {
		t.Skip("no postgres binaries")
	}
	ctx := t.Context()

	setup, cleanup := shardsetup.NewIsolated(
		t,
		shardsetup.WithMultipoolerCount(3),
		shardsetup.WithMultiorchCount(3),
		shardsetup.WithDatabase("postgres"),
		shardsetup.WithCellName("test-cell"),
	)
	defer cleanup()
	setup.StartMultiorchs(ctx, t)

	primary := setup.GetPrimary(t)
	oldPrimaryName := setup.PrimaryName
	targetDB := waitForPrimaryDB(t, ctx, setup)

	srcPort := startStandaloneSource(t)
	specs := []tableSpec{
		{"public.t_small", 200},
		{"public.t_a", 100000},
		{"public.t_b", 100000},
		{"public.t_c", 100000},
		{"public.t_d", 100000},
	}
	seedManyTables(t, ctx, srcPort, specs)

	tables := make([]string, len(specs))
	for i, s := range specs {
		tables[i] = s.name
	}

	mt, mtClose := migrationClient(t, primary)
	createResp, err := mt.CreateMigration(ctx, &migratorpb.CreateMigrationRequest{
		SourceDsn:      sourceDSN(srcPort),
		TargetDatabase: targetDB,
		Tables:         tables,
	})
	require.NoError(t, err)
	id := createResp.GetMigration().GetId()
	_, err = mt.StartMigration(ctx, &migratorpb.StartMigrationRequest{Id: id})
	require.NoError(t, err)
	mtClose()

	// Wait until the initial copy is PARTWAY across the data tables: at least one
	// fully copied and at least one not yet. A tablesync COPY commits atomically,
	// so a data table on the target has either 0 rows (still copying) or its full
	// count (done); count the done ones directly on the (soon-to-die) primary.
	// (We can't gate on the migration's total/ready relation counts because those
	// include multigres.ddl_log, which DDL replication adds to the subscription.)
	oldTC := targetConn(t, ctx, primary, targetDB)
	var copiedAtKill int
	require.Eventually(t, func() bool {
		copiedAtKill = 0
		for _, s := range specs {
			if n, ok := countRows(t, ctx, oldTC, s.name); ok && int64(n) == s.rows {
				copiedAtKill++
			}
		}
		return copiedAtKill >= 1 && copiedAtKill < len(specs)
	}, 60*time.Second, 50*time.Millisecond, "must observe a partial initial copy (some data tables copied, some not)")
	oldTC.Close()
	t.Logf("killing primary %s mid-copy: %d/%d data tables copied", oldPrimaryName, copiedAtKill, len(specs))

	// Kill the target primary mid-copy; multiorch promotes a standby that carries
	// the partial subscription state via physical replication.
	setup.KillPostgres(t, oldPrimaryName)
	newPrimaryName := shardsetup.WaitForNewPrimary(t, setup, oldPrimaryName, 60*time.Second)
	require.NotEmpty(t, newPrimaryName, "multiorch must elect a new primary")
	t.Logf("new primary: %s", newPrimaryName)
	newPrimary := setup.GetMultipoolerInstance(newPrimaryName)
	require.NotNil(t, newPrimary)
	shardsetup.WaitForManagerReady(t, newPrimary.Multipooler)

	// The migration resumes on the new primary and finishes the copy: every table
	// must reach its full row count (incomplete ones re-copied, done ones kept).
	tc := targetConn(t, ctx, newPrimary, targetDB)
	defer tc.Close()
	require.Eventually(t, func() bool {
		for _, s := range specs {
			n, ok := countRows(t, ctx, tc, s.name)
			if !ok || int64(n) != s.rows {
				t.Logf("waiting for copy to finish: %s = %d (want %d)", s.name, n, s.rows)
				return false
			}
		}
		return true
	}, 120*time.Second, 1*time.Second, "all tables must reach full row count on the new primary after mid-copy failover")

	// A post-failover source write must also reach the new primary — proving the
	// stream resumed against the surviving slot on the promoted node.
	sc := dialSource(t, ctx, srcPort)
	_, err = sc.Query(ctx, "INSERT INTO public.t_small (pad) VALUES ('post')")
	require.NoError(t, err)
	_ = sc.Close()
	require.Eventually(t, func() bool {
		n, ok := countRows(t, ctx, tc, "public.t_small")
		return ok && int64(n) == specs[0].rows+1
	}, 60*time.Second, 1*time.Second, "post-failover source write must reach the new primary")
}
