// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package migrator

import (
	"context"
	"strconv"
	"testing"
	"time"

	"github.com/stretchr/testify/require"

	"github.com/multigres/multigres/go/common/pgprotocol/client"
	migratorpb "github.com/multigres/multigres/go/pb/migrator"
	"github.com/multigres/multigres/go/test/endtoend/shardsetup"
	"github.com/multigres/multigres/go/test/utils"
)

// TestDDLReplicationConcurrentIsolation proves DDL scoping across two migrations
// running concurrently on the same target: each migration replicates ONLY the
// DDL of its own tables. Migration A covers public.orders, migration B covers
// public.widgets (both from the same source, into the same target). A schema
// change on one table must ride only that migration's stream — asserted both
// end-to-end (each target table converges) and white-box (the shared
// multigres.ddl_log on the target tags every captured statement with exactly the
// owning migration, and neither migration's stream carries the other's table).
func TestDDLReplicationConcurrentIsolation(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping Multigres Migrator e2e in short mode")
	}
	if !utils.HasPostgreSQLBinaries() {
		t.Skip("PostgreSQL client/server binaries not on PATH")
	}
	ctx := t.Context()

	setup, cleanup := shardsetup.NewIsolated(t, shardsetup.WithMultipoolerCount(2))
	defer cleanup()
	primary := setup.GetPrimary(t)
	shardsetup.WaitForManagerReady(t, primary.Multipooler)
	targetDB := waitForPrimaryDB(t, ctx, setup)

	srcPort := startStandaloneSource(t)
	seedSource(t, ctx, srcPort) // public.orders
	sc := dialSource(t, ctx, srcPort)
	defer sc.Close()
	for _, stmt := range []string{
		"CREATE TABLE public.widgets (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, w text)",
		"INSERT INTO public.widgets (w) VALUES ('p'), ('q')",
	} {
		_, err := sc.Query(ctx, stmt)
		require.NoError(t, err, stmt)
	}

	mt, mtClose := migrationClient(t, primary)
	defer mtClose()

	idA := createAndStartMigration(t, ctx, mt, srcPort, targetDB, []string{"public.orders"})
	idB := createAndStartMigration(t, ctx, mt, srcPort, targetDB, []string{"public.widgets"})
	waitCaughtUp(t, ctx, mt, idA)
	waitCaughtUp(t, ctx, mt, idB)

	tc := targetConn(t, ctx, primary, targetDB)
	defer tc.Close()

	// A schema change on each migration's own table.
	_, err := sc.Query(ctx, "ALTER TABLE public.orders ADD COLUMN a_note text")
	require.NoError(t, err)
	_, err = sc.Query(ctx, "ALTER TABLE public.widgets ADD COLUMN b_note text")
	require.NoError(t, err)

	require.Eventually(t, func() bool {
		return columnsOf(t, ctx, tc, "public", "orders") == "id,v,a_note"
	}, 30*time.Second, 500*time.Millisecond, "orders ALTER (migration A) must replicate")
	require.Eventually(t, func() bool {
		return columnsOf(t, ctx, tc, "public", "widgets") == "id,w,b_note"
	}, 30*time.Second, 500*time.Millisecond, "widgets ALTER (migration B) must replicate")

	// White-box: on the target, each captured statement is tagged with exactly its
	// owning migration and no migration's stream carries the other's table. (A
	// leak would also collide on the (migration_id, log_id) primary key and stall the
	// receiving subscription — checked by the still-streaming assertion below.)
	require.Equal(t, 1, ddlLogCount(t, ctx, tc, idA, "orders"), "A carries its own orders DDL")
	require.Equal(t, 0, ddlLogCount(t, ctx, tc, idA, "widgets"), "A must not carry B's widgets DDL")
	require.Equal(t, 1, ddlLogCount(t, ctx, tc, idB, "widgets"), "B carries its own widgets DDL")
	require.Equal(t, 0, ddlLogCount(t, ctx, tc, idB, "orders"), "B must not carry A's orders DDL")

	// Both streams still flow after the DDL — neither subscription stalled.
	_, err = sc.Query(ctx, "INSERT INTO public.orders (v, a_note) VALUES ('d', 'n')")
	require.NoError(t, err)
	_, err = sc.Query(ctx, "INSERT INTO public.widgets (w, b_note) VALUES ('r', 'n')")
	require.NoError(t, err)
	require.Eventually(t, func() bool {
		n, ok := countRows(t, ctx, tc, "public.orders")
		return ok && n == 4
	}, 30*time.Second, 500*time.Millisecond, "migration A keeps streaming")
	require.Eventually(t, func() bool {
		n, ok := countRows(t, ctx, tc, "public.widgets")
		return ok && n == 3
	}, 30*time.Second, 500*time.Millisecond, "migration B keeps streaming")
}

// TestDDLReplicationExport proves DDL capture follows the publisher across a
// direction switch: after switching to EXPORT (the Multigres target becomes the
// publisher), a schema change on the target replicates OUT to the old database,
// scoped to the migration's tables — a change on a non-migrated table does not.
func TestDDLReplicationExport(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping Multigres Migrator switch e2e in short mode")
	}
	if !utils.HasPostgreSQLBinaries() {
		t.Skip("PostgreSQL client/server binaries not on PATH")
	}
	ctx := t.Context()

	setup, cleanup := shardsetup.NewIsolated(
		t,
		shardsetup.WithMultipoolerCount(2),
		// EXPORT makes the Multigres target the logical publisher, which needs the
		// slot-based-replication admission (matching targetConnInfo's guardrail).
		shardsetup.WithMultipoolerExtraArgs("--enable-slot-based-replication=true"),
	)
	defer cleanup()
	primary := setup.GetPrimary(t)
	shardsetup.WaitForManagerReady(t, primary.Multipooler)
	targetDB := waitForPrimaryDB(t, ctx, setup)

	srcPort := startStandaloneSource(t)
	seedSource(t, ctx, srcPort)

	mt, mtClose := migrationClient(t, primary)
	defer mtClose()

	id := createAndStartMigration(t, ctx, mt, srcPort, targetDB, []string{"public.orders"})
	waitCaughtUp(t, ctx, mt, id)

	tc := targetConn(t, ctx, primary, targetDB)
	defer tc.Close()

	// Switch to EXPORT: Multigres becomes the publisher, so DDL capture moves to
	// the target and apply to the old database.
	exportResp, err := mt.SetMigrationDirection(ctx, &migratorpb.SetMigrationDirectionRequest{
		Id: id, Direction: migratorpb.MigrationDirection_MIGRATION_DIRECTION_EXPORT,
	})
	require.NoError(t, err)
	require.Equal(t, migratorpb.MigrationDirection_MIGRATION_DIRECTION_EXPORT, exportResp.GetMigration().GetActiveDirection())

	// A schema change on the migrated table on the Multigres target must reach the
	// old database.
	_, err = tc.Query(ctx, "ALTER TABLE public.orders ADD COLUMN exp_note text")
	require.NoError(t, err)
	require.Eventually(t, func() bool {
		sc := dialSource(t, ctx, srcPort)
		defer sc.Close()
		return columnsOf(t, ctx, sc, "public", "orders") == "id,v,exp_note"
	}, 30*time.Second, 500*time.Millisecond, "EXPORT: target DDL on a migrated table must reach the old database")

	// A schema change on a NON-migrated table on the target must NOT reach the old
	// database. Create+ALTER an unrelated table, then push a migrated-table write
	// after it and wait for that to land as a barrier.
	for _, stmt := range []string{
		"CREATE TABLE public.untracked (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, x text)",
		"ALTER TABLE public.untracked ADD COLUMN y text",
		"INSERT INTO public.orders (v, exp_note) VALUES ('z', 'barrier')",
	} {
		_, err = tc.Query(ctx, stmt)
		require.NoError(t, err, stmt)
	}
	require.Eventually(t, func() bool {
		sc := dialSource(t, ctx, srcPort)
		defer sc.Close()
		n, ok := countRows(t, ctx, sc, "public.orders")
		return ok && n == 4
	}, 30*time.Second, 500*time.Millisecond, "EXPORT: later migrated write must land (barrier)")
	sc := dialSource(t, ctx, srcPort)
	defer sc.Close()
	require.Equal(t, "", columnsOf(t, ctx, sc, "public", "untracked"),
		"EXPORT: DDL on a non-migrated table must not reach the old database")

	_, err = mt.DropMigration(ctx, &migratorpb.DropMigrationRequest{Id: id, Force: true})
	require.NoError(t, err)
}

// createAndStartMigration creates and starts an IMPORT migration for the given
// tables and returns its id.
func createAndStartMigration(t *testing.T, ctx context.Context, mt migratorpb.MigratorClient, srcPort int, targetDB string, tables []string) string {
	t.Helper()
	createResp, err := mt.CreateMigration(ctx, &migratorpb.CreateMigrationRequest{
		SourceDsn:      sourceDSN(srcPort),
		TargetDatabase: targetDB,
		Tables:         tables,
	})
	require.NoError(t, err)
	id := createResp.GetMigration().GetId()
	startResp, err := mt.StartMigration(ctx, &migratorpb.StartMigrationRequest{Id: id})
	require.NoError(t, err, "start; last_error=%s", startResp.GetMigration().GetLastError())
	return id
}

// waitCaughtUp blocks until the migration reports caught up.
func waitCaughtUp(t *testing.T, ctx context.Context, mt migratorpb.MigratorClient, id string) {
	t.Helper()
	require.Eventually(t, func() bool {
		resp, err := mt.GetMigrations(ctx, &migratorpb.GetMigrationsRequest{Id: id})
		return err == nil && len(resp.GetMigrations()) == 1 && resp.GetMigrations()[0].GetCaughtUp()
	}, 60*time.Second, 500*time.Millisecond, "migration %s must catch up", id)
}

// ddlLogCount returns the number of rows in the target's shared
// multigres.ddl_log tagged with the given migration_id and table_name. The test
// target connection authenticates as the postgres superuser, so it can read the
// superuser-only sidecar table.
func ddlLogCount(t *testing.T, ctx context.Context, conn *client.Conn, migrationID, table string) int {
	t.Helper()
	res, err := conn.Query(ctx,
		"SELECT count(*) FROM multigres.ddl_log WHERE migration_id = '"+migrationID+
			"' AND table_name = '"+table+"'")
	require.NoError(t, err)
	require.NotEmpty(t, res)
	require.NotEmpty(t, res[0].Rows)
	n, err := strconv.Atoi(string(res[0].Rows[0].Values[0]))
	require.NoError(t, err)
	return n
}
