// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package migrator

import (
	"context"
	"testing"

	"github.com/stretchr/testify/require"

	migratorpb "github.com/multigres/multigres/go/pb/migrator"
	"github.com/multigres/multigres/go/test/endtoend/shardsetup"
	"github.com/multigres/multigres/go/test/utils"
)

// seedResolutionSource creates a spread of tables for exercising table selection:
//   - public.{orders,items}: ordinary PK tables in the search_path (matched by "*")
//   - app.{a,b}: PK tables in a schema NOT on the search_path (matched by "app.*",
//     never by "*")
//   - checks.full_ri: no PK, REPLICA IDENTITY FULL (resolves, warns)
//   - checks.no_pk: no PK, default replica identity (rejected)
//   - checks.nothing_ri: REPLICA IDENTITY NOTHING (rejected)
//
// The checks.* tables live off the search_path so "*" never sweeps them in and
// only the explicit cases below exercise the replica-identity rules.
func seedResolutionSource(t *testing.T, ctx context.Context, port int) {
	t.Helper()
	conn := dialSource(t, ctx, port)
	defer conn.Close()
	for _, stmt := range []string{
		"CREATE TABLE public.orders (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, v text)",
		"CREATE TABLE public.items (id bigint PRIMARY KEY)",
		"CREATE SCHEMA app",
		"CREATE TABLE app.a (id int PRIMARY KEY)",
		"CREATE TABLE app.b (id int PRIMARY KEY)",
		"CREATE SCHEMA checks",
		"CREATE TABLE checks.full_ri (id int)",
		"ALTER TABLE checks.full_ri REPLICA IDENTITY FULL",
		"CREATE TABLE checks.no_pk (id int)",
		"CREATE TABLE checks.nothing_ri (id int)",
		"ALTER TABLE checks.nothing_ri REPLICA IDENTITY NOTHING",
	} {
		_, err := conn.Query(ctx, stmt)
		require.NoError(t, err, "seed: %s", stmt)
	}
}

// TestCreateMigrationTableResolution drives create-migration (validation only, no
// replication) across the table-selection matrix and asserts the resolved table
// list, wildcard/explicit dedup, and the create-time errors for missing schemas,
// missing tables, and unusable replica identities.
func TestCreateMigrationTableResolution(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping Multigres Migrator e2e in short mode")
	}
	if !utils.HasPostgreSQLBinaries() {
		t.Skip("PostgreSQL client/server binaries not on PATH")
	}
	ctx := t.Context()

	setup, cleanup := shardsetup.NewIsolated(t, shardsetup.WithMultipoolerCount(2))
	defer cleanup()
	primary := setup.GetPrimary(t)
	shardsetup.WaitForManagerReady(t, primary.Multipooler)
	targetDB := waitForPrimaryDB(t, ctx, setup)

	srcPort := startStandaloneSource(t)
	seedResolutionSource(t, ctx, srcPort)

	mt, mtClose := migrationClient(t, primary)
	defer mtClose()

	cases := []struct {
		name        string
		tables      []string
		want        []string // expected resolved tables (ordered schema, table); nil when an error is expected
		errContains string
	}{
		{"star is search_path tables", []string{"*"}, []string{"public.items", "public.orders"}, ""},
		{"schema wildcard reaches off-path schema", []string{"app.*"}, []string{"app.a", "app.b"}, ""},
		{"bare name canonicalizes via search_path", []string{"orders"}, []string{"public.orders"}, ""},
		{"star plus explicit dedups", []string{"*", "orders"}, []string{"public.items", "public.orders"}, ""},
		{"mixed schema wildcard and explicit", []string{"app.*", "public.orders"}, []string{"app.a", "app.b", "public.orders"}, ""},
		{"full replica identity resolves", []string{"checks.full_ri"}, []string{"checks.full_ri"}, ""},
		{"missing schema errors", []string{"nope.*"}, nil, "schema"},
		{"missing qualified table errors", []string{"public.nope"}, nil, "do not exist"},
		{"missing bare table errors", []string{"nope"}, nil, "do not exist"},
		{"replica identity nothing errors", []string{"checks.nothing_ri"}, nil, "replica identity"},
		{"no primary key errors", []string{"checks.no_pk"}, nil, "primary key"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			resp, err := mt.CreateMigration(ctx, &migratorpb.CreateMigrationRequest{
				SourceDsn:      sourceDSN(srcPort),
				TargetDatabase: targetDB,
				Tables:         tc.tables,
			})
			if tc.errContains != "" {
				require.Error(t, err)
				require.Contains(t, err.Error(), tc.errContains)
				return
			}
			require.NoError(t, err)
			// resolved order is unspecified (the query does not ORDER BY), so
			// compare as a set.
			require.ElementsMatch(t, tc.want, resp.GetMigration().GetTables())
		})
	}
}
