# Job to generate TLS certificates for pgBackRest
# Creates a Root CA and pgBackRest certificate signed by the CA
apiVersion: batch/v1
kind: Job
metadata:
  name: generate-pgbackrest-certs
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: cert-generator
          image: alpine/openssl:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              cd /certs

              echo "Generating Root CA certificate..."
              openssl req -x509 -newkey rsa:4096 -nodes -days 3650 \
                -keyout ca.key \
                -out ca.crt \
                -subj "/CN=Multigres Root CA"

              echo "Generating pgBackRest certificate signing request..."
              openssl req -newkey rsa:2048 -nodes \
                -keyout pgbackrest.key \
                -out /tmp/pgbackrest.csr \
                -subj "/CN=pgbackrest"

              echo "Signing pgBackRest certificate with Root CA..."
              openssl x509 -req -days 3650 \
                -in /tmp/pgbackrest.csr \
                -CA ca.crt \
                -CAkey ca.key \
                -CAcreateserial \
                -out pgbackrest.crt

              echo "Cleaning up temporary files..."
              rm -f /tmp/pgbackrest.csr ca.srl

              # Remove CA private key - we don't need it after signing the certificate
              # Keep only ca.crt for verification, pgbackrest.crt and pgbackrest.key for TLS
              echo "Removing CA private key (no longer needed)..."
              rm -f ca.key

              echo "Setting file permissions..."
              chmod 600 *.key
              chmod 644 *.crt

              echo "Certificate generation complete!"
              echo "Generated files:"
              ls -lh /certs/

              echo ""
              echo "Verifying certificate chain..."
              openssl verify -CAfile ca.crt pgbackrest.crt

          volumeMounts:
            - name: certs
              mountPath: /certs
      volumes:
        # Using hostPath to persist certificates on the Kind node
        # For production, use a PersistentVolumeClaim or create Kubernetes Secrets
        - name: certs
          hostPath:
            path: /data/certs
            type: DirectoryOrCreate
