# Observability stack for kind_demo: Prometheus + Jaeger + Grafana
# All three services run in a single pod for simplicity.
---
# ConfigMap: Prometheus configuration (minimal - using OTLP push, not scrape)
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
---
# ConfigMap: Grafana datasources
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        uid: Prometheus
        access: proxy
        url: http://localhost:9090
        isDefault: true
        editable: false
        jsonData:
          timeInterval: "60s"
          exemplarTraceIdDestinations:
            - name: trace_id
              datasourceUid: jaeger
              url: "http://localhost:16686/trace/$${__value.raw}"
              urlDisplayLabel: "View Trace in Jaeger"
      - name: Jaeger
        type: jaeger
        uid: jaeger
        access: proxy
        url: http://localhost:16686
        editable: false
---
# ConfigMap: Grafana dashboard provisioning
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-config
data:
  dashboards.yml: |
    apiVersion: 1
    providers:
      - name: "default"
        orgId: 1
        folder: ""
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
---
# ConfigMap: OTEL environment variables for multigres services
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
data:
  OTEL_METRIC_EXPORT_INTERVAL: "5000"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://observability:4318/v1/traces"
  OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: "http://observability:9090/api/v1/otlp/v1/metrics"
  OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE: "cumulative"
  OTEL_TRACES_EXPORTER: "otlp"
  OTEL_METRICS_EXPORTER: "otlp"
  OTEL_TRACES_SAMPLER: "always_on"
  OTEL_EXPORTER_OTLP_METRICS_DEFAULT_HISTOGRAM_AGGREGATION: "base2_exponential_bucket_histogram"
---
# Deployment: Observability stack (Prometheus + Jaeger + Grafana in one pod)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: observability
  labels:
    app: observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: observability
  template:
    metadata:
      labels:
        app: observability
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/jaeger:2.3.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 16686
              name: ui
            - containerPort: 4318
              name: otlp-http
            - containerPort: 4317
              name: otlp-grpc
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
        - name: prometheus
          image: prom/prometheus:v3.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
              name: http
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.console.libraries=/usr/share/prometheus/console_libraries"
            - "--web.console.templates=/usr/share/prometheus/consoles"
            - "--enable-feature=exemplar-storage"
            - "--enable-feature=native-histograms"
            - "--web.enable-otlp-receiver"
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
        - name: grafana
          image: grafana/grafana:11.4.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: "Admin"
            - name: GF_AUTH_DISABLE_LOGIN_FORM
              value: "true"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"
          volumeMounts:
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: grafana-dashboards-config
              mountPath: /etc/grafana/provisioning/dashboards
            - name: grafana-dashboard-multigres
              mountPath: /var/lib/grafana/dashboards
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
        - name: grafana-datasources
          configMap:
            name: grafana-datasources
        - name: grafana-dashboards-config
          configMap:
            name: grafana-dashboards-config
        - name: grafana-dashboard-multigres
          configMap:
            name: grafana-dashboard-multigres
---
# Service: Observability endpoints
apiVersion: v1
kind: Service
metadata:
  name: observability
spec:
  selector:
    app: observability
  ports:
    - port: 16686
      targetPort: 16686
      name: jaeger-ui
    - port: 4318
      targetPort: 4318
      name: otlp-http
    - port: 4317
      targetPort: 4317
      name: otlp-grpc
    - port: 9090
      targetPort: 9090
      name: prometheus
    - port: 3000
      targetPort: 3000
      name: grafana
  type: ClusterIP
