// Copyright 2026 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package pgregresstest

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/multigres/multigres/go/test/endtoend/shardsetup"
	"github.com/multigres/multigres/go/test/endtoend/suiteutil"
)

// testdataConfPath returns the absolute path to a postgresql.conf snippet under
// this package's testdata/pg<major>/<parts...>. Resolved via runtime.Caller so
// the path is correct regardless of the test's working directory at run time.
func testdataConfPath(parts ...string) string {
	_, file, _, _ := runtime.Caller(0)
	pkgDir := filepath.Dir(file)
	return filepath.Join(append([]string{pkgDir, "testdata", "pg17"}, parts...)...)
}

// regressionOverridesConfPath returns the snippet that forces lc_* GUCs to 'C'
// on each pgctld so locale-sensitive expected outputs reproduce upstream.
func regressionOverridesConfPath() string {
	return testdataConfPath("regression_overrides.conf")
}

// externalServerConfPaths returns the postgresql.conf snippets the external
// extensions selected for this run need applied to the cluster before postgres
// starts: each extension's ServerConfigFile, plus one generated snippet holding
// the merged shared_preload_libraries list (ExternalExtension.PreloadLibraries).
// The preload list is generated rather than kept in per-extension files because
// shared_preload_libraries is a single list-valued GUC and appended snippets are
// last-write-wins per GUC — two extensions' files would silently clobber each
// other's library. PGEXTERNAL_TESTS narrowing is honored via ExternalBuildList
// so dependency-only modules get their required config too.
//
// These snippets are scoped to the EXTERNAL phase's cluster only:
//   - In an external-only run (no other suite selected) the shared setup
//     applies them at initial initdb (externalOnlySuite gates that below).
//   - In a combined run the other suites come first and must run on a STOCK
//     cluster — the preloads are not always inert (plpgsql_check's cursor-leak
//     detection emits WARNINGs the core plpgsql test doesn't expect, and it
//     cannot be disabled: upstream plpgsql_check hangs any exception-trapping
//     function when cursors_leaks is off — reproduced on stock PostgreSQL
//     17.6 with v2.9.1 and master). The external phase is last, so
//     TestPostgreSQLRegression appends these via AddPgInitdbExtraConfFiles
//     right before the ReinitializeCluster that precedes it.
func externalServerConfPaths() []string {
	var paths []string
	for _, ext := range ExternalBuildList() {
		if ext.ServerConfigFile == "" {
			continue
		}
		paths = append(paths, testdataConfPath("external", ext.ServerConfigFile))
	}
	if p := generatedVaultGetKeyConfPath(); p != "" {
		paths = append(paths, p)
	}
	if p := generatedPreloadConfPath(); p != "" {
		paths = append(paths, p)
	}
	return paths
}

// externalOnlySuite reports whether this run executes ONLY the external suite,
// in which case there is no later reinitialization and the external server
// config must be applied at initial cluster setup.
func externalOnlySuite() bool {
	if os.Getenv(suiteutil.EnvRunExtendedQueryServingTests) == "1" {
		return false // extended gate runs every suite
	}
	return os.Getenv("RUN_PGEXTERNAL") == "1" &&
		os.Getenv("RUN_PGREGRESS") != "1" &&
		os.Getenv("RUN_PGISOLATION") != "1" &&
		os.Getenv("RUN_PGCONTRIB") != "1"
}

// generatedPreloadConfPath writes a postgresql.conf snippet with the merged
// shared_preload_libraries list for the selected external extensions and
// returns its path, or "" when none of them need a preload (no file is written
// then, so the cluster's shared_preload_libraries stays at the template
// default). The file lands in a fresh temp dir; it is tiny and the OS cleans
// the temp tree, so no explicit teardown is needed (the shared cluster setup
// outlives any single test's TempDir anyway).
func generatedPreloadConfPath() string {
	libs := ExternalPreloadLibraries()
	if len(libs) == 0 {
		return ""
	}
	dir, err := os.MkdirTemp("", "pgregress-preload-")
	if err != nil {
		panic(fmt.Sprintf("pgregresstest: create preload conf dir: %v", err))
	}
	path := filepath.Join(dir, "shared_preload_libraries.conf")
	content := fmt.Sprintf("# Generated by pgregresstest (externalServerConfPaths): the merged\n"+
		"# shared_preload_libraries for the external extensions selected in this run\n"+
		"# (ExternalExtension.PreloadLibraries). Appended after the pgctld template,\n"+
		"# so this wins.\n"+
		"shared_preload_libraries = '%s'\n", strings.Join(libs, ","))
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		panic(fmt.Sprintf("pgregresstest: write preload conf: %v", err))
	}
	return path
}

// generatedVaultGetKeyConfPath writes a deterministic test-only getkey script
// for supabase_vault and a postgresql.conf snippet pointing vault.getkey_script
// at it. The script must exist before postgres starts because supabase_vault
// reads the key from _PG_init when it is preloaded.
func generatedVaultGetKeyConfPath() string {
	needsVaultKey := false
	for _, ext := range ExternalBuildList() {
		if ext.NeedsVaultKey {
			needsVaultKey = true
			break
		}
	}
	if !needsVaultKey {
		return ""
	}

	dir, err := os.MkdirTemp("", "pgregress-vault-key-")
	if err != nil {
		panic(fmt.Sprintf("pgregresstest: create vault key dir: %v", err))
	}
	scriptPath := filepath.Join(dir, "vault_getkey.sh")
	const key = "000102030405060708090a0b0c0d0e0f000102030405060708090a0b0c0d0e0f"
	if err := os.WriteFile(scriptPath, []byte("#!/bin/sh\nprintf '%s\\n' '"+key+"'\n"), 0o700); err != nil {
		panic(fmt.Sprintf("pgregresstest: write vault getkey script: %v", err))
	}

	confPath := filepath.Join(dir, "vault_getkey.conf")
	quotedScriptPath := strings.ReplaceAll(scriptPath, "'", "''")
	content := fmt.Sprintf("# Generated by pgregresstest (externalServerConfPaths):\n"+
		"# deterministic test-only root key for supabase_vault.\n"+
		"vault.getkey_script = '%s'\n", quotedScriptPath)
	if err := os.WriteFile(confPath, []byte(content), 0o644); err != nil {
		panic(fmt.Sprintf("pgregresstest: write vault getkey conf: %v", err))
	}
	return confPath
}

// setupManager manages the shared test setup for tests in this package.
var setupManager = shardsetup.NewSharedSetupManager(func(t *testing.T) *shardsetup.ShardSetup {
	opts := []shardsetup.SetupOption{
		shardsetup.WithMultipoolerCount(2), // primary + standby
		shardsetup.WithMultigateway(),      // enable multigateway for PostgreSQL connections
		// Force C locale on initdb so locale-sensitive expected outputs
		// (char/varchar collation, to_char 'L' currency symbol, etc.) reproduce
		// upstream PostgreSQL behavior. Keep UTF8 encoding so the unicode /
		// collate.utf8 / json_encoding tests still see a real multibyte
		// codec — pg_regress upstream runs initdb with just --no-locale
		// (locale=C) and inherits the default encoding (UTF8 on modern
		// installs); --encoding=SQL_ASCII would break those tests.
		shardsetup.WithPgInitdbArgs("--no-locale --encoding=UTF8"),
		// The pgctld postgresql.conf template hard-codes en_US.UTF-8 for the
		// locale GUCs, which overrides initdb's --no-locale. Append a snippet
		// that resets lc_* to 'C' so currency/number/time/message formatting
		// matches upstream expected fixtures.
		shardsetup.WithPgInitdbExtraConfFiles(regressionOverridesConfPath()),
	}
	// Some external extensions need server-level config the pooled query path
	// can't set (pg_cron's background worker needs shared_preload_libraries).
	// Apply their snippets at initial setup ONLY when the external suite is the
	// only one running; in combined runs the earlier suites must see a stock
	// cluster, so TestPostgreSQLRegression appends the snippets right before
	// the reinitialization that precedes the external phase instead. See
	// externalServerConfPaths.
	if externalOnlySuite() {
		if confs := externalServerConfPaths(); len(confs) > 0 {
			opts = append(opts, shardsetup.WithPgInitdbExtraConfFiles(confs...))
		}
	}
	return shardsetup.New(t, opts...)
})

// TestMain sets the path and cleans up after all tests.
func TestMain(m *testing.M) {
	exitCode := shardsetup.RunTestMain(m)
	if exitCode != 0 {
		setupManager.DumpLogs()
	}
	setupManager.Cleanup()
	os.Exit(exitCode) //nolint:forbidigo // TestMain() is allowed to call os.Exit
}

// getSharedSetup returns the shared setup for tests.
func getSharedSetup(t *testing.T) *shardsetup.ShardSetup {
	t.Helper()
	return setupManager.Get(t)
}
