// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by proto-to-struct. DO NOT EDIT.
// Source: clustermetadata.proto
// Generated: 2025-11-25T09:33:25-05:00

package types

import (
	"time"

	"google.golang.org/protobuf/types/known/timestamppb"

	pb "github.com/multigres/multigres/go/pb/clustermetadata"
)

// Helper functions for type conversions

func copyStringSlice(s []string) []string {
	if s == nil {
		return nil
	}
	c := make([]string, len(s))
	copy(c, s)
	return c
}

func copyBytes(b []byte) []byte {
	if b == nil {
		return nil
	}
	c := make([]byte, len(b))
	copy(c, b)
	return c
}

func copyStringInt32Map(m map[string]int32) map[string]int32 {
	if m == nil {
		return nil
	}
	c := make(map[string]int32, len(m))
	for k, v := range m {
		c[k] = v
	}
	return c
}

func protoTimestampToTime(ts *timestamppb.Timestamp) time.Time {
	if ts == nil {
		return time.Time{}
	}
	return ts.AsTime()
}

func timeToProtoTimestamp(t time.Time) *timestamppb.Timestamp {
	if t.IsZero() {
		return nil
	}
	return timestamppb.New(t)
}

// Cell is an immutable plain Go struct mirroring pb.Cell.
type Cell struct {
	Name            string
	ServerAddresses []string
	Root            string
}

// CellFromProto creates a Cell from a protobuf message.
func CellFromProto(p *pb.Cell) Cell {
	if p == nil {
		return Cell{}
	}
	return Cell{
		Name:            p.GetName(),
		ServerAddresses: copyStringSlice(p.GetServerAddresses()),
		Root:            p.GetRoot(),
	}
}

// ToProto converts back to a protobuf message.
func (s Cell) ToProto() *pb.Cell {
	return &pb.Cell{
		Name:            s.Name,
		ServerAddresses: copyStringSlice(s.ServerAddresses),
		Root:            s.Root,
	}
}

// Database is an immutable plain Go struct mirroring pb.Database.
type Database struct {
	Name             string
	BackupLocation   string
	DurabilityPolicy string
	Cells            []string
}

// DatabaseFromProto creates a Database from a protobuf message.
func DatabaseFromProto(p *pb.Database) Database {
	if p == nil {
		return Database{}
	}
	return Database{
		Name:             p.GetName(),
		BackupLocation:   p.GetBackupLocation(),
		DurabilityPolicy: p.GetDurabilityPolicy(),
		Cells:            copyStringSlice(p.GetCells()),
	}
}

// ToProto converts back to a protobuf message.
func (s Database) ToProto() *pb.Database {
	return &pb.Database{
		Name:             s.Name,
		BackupLocation:   s.BackupLocation,
		DurabilityPolicy: s.DurabilityPolicy,
		Cells:            copyStringSlice(s.Cells),
	}
}

// DurabilityPolicy is an immutable plain Go struct mirroring pb.DurabilityPolicy.
type DurabilityPolicy struct {
	PolicyName    string
	PolicyVersion int64
	QuorumRule    QuorumRule
	IsActive      bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// DurabilityPolicyFromProto creates a DurabilityPolicy from a protobuf message.
func DurabilityPolicyFromProto(p *pb.DurabilityPolicy) DurabilityPolicy {
	if p == nil {
		return DurabilityPolicy{}
	}
	return DurabilityPolicy{
		PolicyName:    p.GetPolicyName(),
		PolicyVersion: p.GetPolicyVersion(),
		QuorumRule:    QuorumRuleFromProto(p.GetQuorumRule()),
		IsActive:      p.GetIsActive(),
		CreatedAt:     protoTimestampToTime(p.GetCreatedAt()),
		UpdatedAt:     protoTimestampToTime(p.GetUpdatedAt()),
	}
}

// ToProto converts back to a protobuf message.
func (s DurabilityPolicy) ToProto() *pb.DurabilityPolicy {
	return &pb.DurabilityPolicy{
		PolicyName:    s.PolicyName,
		PolicyVersion: s.PolicyVersion,
		QuorumRule:    s.QuorumRule.ToProto(),
		IsActive:      s.IsActive,
		CreatedAt:     timeToProtoTimestamp(s.CreatedAt),
		UpdatedAt:     timeToProtoTimestamp(s.UpdatedAt),
	}
}

// GlobalTopoConfig is an immutable plain Go struct mirroring pb.GlobalTopoConfig.
type GlobalTopoConfig struct {
	Implementation  string
	ServerAddresses []string
	Root            string
}

// GlobalTopoConfigFromProto creates a GlobalTopoConfig from a protobuf message.
func GlobalTopoConfigFromProto(p *pb.GlobalTopoConfig) GlobalTopoConfig {
	if p == nil {
		return GlobalTopoConfig{}
	}
	return GlobalTopoConfig{
		Implementation:  p.GetImplementation(),
		ServerAddresses: copyStringSlice(p.GetServerAddresses()),
		Root:            p.GetRoot(),
	}
}

// ToProto converts back to a protobuf message.
func (s GlobalTopoConfig) ToProto() *pb.GlobalTopoConfig {
	return &pb.GlobalTopoConfig{
		Implementation:  s.Implementation,
		ServerAddresses: copyStringSlice(s.ServerAddresses),
		Root:            s.Root,
	}
}

// ID is an immutable plain Go struct mirroring pb.ID.
type ID struct {
	Component pb.ID_ComponentType
	Cell      string
	Name      string
}

// IDFromProto creates a ID from a protobuf message.
func IDFromProto(p *pb.ID) ID {
	if p == nil {
		return ID{}
	}
	return ID{
		Component: p.GetComponent(),
		Cell:      p.GetCell(),
		Name:      p.GetName(),
	}
}

// ToProto converts back to a protobuf message.
func (s ID) ToProto() *pb.ID {
	return &pb.ID{
		Component: s.Component,
		Cell:      s.Cell,
		Name:      s.Name,
	}
}

// KeyRange is an immutable plain Go struct mirroring pb.KeyRange.
type KeyRange struct {
	Start []byte
	End   []byte
}

// KeyRangeFromProto creates a KeyRange from a protobuf message.
func KeyRangeFromProto(p *pb.KeyRange) KeyRange {
	if p == nil {
		return KeyRange{}
	}
	return KeyRange{
		Start: copyBytes(p.GetStart()),
		End:   copyBytes(p.GetEnd()),
	}
}

// ToProto converts back to a protobuf message.
func (s KeyRange) ToProto() *pb.KeyRange {
	return &pb.KeyRange{
		Start: copyBytes(s.Start),
		End:   copyBytes(s.End),
	}
}

// MultiGateway is an immutable plain Go struct mirroring pb.MultiGateway.
type MultiGateway struct {
	Id       ID
	Hostname string
	PortMap  map[string]int32
}

// MultiGatewayFromProto creates a MultiGateway from a protobuf message.
func MultiGatewayFromProto(p *pb.MultiGateway) MultiGateway {
	if p == nil {
		return MultiGateway{}
	}
	return MultiGateway{
		Id:       IDFromProto(p.GetId()),
		Hostname: p.GetHostname(),
		PortMap:  copyStringInt32Map(p.GetPortMap()),
	}
}

// ToProto converts back to a protobuf message.
func (s MultiGateway) ToProto() *pb.MultiGateway {
	return &pb.MultiGateway{
		Id:       s.Id.ToProto(),
		Hostname: s.Hostname,
		PortMap:  copyStringInt32Map(s.PortMap),
	}
}

// MultiOrch is an immutable plain Go struct mirroring pb.MultiOrch.
type MultiOrch struct {
	Id       ID
	Hostname string
	PortMap  map[string]int32
}

// MultiOrchFromProto creates a MultiOrch from a protobuf message.
func MultiOrchFromProto(p *pb.MultiOrch) MultiOrch {
	if p == nil {
		return MultiOrch{}
	}
	return MultiOrch{
		Id:       IDFromProto(p.GetId()),
		Hostname: p.GetHostname(),
		PortMap:  copyStringInt32Map(p.GetPortMap()),
	}
}

// ToProto converts back to a protobuf message.
func (s MultiOrch) ToProto() *pb.MultiOrch {
	return &pb.MultiOrch{
		Id:       s.Id.ToProto(),
		Hostname: s.Hostname,
		PortMap:  copyStringInt32Map(s.PortMap),
	}
}

// MultiPooler is an immutable plain Go struct mirroring pb.MultiPooler.
type MultiPooler struct {
	Id            ID
	Database      string
	TableGroup    string
	Shard         string
	KeyRange      KeyRange
	Type          pb.PoolerType
	ServingStatus pb.PoolerServingStatus
	Hostname      string
	PortMap       map[string]int32
}

// MultiPoolerFromProto creates a MultiPooler from a protobuf message.
func MultiPoolerFromProto(p *pb.MultiPooler) MultiPooler {
	if p == nil {
		return MultiPooler{}
	}
	return MultiPooler{
		Id:            IDFromProto(p.GetId()),
		Database:      p.GetDatabase(),
		TableGroup:    p.GetTableGroup(),
		Shard:         p.GetShard(),
		KeyRange:      KeyRangeFromProto(p.GetKeyRange()),
		Type:          p.GetType(),
		ServingStatus: p.GetServingStatus(),
		Hostname:      p.GetHostname(),
		PortMap:       copyStringInt32Map(p.GetPortMap()),
	}
}

// ToProto converts back to a protobuf message.
func (s MultiPooler) ToProto() *pb.MultiPooler {
	return &pb.MultiPooler{
		Id:            s.Id.ToProto(),
		Database:      s.Database,
		TableGroup:    s.TableGroup,
		Shard:         s.Shard,
		KeyRange:      s.KeyRange.ToProto(),
		Type:          s.Type,
		ServingStatus: s.ServingStatus,
		Hostname:      s.Hostname,
		PortMap:       copyStringInt32Map(s.PortMap),
	}
}

// QuorumRule is an immutable plain Go struct mirroring pb.QuorumRule.
type QuorumRule struct {
	QuorumType    pb.QuorumType
	RequiredCount int32
	Description   string
	AsyncFallback pb.AsyncReplicationFallbackMode
}

// QuorumRuleFromProto creates a QuorumRule from a protobuf message.
func QuorumRuleFromProto(p *pb.QuorumRule) QuorumRule {
	if p == nil {
		return QuorumRule{}
	}
	return QuorumRule{
		QuorumType:    p.GetQuorumType(),
		RequiredCount: p.GetRequiredCount(),
		Description:   p.GetDescription(),
		AsyncFallback: p.GetAsyncFallback(),
	}
}

// ToProto converts back to a protobuf message.
func (s QuorumRule) ToProto() *pb.QuorumRule {
	return &pb.QuorumRule{
		QuorumType:    s.QuorumType,
		RequiredCount: s.RequiredCount,
		Description:   s.Description,
		AsyncFallback: s.AsyncFallback,
	}
}
