// Copyright 2025 Supabase, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: consensusdata.proto

package consensusdata

import (
	clustermetadata "github.com/multigres/multigres/go/pb/clustermetadata"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Action type for BeginTerm operations
// Indicates what action to execute in addition to term acceptance
type BeginTermAction int32

const (
	// Default/unknown action
	BeginTermAction_BEGIN_TERM_ACTION_UNSPECIFIED BeginTermAction = 0
	// No additional action - only accept the term
	BeginTermAction_BEGIN_TERM_ACTION_NO_ACTION BeginTermAction = 1
	// Revoke the current term by demoting primary or pausing standby replication
	// This is used during failover to ensure the old primary stops accepting writes
	BeginTermAction_BEGIN_TERM_ACTION_REVOKE BeginTermAction = 2
)

// Enum value maps for BeginTermAction.
var (
	BeginTermAction_name = map[int32]string{
		0: "BEGIN_TERM_ACTION_UNSPECIFIED",
		1: "BEGIN_TERM_ACTION_NO_ACTION",
		2: "BEGIN_TERM_ACTION_REVOKE",
	}
	BeginTermAction_value = map[string]int32{
		"BEGIN_TERM_ACTION_UNSPECIFIED": 0,
		"BEGIN_TERM_ACTION_NO_ACTION":   1,
		"BEGIN_TERM_ACTION_REVOKE":      2,
	}
)

func (x BeginTermAction) Enum() *BeginTermAction {
	p := new(BeginTermAction)
	*p = x
	return p
}

func (x BeginTermAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BeginTermAction) Descriptor() protoreflect.EnumDescriptor {
	return file_consensusdata_proto_enumTypes[0].Descriptor()
}

func (BeginTermAction) Type() protoreflect.EnumType {
	return &file_consensusdata_proto_enumTypes[0]
}

func (x BeginTermAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BeginTermAction.Descriptor instead.
func (BeginTermAction) EnumDescriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{0}
}

// WAL position for tracking replication state
type WALPosition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// For primary: current write position from pg_current_wal_lsn()
	// For standby: empty (use last_receive_lsn and last_replay_lsn instead)
	CurrentLsn string `protobuf:"bytes,1,opt,name=current_lsn,json=currentLsn,proto3" json:"current_lsn,omitempty"`
	// For standby: last WAL position received from pg_last_wal_receive_lsn()
	// For primary: empty
	LastReceiveLsn string `protobuf:"bytes,2,opt,name=last_receive_lsn,json=lastReceiveLsn,proto3" json:"last_receive_lsn,omitempty"`
	// For standby: last WAL position replayed from pg_last_wal_replay_lsn()
	// For primary: empty
	LastReplayLsn string `protobuf:"bytes,3,opt,name=last_replay_lsn,json=lastReplayLsn,proto3" json:"last_replay_lsn,omitempty"`
	// Timestamp when this position was recorded
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// PostgreSQL timeline ID from pg_control_checkpoint().
	// Retained for observability and as a secondary safety check during candidate
	// selection (see leadership_term).
	TimelineId int64 `protobuf:"varint,5,opt,name=timeline_id,json=timelineId,proto3" json:"timeline_id,omitempty"`
	// Term number from the most recent multigres.leadership_history record, read
	// after WAL replay stabilizes during revoke. Used as the primary criterion for
	// candidate selection: a node that has replicated a higher consensus term has
	// applied more of the agreed WAL history, regardless of LSN.
	// LSN is used as a tiebreaker only when both term and timeline are equal.
	// 0 if the leadership_history table is empty (e.g. pre-bootstrap).
	LeadershipTerm int64 `protobuf:"varint,6,opt,name=leadership_term,json=leadershipTerm,proto3" json:"leadership_term,omitempty"`
	// Cohort members from the most recent multigres.leadership_history record
	// (application-name strings, same encoding as the table's cohort_members JSONB
	// column). Empty if the table is empty. Allows the coordinator to see which
	// cohort was active on each standby at the time of its last leadership event.
	CohortMembers []string `protobuf:"bytes,7,rep,name=cohort_members,json=cohortMembers,proto3" json:"cohort_members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WALPosition) Reset() {
	*x = WALPosition{}
	mi := &file_consensusdata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WALPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WALPosition) ProtoMessage() {}

func (x *WALPosition) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WALPosition.ProtoReflect.Descriptor instead.
func (*WALPosition) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{0}
}

func (x *WALPosition) GetCurrentLsn() string {
	if x != nil {
		return x.CurrentLsn
	}
	return ""
}

func (x *WALPosition) GetLastReceiveLsn() string {
	if x != nil {
		return x.LastReceiveLsn
	}
	return ""
}

func (x *WALPosition) GetLastReplayLsn() string {
	if x != nil {
		return x.LastReplayLsn
	}
	return ""
}

func (x *WALPosition) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WALPosition) GetTimelineId() int64 {
	if x != nil {
		return x.TimelineId
	}
	return 0
}

func (x *WALPosition) GetLeadershipTerm() int64 {
	if x != nil {
		return x.LeadershipTerm
	}
	return 0
}

func (x *WALPosition) GetCohortMembers() []string {
	if x != nil {
		return x.CohortMembers
	}
	return nil
}

// BeginTerm is sent by coordinators during leader appointments
type BeginTermRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Term of the candidate
	Term int64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// ID of the candidate for appointment
	CandidateId *clustermetadata.ID `protobuf:"bytes,2,opt,name=candidate_id,json=candidateId,proto3" json:"candidate_id,omitempty"`
	// Shard ID for this appointment
	ShardId string `protobuf:"bytes,3,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	// Version of the durability policy
	PolicyVersion int64 `protobuf:"varint,4,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	// Action type for this BeginTerm operation
	// Indicates what scenario triggered this term change
	Action        BeginTermAction `protobuf:"varint,5,opt,name=action,proto3,enum=consensusdata.BeginTermAction" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTermRequest) Reset() {
	*x = BeginTermRequest{}
	mi := &file_consensusdata_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTermRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTermRequest) ProtoMessage() {}

func (x *BeginTermRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTermRequest.ProtoReflect.Descriptor instead.
func (*BeginTermRequest) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{1}
}

func (x *BeginTermRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *BeginTermRequest) GetCandidateId() *clustermetadata.ID {
	if x != nil {
		return x.CandidateId
	}
	return nil
}

func (x *BeginTermRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

func (x *BeginTermRequest) GetPolicyVersion() int64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *BeginTermRequest) GetAction() BeginTermAction {
	if x != nil {
		return x.Action
	}
	return BeginTermAction_BEGIN_TERM_ACTION_UNSPECIFIED
}

type BeginTermResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current term, for candidate to update itself
	Term int64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// True if the term was accepted
	Accepted bool `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// ID of the responding pooler
	PoolerId string `protobuf:"bytes,3,opt,name=pooler_id,json=poolerId,proto3" json:"pooler_id,omitempty"`
	// WAL position for candidate selection
	WalPosition *WALPosition `protobuf:"bytes,4,opt,name=wal_position,json=walPosition,proto3" json:"wal_position,omitempty"`
	// The pooler's consensus status at the time of the response.
	// For REVOKE actions, captured after WAL positions are frozen (post-revoke snapshot).
	// May be nil if postgres is unreachable.
	ConsensusStatus *clustermetadata.ConsensusStatus `protobuf:"bytes,5,opt,name=consensus_status,json=consensusStatus,proto3" json:"consensus_status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BeginTermResponse) Reset() {
	*x = BeginTermResponse{}
	mi := &file_consensusdata_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTermResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTermResponse) ProtoMessage() {}

func (x *BeginTermResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTermResponse.ProtoReflect.Descriptor instead.
func (*BeginTermResponse) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{2}
}

func (x *BeginTermResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *BeginTermResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *BeginTermResponse) GetPoolerId() string {
	if x != nil {
		return x.PoolerId
	}
	return ""
}

func (x *BeginTermResponse) GetWalPosition() *WALPosition {
	if x != nil {
		return x.WalPosition
	}
	return nil
}

func (x *BeginTermResponse) GetConsensusStatus() *clustermetadata.ConsensusStatus {
	if x != nil {
		return x.ConsensusStatus
	}
	return nil
}

// Status returns the current status of a node
type StatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional term to include in response
	Term int64 `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	// Shard ID to query status for
	ShardId       string `protobuf:"bytes,2,opt,name=shard_id,json=shardId,proto3" json:"shard_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_consensusdata_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{3}
}

func (x *StatusRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *StatusRequest) GetShardId() string {
	if x != nil {
		return x.ShardId
	}
	return ""
}

type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity of the responding node. Always set, even when postgres is
	// unavailable and consensus_status cannot be constructed.
	Id *clustermetadata.ID `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	// The term for which this multipooler was promoted to primary.
	// Set during promotion (Promote).
	// Preserved when consensus term increases (new elections).
	// Cleared to 0 when demoted (DemoteStalePrimary) or restored from backup.
	// 0 if never primary. For current primaries, must be non-zero.
	PrimaryTerm int64 `protobuf:"varint,11,opt,name=primary_term,json=primaryTerm,proto3" json:"primary_term,omitempty"`
	// The pooler's current consensus status: its term revocation, committed
	// rule position, and highest known rule. Authoritative view of where this
	// pooler stands in the distributed system. Nil when postgres is unavailable.
	ConsensusStatus *clustermetadata.ConsensusStatus `protobuf:"bytes,12,opt,name=consensus_status,json=consensusStatus,proto3" json:"consensus_status,omitempty"`
	// Best-effort operational fitness signals for this node. These signals are
	// in-memory and may be absent after a process restart. Coordinators treat
	// absence as "unknown," not "unfit."
	AvailabilityStatus *clustermetadata.AvailabilityStatus `protobuf:"bytes,13,opt,name=availability_status,json=availabilityStatus,proto3" json:"availability_status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_consensusdata_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_consensusdata_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_consensusdata_proto_rawDescGZIP(), []int{4}
}

func (x *StatusResponse) GetId() *clustermetadata.ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *StatusResponse) GetPrimaryTerm() int64 {
	if x != nil {
		return x.PrimaryTerm
	}
	return 0
}

func (x *StatusResponse) GetConsensusStatus() *clustermetadata.ConsensusStatus {
	if x != nil {
		return x.ConsensusStatus
	}
	return nil
}

func (x *StatusResponse) GetAvailabilityStatus() *clustermetadata.AvailabilityStatus {
	if x != nil {
		return x.AvailabilityStatus
	}
	return nil
}

var File_consensusdata_proto protoreflect.FileDescriptor

const file_consensusdata_proto_rawDesc = "" +
	"\n" +
	"\x13consensusdata.proto\x12\rconsensusdata\x1a\x15clustermetadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xab\x02\n" +
	"\vWALPosition\x12\x1f\n" +
	"\vcurrent_lsn\x18\x01 \x01(\tR\n" +
	"currentLsn\x12(\n" +
	"\x10last_receive_lsn\x18\x02 \x01(\tR\x0elastReceiveLsn\x12&\n" +
	"\x0flast_replay_lsn\x18\x03 \x01(\tR\rlastReplayLsn\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vtimeline_id\x18\x05 \x01(\x03R\n" +
	"timelineId\x12'\n" +
	"\x0fleadership_term\x18\x06 \x01(\x03R\x0eleadershipTerm\x12%\n" +
	"\x0ecohort_members\x18\a \x03(\tR\rcohortMembers\"\xd8\x01\n" +
	"\x10BeginTermRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x126\n" +
	"\fcandidate_id\x18\x02 \x01(\v2\x13.clustermetadata.IDR\vcandidateId\x12\x19\n" +
	"\bshard_id\x18\x03 \x01(\tR\ashardId\x12%\n" +
	"\x0epolicy_version\x18\x04 \x01(\x03R\rpolicyVersion\x126\n" +
	"\x06action\x18\x05 \x01(\x0e2\x1e.consensusdata.BeginTermActionR\x06action\"\xec\x01\n" +
	"\x11BeginTermResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x1b\n" +
	"\tpooler_id\x18\x03 \x01(\tR\bpoolerId\x12=\n" +
	"\fwal_position\x18\x04 \x01(\v2\x1a.consensusdata.WALPositionR\vwalPosition\x12K\n" +
	"\x10consensus_status\x18\x05 \x01(\v2 .clustermetadata.ConsensusStatusR\x0fconsensusStatus\">\n" +
	"\rStatusRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x19\n" +
	"\bshard_id\x18\x02 \x01(\tR\ashardId\"\xfb\x01\n" +
	"\x0eStatusResponse\x12#\n" +
	"\x02id\x18\x04 \x01(\v2\x13.clustermetadata.IDR\x02id\x12!\n" +
	"\fprimary_term\x18\v \x01(\x03R\vprimaryTerm\x12K\n" +
	"\x10consensus_status\x18\f \x01(\v2 .clustermetadata.ConsensusStatusR\x0fconsensusStatus\x12T\n" +
	"\x13availability_status\x18\r \x01(\v2#.clustermetadata.AvailabilityStatusR\x12availabilityStatus*s\n" +
	"\x0fBeginTermAction\x12!\n" +
	"\x1dBEGIN_TERM_ACTION_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bBEGIN_TERM_ACTION_NO_ACTION\x10\x01\x12\x1c\n" +
	"\x18BEGIN_TERM_ACTION_REVOKE\x10\x02B4Z2github.com/multigres/multigres/go/pb/consensusdatab\x06proto3"

var (
	file_consensusdata_proto_rawDescOnce sync.Once
	file_consensusdata_proto_rawDescData []byte
)

func file_consensusdata_proto_rawDescGZIP() []byte {
	file_consensusdata_proto_rawDescOnce.Do(func() {
		file_consensusdata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_consensusdata_proto_rawDesc), len(file_consensusdata_proto_rawDesc)))
	})
	return file_consensusdata_proto_rawDescData
}

var file_consensusdata_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_consensusdata_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_consensusdata_proto_goTypes = []any{
	(BeginTermAction)(0),                       // 0: consensusdata.BeginTermAction
	(*WALPosition)(nil),                        // 1: consensusdata.WALPosition
	(*BeginTermRequest)(nil),                   // 2: consensusdata.BeginTermRequest
	(*BeginTermResponse)(nil),                  // 3: consensusdata.BeginTermResponse
	(*StatusRequest)(nil),                      // 4: consensusdata.StatusRequest
	(*StatusResponse)(nil),                     // 5: consensusdata.StatusResponse
	(*timestamppb.Timestamp)(nil),              // 6: google.protobuf.Timestamp
	(*clustermetadata.ID)(nil),                 // 7: clustermetadata.ID
	(*clustermetadata.ConsensusStatus)(nil),    // 8: clustermetadata.ConsensusStatus
	(*clustermetadata.AvailabilityStatus)(nil), // 9: clustermetadata.AvailabilityStatus
}
var file_consensusdata_proto_depIdxs = []int32{
	6, // 0: consensusdata.WALPosition.timestamp:type_name -> google.protobuf.Timestamp
	7, // 1: consensusdata.BeginTermRequest.candidate_id:type_name -> clustermetadata.ID
	0, // 2: consensusdata.BeginTermRequest.action:type_name -> consensusdata.BeginTermAction
	1, // 3: consensusdata.BeginTermResponse.wal_position:type_name -> consensusdata.WALPosition
	8, // 4: consensusdata.BeginTermResponse.consensus_status:type_name -> clustermetadata.ConsensusStatus
	7, // 5: consensusdata.StatusResponse.id:type_name -> clustermetadata.ID
	8, // 6: consensusdata.StatusResponse.consensus_status:type_name -> clustermetadata.ConsensusStatus
	9, // 7: consensusdata.StatusResponse.availability_status:type_name -> clustermetadata.AvailabilityStatus
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_consensusdata_proto_init() }
func file_consensusdata_proto_init() {
	if File_consensusdata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_consensusdata_proto_rawDesc), len(file_consensusdata_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_consensusdata_proto_goTypes,
		DependencyIndexes: file_consensusdata_proto_depIdxs,
		EnumInfos:         file_consensusdata_proto_enumTypes,
		MessageInfos:      file_consensusdata_proto_msgTypes,
	}.Build()
	File_consensusdata_proto = out.File
	file_consensusdata_proto_goTypes = nil
	file_consensusdata_proto_depIdxs = nil
}
