#!/bin/bash
# Copyright 2025 The Multigres Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Git pre-commit hook to check license headers

# Get list of staged files that match our criteria
staged_files=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(go|proto|sh|yaml|yml)$' | grep -v -E '^(site/|pb/|dist/|bin/)')

if [ -z "$staged_files" ]; then
    # No relevant files staged
    exit 0
fi

# Check license headers using our script
./bash_tools/check_license.sh $staged_files